### ISSUE TITLE
Some handlers not working ... after fix #517

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#1007]
Good morning,

for some reason drag, rotate, freerotate and other handlers won't do his job in some circumstances.

After a lot of time debugging the code, to find the problem I have noticed that changes in #517 has broke the usual behavior of this handlers.

I have noticed that the problem is in the function:

`  _cornerExceedsMapLats: function(zoom, corner, map) {...}` on file DistortabeImageOverlay.js
 
 and the problem becomes in the next check:

```
    if (zoom === 0) {
      exceedsTop = map.project(corner).y < 2;
      exceedsBottom = map.project(corner).y >= 255;
    } else {
      exceedsTop = map.project(corner).y / zoom < 2;
      exceedsBottom = map.project(corner).y / Math.pow(2, zoom) >= 255;
    }
```

for some reason, in the map I use, the variable `map.project(corner).y` returns a negative value, and obviously this is always lower than 2

then next both checks return `True`:

`exceedsTop = map.project(corner).y < 2;`
or
`exceedsTop = map.project(corner).y / zoom < 2;`

and it make leave the normal execution of the handler function.

Im still not use why `map.project(corner).y` return a negative value, probably due the system coordinates Im using.

And probably this is a bug on the logics in the code. @jywarren

**Comment by themacboy** [comment]
console print of the check and value of variable :

`exceedsTop = map.project(corner).y / zoom < 2;`

![image](https://user-images.githubusercontent.com/8063711/182755162-f0896eee-1440-4bc7-a065-2971a71c14e7.png)

**Comment by themacboy** [comment]
Other output values:

map.project(corner).x = 12888737.999999993
map.project(corner).y = -147853214.99999997
object corner = {lat: 41.72958170926682, lng: 1.8309573804288197}

**Comment by jywarren** [comment]
Hmm, thanks for documenting this... can you share a screen recording of the issue? What projection are you using, L.CRS.Simple? Is there any way we can try out the code you're using interactively? Thanks again!

**Comment by themacboy** [comment]
Sorry Im not skilled on all this, not sure what kind of L.CRS im using, i copy you my lines to creqate the map:

            this.ocrs = new L.Proj.CRS('EPSG:25831', '+proj=utm +zone=31 +ellps=GRS80 +units=m +no_def', {
                resolutions: this.resolutions,
                origin: [0, 0]
            });

**Comment by themacboy** [comment]
this is the code I have modified to "patch" the issue (but really is a worng solution):

`  _cornerExceedsMapLats: function(zoom, corner, map) {
    var exceedsTop;
    var exceedsBottom;
    if (zoom === 0) {
      exceedsTop = Math.abs( map.project(corner).y ) < 2;
      exceedsBottom = Math.abs( map.project(corner).y ) >= 255;
    } else {
      exceedsTop = Math.abs( map.project(corner).y / zoom ) < 2;
      exceedsBottom = Math.abs( map.project(corner).y / Math.pow(2, zoom) ) >= 255;
    }
    return (exceedsTop || exceedsBottom);
  },
`

**Comment by jywarren** [comment]
No worries at all - that's very helpful -- would you be able to share the
entire HTML page so we can try it, maybe using gist.github.com? Thank you!

**Comment by jywarren** [comment]
Is it possible the projection is uniquely rejecting out of bounds coordinates and that we could bypass by actually limiting them to just under 180 or 90, so like 179.999 and 89.999? Just to avoid the situation entirely.

**Comment by jywarren** [comment]
Or might another solution be to just turn off this bounds limiting check for the L.CRS.simple projection until we can otherwise resolve it?

**Comment by jywarren** [comment]
@steveruiz @jbogdani does this last suggestion seem an ok workaround for you?

**Comment by steveruiz** [comment]
Yes - I think entirely turning off the bounds limiting check for L.CRS.Simple is the right way to go.

**Comment by jywarren** [comment]
Excellent, i will craft a first-timers-only issue from it and it should get completed soon then. Thank you!

**Comment by jywarren** [comment]
Just copying in info here as i go:

https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/DistortableImageOverlay.js#L213-L240

**Comment by jywarren** [comment]
This method is called twice, both times in that file:

https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/DistortableImageOverlay.js#L232-L234

and

https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/DistortableImageOverlay.js#L268

**Comment by jywarren** [comment]
Hi all, once the final steps are made in #1033 would you mind testing them out? Thank you!!

**Comment by jywarren** [comment]
Hello @themacboy @steveruiz @jbogdani @tadiraman can you check out the release candidate at https://github.com/publiclab/Leaflet.DistortableImage/pull/1036 (v0.21.9) to confirm if it does or doesn't address the issues you've been having? (remembering that we are guessing they are all inter-related but it's still possible this may fix things for some but not all of you?)

Thank you!

**Comment by jywarren** [comment]
Hi @themacboy @steveruiz @jbogdani @tadiraman just checking if you've been able to give this a try. No rush though. Thanks! <3

**Comment by themacboy** [comment]
With the exception in last update it is working as normal for me.

Not sure if there can be other issues, but now is working for sure

**Comment by jywarren** [comment]
Published!!!

**Comment by themacboy** [comment]
opsss but news! there is a error yet, sorry when I test the changes something remain in my browser cache. 

Now I go to PR a solution

**Comment by jywarren** [comment]
Oh, can you share the error? Can you try it in incognito mode? Thank you !
