### ISSUE TITLE
Fetch and display all the collection's images in the sidebar

### ISSUE THREAD

**Issue by PeculiarE** [publiclab/Leaflet.DistortableImage#1013]
On inputting a valid Internet Archive URL, the images saved in that collection should be displayed on the sidebar.

**Comment by jywarren** [comment]
Let's be aware that we'll need jQuery in there -- with `<script src='https://code.jquery.com/jquery-3.6.1.min.js'></script>`

and Leaflet used to use the same shortcut - `$` so if both libraries try to, there could be an issue. Try inserting that code below the leaflet code so hopefully it overwrites Leaflet's use of `$`, and we don't have any trouble. But watch out if it says it `$.get` is not defined!

Quoting from https://github.com/publiclab/Leaflet.DistortableImage/issues/998 --

> Code to fetch a gallery (CORS is now enabled for IA images) using jQuery `$.get()` function:

```js
$.get('https://archive.org/metadata/texas-barnraising/',function(response) { console.log(response) })
{readyState: 1, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
=> VM8221:1 {created: 1657632500, d1: 'ia600904.us.archive.org', d2: 'ia800904.us.archive.org', dir: '/27/items/texas-barnraising', files: Array(25), …}

i = new Image; i.src = "https://archive.org/download/texas-barnraising/IMG_0764.JPG";
=> 'https://archive.org/download/texas-barnraising/IMG_0764.JPG'
// will be at https://ia801507.us.archive.org/34/items/texas-barnraising/IMG_0764.JPG

i.width
=> 2592
```

**Comment by PeculiarE** [comment]
Hmmm...I used pure JS with axios instead. And yes, there's no clash of any sort. Is this okay, or must we use jQuery?

**Comment by jywarren** [comment]
It looks super, thank you!!

**Comment by PeculiarE** [comment]
Alright! Thanks, Jeff 😄
