### ISSUE TITLE
Get rotate angle of image layer

### ISSUE THREAD

**Issue by meygh** [publiclab/Leaflet.DistortableImage#102]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

Hello

How do I can get / set rotation degree for an image layer.
Something like: image.getRotate() / image.setRotate(45)
I can't find anything, please help me.

Thanks

**Comment by gauravano** [comment]
Hi @meygh, the issue has been updated by @jywarren. Please close the issue if the answer resolves your problem or if it's not required anymore. Thanks!

**Comment by rexagod** [comment]
@meygh Simple algebra here, I guess. First off, find the pivot by the intersection of both the diagonals formed by the corners (exposed). Once you have that, calculate the mid-point of any side (again, using the adjacent corners) then after rotation find the angle difference from the slopes of the initial and rotated lines. Let me know and I'll be happy to come up with a function that implements this.

**Comment by rexagod** [comment]
Uploaded to GCI Dashboard.

**Comment by SidharthBansal** [comment]
Published

**Comment by pythongiant** [comment]
Why was this opened again @sashadev-sky

**Comment by sashadev-sky** [comment]
@SidharthBansal @VladimirMikulic was this one definitely published on the dashboard and not just "Set degrees of rotation..." I can't find it! Just wanted to double check

**Comment by SidharthBansal** [comment]
@VladimirMikulic can check and get it approved from me asap. :-)

**Comment by VladimirMikulic** [comment]
@sashadev-sky this one was published on GCI dashboard and I claimed points for it.
In the description, it said to write `getAngle`, not `getRotate` and the other one was `setAngle` instead of `setRotate`.

@SidharthBansal thanks you've approved them already.

**Comment by sashadev-sky** [comment]
ok perfect
