### ISSUE TITLE
Replace `var` keyword with `let`/`const`

### ISSUE THREAD

**Issue by TildaDares** [publiclab/Leaflet.DistortableImage#1086]
Hi everyone, we'd like to update this project to use `let`/`const` instead of `var`. This task will be divided into several sub tasks and each one of you will get to work on one file. All you have to do is replace `var` with `let`/`const` where appropriate.

## General rules

Use `let` when you know that the value of a variable will change.
Use `const` for every other variable.

If you'd like to know more about the differences between these keywords, you can read this [freecodecamp article on var, let & const](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/)

### `src/components`

- [x] [DistortableImage.Keymapper.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/components/DistortableImage.Keymapper.js) - Reserved for @jesutobi

### `src/edit`

- [x] [DistortableImage.Edit.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/DistortableImage.Edit.js) - Reserved for @leilayesufu
- [x] [getEXIFdata.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/getEXIFdata.js) - Reserved for @AM-png

### `src/edit/actions`

- [x] [BorderAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/BorderAction.js) - Reserved for @Lovelyfin00
- [x] [DeleteAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/DeleteAction.js) - Reserved for @ijayhub
- [x] [DistortAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/DistortAction.js) - Reserved for @dayopius
- [x] [DragAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/DragAction.js) - Reserved for @belfarz
- [x] [EditAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/EditAction.js) - Reserved for @sahilbansal17
- [x] [ExportAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/ExportAction.js) - Reserved for @OluwatuyiAbiola
- [x] [FreeRotateAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/FreeRotateAction.js) - Reserved for @adetyaz
- [x] [GeolocateAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/GeolocateAction.js) - Reserved for @klaus139
- [x] [LockAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/LockAction.js) - Reserved for @chemistry-notfun
- [x] [OpacityAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/OpacityAction.js) - Reserved for @codeinvoke7
- [x] [RestoreAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/RestoreAction.js) - Reserved for @Ibom99
- [x] [RotateAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/RotateAction.js) - Reserved for @titiodus
- [x] [ScaleAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/ScaleAction.js) - Reserved for @THEDARKMAN007
- [x] [StackAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/StackAction.js) - Reserved for @abdelquodr
- [x] [UnlockAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/UnlockAction.js) - Reserved for @ @yukiyuli

### `src/edit/handles`

- [x] [DistortHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/DistortHandle.js) - Reserved for @ChiomaNwosisi
- [x] [DragHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/DragHandle.js) - Reserved for @mutmainaho
- [x] [EditHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/EditHandle.js) - Reserved for @obueto
- [x] [LockHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/LockHandle.js) - Reserved for @Mootconn
- [x] [RotateHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/RotateHandle.js) - Reserved for @Tammy-Ajoko
- [x] [ScaleHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/handles/ScaleHandle.js) - Reserved for @leumasxxx

### `src/edit/toolbar`

- [x] [DistortableImage.ControlBar.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/toolbars/DistortableImage.ControlBar.js) - Reserved for @haszankauna
- [x] [DistortableImage.PopupBar.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/toolbars/DistortableImage.PopupBar.js) - Reserved for @Achele

### `src/mapmixins`

- [x] [BoxCollector.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/mapmixins/BoxCollector.js) - Reserved for @Munnachienyi
- [x] [DoubleClickLabels.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/mapmixins/DoubleClickLabels.js) - Reserved for @TomisinAjayi
- [x] [DoubleClickZoom.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/mapmixins/DoubleClickZoom.js) - Reserved for @Jennifer-tech
- [x] [MapMixins.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/mapmixins/MapMixins.js) - Reserved for @Ranecodes

### `src/util`

- [x] [DomUtil.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/util/DomUtil.js) - Reserved for @meggiddy
- [x] [IconUtil.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/util/IconUtil.js) - Reserved for @xiaodaiweiwei
- [x] [ImageUtil.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/util/ImageUtil.js) - Reserved for @kabuur
- [x] [MatrixUtil.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/util/MatrixUtil.js) - Reserved for @tiffieangel
- [x] [Utils.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/util/Utils.js) - Reserved for @sainamercy

### `src`

- [x] [DistortableCollection.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/DistortableCollection.js) - Reserved for @RealRichi3
- [x] [DistortableImageOverlay.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/DistortableImageOverlay.js) - Reserved for @Thesaleem

**Comment by leilayesufu** [comment]
Hi @TildaDares 
Thank you for assigning a FTO issue to me 
I’d like to claim my issue and work on it

**Comment by ifeawoyemi** [comment]
I will do it

**Comment by ifeawoyemi** [comment]
I will take the Task @TildaDares

**Comment by Ibom99** [comment]
Hello @TildaDares I claim my task and I’ll work on it! Thank you!✨

**Comment by leumasxxx** [comment]
I claim this task @TildaDares

**Comment by mimi-tech** [comment]
Hello @TildaDares I calm this task

**Comment by Thesaleem** [comment]
Hi @TildaDares Thanks! I’ll work on it now.

**Comment by TildaDares** [comment]
Hi @mimi-tech, your name isn't included in this issue but rest assured we'll find something for you to work on. Thank you!

**Comment by Ranecodes** [comment]
Hi @TildaDares. Will be working on the task assigned to me. Thanks!

**Comment by THEDARKMAN007** [comment]
hi @TildaDares  i would like to let you know i will be working on the issue assigned to me at "https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/actions/ScaleAction.js"

**Comment by Tammy-Ajoko** [comment]
Hi @TildaDares thank you for this I'm currently working on it

**Comment by Jennifer-tech** [comment]
Thanks @TildaDares , I claim the task and I'm currently working on it

**Comment by titiodus** [comment]
I accept my issue and will work on it @TildaDares

**Comment by Tammy-Ajoko** [comment]
@TildaDares  there a section for screenshot before making the final pull request. I'm not sure on how to link it or can I just go on and make the pull request without it

**Comment by OluwatuyiAbiola** [comment]
HI @TildaDares I claim my issue

**Comment by TildaDares** [comment]
Hi @Tammy-Ajoko, you can ignore that. Thank you!

**Comment by klaus139** [comment]
Thanks for this @TildaDares  I am working on this

**Comment by ChiomaNwosisi** [comment]
Thank you @TildaDares i will work on this

**Comment by RealRichi3** [comment]
Thanks @TildaDares I will work on this

**Comment by ijayhub** [comment]
> 
HI @TildaDares I claim my issue

**Comment by THEDARKMAN007** [comment]
hi, @TildaDares I just made my first pull request at https://github.com/publiclab/Leaflet.DistortableImage/pull/1099 . id kindly appreciate it if you could get back to me on any other action I may need to take, or i may not have taken as regards the pull request.  thank you

**Comment by tiffieangel** [comment]
THanks @TildaDares I'm working on it

**Comment by xiaodaiweiwei** [comment]
Thank you for assigning a FTO issue to me. @TildaDares  I’d like to claim my issue and work on it!

**Comment by chemistry-notfun** [comment]
Hi @TildaDares I will work on it. Thank you!

**Comment by Lovelyfin00** [comment]
Thanks @TildaDares
I'm working on it

**Comment by xiaodaiweiwei** [comment]
> 



> Thank you for assigning a FTO issue to me. @TildaDares I’d like to claim my issue and work on it! #1103

I just pull request the fix and I'm not sure whether it's ok. This is the first time for me to submit and I found it's so interesting. I learned a lot from that. I am looking forward to the next contribution!

**Comment by sainamercy** [comment]
Thank you @TildaDares I'll work on the issue assigned to me

**Comment by fonkwe** [comment]
Greetings, am I too late to contribute ?

**Comment by Lovelyfin00** [comment]
@TildaDares  I just made a PR for the issue assigned to me  at #1106

**Comment by jesutobi** [comment]
@TildaDares Goodmorning thanks for assigning me to an FTO, would work start working on it

**Comment by abdelquodr** [comment]
@TildaDares, Looking into the task assigned to me. Thanks

**Comment by THEDARKMAN007** [comment]
hi @TildaDares @jywarren @cesswairimu  i just made my first pull request at https://github.com/publiclab/Leaflet.DistortableImage/pull/1099 id appreciate it being reviewed. thank you

**Comment by titiodus** [comment]
Hi @TildaDares Did I miss the message of the merge of my PR? Pls let me know if there's more to do. Thanks

**Comment by Munnachienyi** [comment]
i have worked on my FTO please review

**Comment by Favour-Cay** [comment]
Hi @TildaDares @cesswairimu id like to be assigned an FTO please

**Comment by victorvictoria-maker** [comment]
Hi @TildaDares, please I am yet to be assigned an FTO.
Thank you for your consideration.

**Comment by mimi-tech** [comment]
@TildaDares Please when will you assign me a task?

**Comment by Josephsanya** [comment]
Hi @TildaDares  I just made my first pull request at #1117
Please kindly review it. Thanks

**Comment by obueto** [comment]
Hi @TildaDares thank you for this I'm currently working on it

**Comment by Simplecodez** [comment]
Hi everyone. I am Emmanuel Elendu, an Outreachy applicant. Please a would love to work on a FTO issue

**Comment by codeinvoke7** [comment]
Hello @TildaDares I have opened a pr at #1121 please do kindly review and give feedback thanks

**Comment by AminMusah** [comment]
Hello @TildaDares, I'm an Outreachy applicant and would love to make my first contribution. thank you.

**Comment by 7malikk** [comment]
@TildaDares I'd like to get work on this, as it's reopened

**Comment by alexanderchosen** [comment]
@TildaDares please can I also work on this too. I am yet to be assigned an FTO issue
Thanks

**Comment by Dalu46** [comment]
Hi @jywarren I'm yet to be assigned an issue. Can you please assign one to me?

**Comment by alexanderchosen** [comment]
Hello @jywarren I am Alexander, an outreachy applicant.  Please I am yet to be assigned an issue to work on. Please help. Thanks

**Comment by 7malikk** [comment]
@TildaDares hello, I'm an Outreachy applican, can I work on this as it has been reopened?

**Comment by TildaDares** [comment]
Hi @7malikk, all of the issues here have been reserved. I've added your name to the list of first-timers so as soon as one is available, I'll let you know. Thank you!

**Comment by Teslimsama** [comment]
@TildaDares I would like to be give a task

**Comment by victory-lydia** [comment]
Hello, @TildaDares please for an FTO.

**Comment by Teslimsama** [comment]
Please can I be assigned this task @Tilda

bolaji Teslim

**Comment by TildaDares** [comment]
Hi @ifeawoyemi, @sahilbansal17, @albinazs, @oluwatunbi, @kabuur, @TaladeogoA, do you need any help with your assignments? Please feel free to reach out if you do. Thanks!

**Comment by Tishly** [comment]
Hello @TildaDares. Please, I'd like to get assigned this issue to work on for my first contribution. Thank you.

**Comment by TildaDares** [comment]
Hi @AM-png, @Mootconn, @mimi-tech, @Achele, there are issues reserved for you here. Look at the list for the files reserved for you.

**Comment by AM-png** [comment]
Thanks, I'll do it.

**Comment by Mootconn** [comment]
Ill claim this task please @TildaDares

**Comment by onireke** [comment]
Hi @TildaDares please  I am yet to be assigned a FTO  the only I saw was that my comment was deleted. Kindly assist me. Thank you

**Comment by RoleyJes** [comment]
Hi @TildaDares please can I be assigned an issue? I'm an Outreachy applicant

**Comment by RoleyJes** [comment]
Thank you!

**Comment by TildaDares** [comment]
Hi @victorvictoria-maker, please look for the issue reserved for you in the issue description above. Thank you!

**Comment by TildaDares** [comment]
Hi, @yukiyuli, please look for the issue reserved for you in the issue description above. Thank you!
