### ISSUE TITLE
Option to suppress Toolbar

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#111]
Some downstream uses (as described in #105) don't need or want a toolbar, so we should make it suppress-able with a constructor parameter, like:

```js
      img = new L.DistortableImageOverlay(
        'example.jpg', {
          suppressToolbar: true, // <= here we suppress it
          corners: [
            new L.latLng(51.52,-0.10),
            new L.latLng(51.52,-0.14),
            new L.latLng(51.50,-0.10),
            new L.latLng(51.50,-0.14)
          ]
        }
      ).addTo(map);
```

This way, we can suppress the whole `var EditOverlayAction = LeafletToolbar.ToolbarAction.extend({` section based on this constructor parameter, within the toolbar source file here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.Edit.js#L243

Here's an example of using a constructor parameter: 

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.Edit.js#L21

So we can do a conditional like:

```js
if (this._overlay.options.suppressToolbar !== false) {
  ...
}
```

And/or on this line where we instantiate the toolbar where we can also put a conditional: 

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.Edit.js#L243 

This should get us one step closer to @ChrisLowe-Takor being able to directly include this library in https://github.com/ChrisLowe-Takor/react-leaflet-distortable-imageoverlay/ and share code more easily!

**Comment by jywarren** [comment]
@gauravano @rexagod @sashadev-sky @IgorWilbert this is actually the next step towards making this more compatible with the React-based wrapper in #105. I think more broadly we should consider how to make the tools more UI independent, and offer more README guidance for that, both because all the new things we want to do (ordering, maybe ImageSequencer work) will start to outgrow the popup-style menu. 

We could show examples of how to bind buttons to different tools, for example. What do you think?

**Comment by jywarren** [comment]
An alternative to the above syntax might be:

`toolbar: false`

or we could even pass in the toolbar as a parameter, like:

```
var altToolbar = new SomeOtherToolbarUI();

img = new L.DistortableImageOverlay(
        'example.jpg', {
          tools: altToolbar,
          corners: [
            new L.latLng(51.52,-0.10),
            new L.latLng(51.52,-0.14),
            new L.latLng(51.50,-0.10),
            new L.latLng(51.50,-0.14)
          ]
        }
).addTo(map);
```

...with the current toolbar as the default if it's not set. 

ideas welcome here, although probably being able to just turn off the toolbar is a good initial step.

**Comment by sashadev-sky** [comment]
Hi, I am writing up a proposal for this right now @jywarren

**Comment by jywarren** [comment]
awesome!

**Comment by jywarren** [comment]
Moved the remaining portions of the abstraction changes to #140
