### ISSUE TITLE
change `var` to `let`/`const`

### ISSUE THREAD

**Issue by Tammy-Ajoko** [publiclab/Leaflet.DistortableImage#1127]
L.ImageUtil = {

  getCmPerPixel(overlay) {
    var map = overlay._map;

    var dist = map
        .latLngToLayerPoint(overlay.getCorner(0))
        .distanceTo(map.latLngToLayerPoint(overlay.getCorner(1)));

    return (dist * 100) / overlay.getElement().width;
  },
};
@TildaDares @jywarren

**Comment by TildaDares** [comment]
Hi @Tammy-Ajoko, thank you for opening this issue. I believe all of the files that need to updated have been reserved for in #1086. Can you double-check to make sure that the file in this issue hasn't already been worked on or assigned in #1086? Thank you!

**Comment by olamideazeez** [comment]
Hello @TildaDares can i work on this?

**Comment by TildaDares** [comment]
Closing this as it’s a duplicate of #1086
