### ISSUE TITLE
Replace Var with const and let

### ISSUE THREAD

**Issue by meggiddy** [publiclab/Leaflet.DistortableImage#1129]
https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/toolbars/DistortableImage.PopupBar.js

@TildaDares @PeculiarE  Kindly check the above potential FTO issue.

**Comment by TildaDares** [comment]
Hi @meggiddy, thank you for opening this issue. I believe all of the files that need to updated have been reserved for in https://github.com/publiclab/Leaflet.DistortableImage/issues/1086. Can you double-check to make sure that the file in this issue hasn't already been worked on or assigned in https://github.com/publiclab/Leaflet.DistortableImage/issues/1086? Thank you!

**Comment by victorvictoria-maker** [comment]
@TildaDares 
Can I work on this issue please?

**Comment by TildaDares** [comment]
Duplicate of #1086
