### ISSUE TITLE
:rainbow: Welcome Outreachy Winter 2022 Aspirants :tada: :woman_technologist: :raising_hand: :man_technologist:

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/Leaflet.DistortableImage#1131]
(_kindly read fully before asking a question :pray: _)
# :tada: Welcome Outreachy applicants Winter 2022 :tada:
Hi! :wave: and welcome to PublicLab :balloon: We are glad to have you here :heart: . This is a discussion issue for all of you with the mentors and community members. Please say hello in a comment below if you haven't done that in the chat yet , so we get to know you. Ask any questions that you might have here and we will try to answer them as soon as possible. We would also appreciate if we could help each other e.g feel free to answer a question that another applicant asks that was answered elsewhere. Thanks 

We have 1 project this round:

[Improve MapKnitter Lite for mapmaking with aerial photos as a lightweight web service](https://www.outreachy.org/outreachy-december-2022-internship-round/communities/public-lab/#improve-mapknitter-lite-for-mapmaking-with-aerial-)

We have started a discussion of the project [here](https://github.com/publiclab/Leaflet.DistortableImage/issues/1130) please feel free to ask any questions about the project there.

## First Step
Please say hi and introduce yourself. Kindly checkout [our code of conduct](https://publiclab.org/conduct). Our coding landing page is [here](https://code.publiclab.org/) and our [chat channel](https://app.element.io/#/room/#publiclab:matrix.org) 
## First Contribution :computer:
 > So we are going to hold off on making more first-timers-only issues for the time being, because we want to do as good a job as we can supporting those who have begun working on them. I know this is disappointing but we don't want a situation where folks are frustrated and unsupported in their first experience with our community, and we have to make do with what we can manage this year.
> We are so grateful for all your contributions and interest. As folks complete first-timers-only issues, we would love it if they would consider trying to make new ones for other people, and reaching out to us mentors to get them labelled. Or to help one another make it through the steps to make your first contributions -- that helps us to welcome more people effectively, and mutual support is a big thing we look to when selecting folks for the internship
> If you see an issue especially an `first-timer-only` issue that has a comment “Reserved for someone”, please don’t open a PR for it. You can express interest to work on it or offer to help out the applicant working on it. 

_Originally posted by @jywarren  and @TildaDares on chat
If we do create any first-timer issues we will update here. Thanks all.

## Second issue
After you solve the first issue you can browse through our "help-wanted" or "bug" issues and leave a comment on any you would like to work on. Feel free to ask if you need more context for you to solve an issue. 

## Call for Proposals :page_with_curl:
We request applicants to post their proposals on the PublicLab website too. In the past we have tried to read all the applicants proposals and give feedback before applicants can post the final draft on the Outreachy website. We have a high number of applicants and it may be hard for our few mentors to go through all the proposals and provide feedback in time or at all. We do encourage applicants to write a proposal regardless : it gives the mentors a better way to understand you, your plan and for you to better articulate the project but its not mandatory.

[Here is the call for proposals](https://publiclab.org/notes/cess/10-24-2022/call-for-proposals-outreachy-winter-2022-round) 
[See Summer proposals here](https://publiclab.org/notes/cess/04-04-2022/call-for-proposals-outreachy-summer-2022) 

### Deadline :stopwatch: 
Fri Nov 4 at 4pm UTC is the deadline for applicants to record contributions and create a final application on the Outreachy website

### Helpful Links
- https://github.com/publiclab/Leaflet.DistortableImage/issues/1130
- [Gitpod install guide](https://github.com/publiclab/plots2/issues/11467) thanks @AndroGenius-codes :heart:  
- [How to work with Git and Github](https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-mprove-public-lab-software)
- [Developers guides](https://publiclab.org/wiki/developers)

### A few tips for making awesome proposals:
- Your information so that we can know you better (not mandatory !).
- Include weekly timeline: Explain what you will be doing in which week. Divide the period into months in bigger tasks. Then into weeks into smaller tasks.
- Include demos/images/gifs to demonstrate your idea.
- Include Mock-Ups, Flow Charts, Data Flow Diagrams, etc to explain the workflow in simple language. So its easy for people to understand.
PRs merged & Issues reported: 
- Please mention any issues reported, PR merged, suggestions etc in the proposal.
- Start early and make revisions of the proposal to enrich it.

###  Questions :thinking:
If you have any questions please leave a comment below and we will get back to you.

Welcome again :tada: :tada: :tada:

**Comment by victory-lydia** [comment]
@cesswairimu  I am not really understanding what the issue is all about pls can you break it down for me

**Comment by victory-lydia** [comment]
Will like to work on this.

**Comment by Emenyi95** [comment]
Hello, my name is Emenyi Nelly from the South West region of Cameroon. I am an aspiring mobile app developer and Python developer. I am an intern for the current Outreachy session. Please I will like an issue to be assigned to me.Thank you

**Comment by oryxwhite** [comment]
Hello, my name is Marina. I'm an Outreachy applicant and would love to take on an issue if one becomes available

**Comment by alexanderchosen** [comment]
Hello everyone. I am Alexander, an Outreachy applicant from Nigeria. I am so glad to be here and my aim is to contribute to this project and help others too. Thanks

**Comment by alexanderchosen** [comment]
@TildaDares please I am yet to be assigned to a FTO. Can I also work on this?
Thanks

**Comment by leumasxxx** [comment]
@TildaDares how do I help create FTO,s for other first timers

**Comment by JeffyDave** [comment]
@TildaDares please I am awaiting an FTO, can I work on this?

**Comment by victory-lydia** [comment]
Please I want to do this

**Comment by Teslimsama** [comment]
@cesswairimu  hi I am an outreachy applicant I would you to assign me to a task

**Comment by IvyJeptoo** [comment]
Hi, my name is Ivy an outreachy applicant looking to contributing to this project and also being assigned an FTO.

**Comment by Marvisjaja** [comment]
Hi my name is Marvis macjaja. I am a front end Nd backend developer. An outreachy applicant . I would really appreciate if a task is assigned to me so I can make a contribution 🙏

**Comment by leilayesufu** [comment]
Hello everyone. My name is Leila, an Outreachy applicant and a frontend developer from Lagos, Nigeria. I  am so glad to be here and my aim is to contribute to the growth of this project and to help others in any way I can.

**Comment by Ibom99** [comment]
Hey everyone! I’m Esther and I am so excited to do more and contribute to this amazing community! Can’t wait to get my hands on so much more!

**Comment by cesswairimu** [comment]
@leumasxxx you could use the  " First Timers Only issue" template from [here](https://github.com/publiclab/Leaflet.DistortableImage/issues/new/choose), thanks!

**Comment by leumasxxx** [comment]
> 

thank you @cesswairimu i'd look into them now

**Comment by cesswairimu** [comment]
hi :wave: and welcome again
sorrry @victory-lydia I missed your prev question -  this is a discussion issue for Outreachy applicants--more of a conversation thread on an issue, makes sense? 
Just clarifying this is not a issue one can work on, I saw a few people asking to work on it.
I've assigned a few issues to the people who didn't have one, you should have seen a notification:  if not just ping me if your name is checked on the FTO list and you cannot trace the issue.
Thanks everyone for your patience

**Comment by Tishly** [comment]
Hi @cesswairimu I just joined the community chat on element.io and would like to request an FTO assignment. Thank you.

**Comment by Tobbiloba** [comment]
please i just cloned the github repository
how do i run it??

**Comment by cesswairimu** [comment]
Anyone looking for a second issue and has plots2 installed - this could be a good one to try out https://github.com/publiclab/plots2/issues/11528

**Comment by Emenyi95** [comment]
Thank you @cesswairimu let me get my hands on this

**Comment by IvyJeptoo** [comment]
i'd like to claim another issue if available @cesswairimu

**Comment by cesswairimu** [comment]
Happy new week all, we have opened the call for proposals [here](https://publiclab.org/notes/cess/10-24-2022/call-for-proposals-outreachy-winter-2022-round)

**Comment by leumasxxx** [comment]
> 

happy new week @cesswairimu  and thank you for opening the call for proposal

**Comment by sainamercy** [comment]
Hi @cesswairimu. some internship tasks have already been worked on. Do we still include them in our proposal

**Comment by cesswairimu** [comment]
Hi @sainamercy, you can skip those or if you have any ideas on improving the already completed tasks you can include that too.

**Comment by sainamercy** [comment]
> Hi @sainamercy, you can skip those or if you have any ideas on improving the already completed tasks you can include that too.

Thanks @cesswairimu ❤

**Comment by Ashism766** [comment]
Hi everyone, I'm Ashis, is there any way to participate anymore?

**Comment by cesswairimu** [comment]
Closing this now, Thanks all
