### ISSUE TITLE
Replace var keyword with let/const

### ISSUE THREAD

**Issue by Jennifer-tech** [publiclab/Leaflet.DistortableImage#1132]
I did like an update on this project to use let/const instead of var.

## General rules

Use `let` when you know that the value of a variable will change.
Use `const` for every other variable.

<img width="916" alt="Leaflet DistortableImage issue" src="https://user-images.githubusercontent.com/85136425/195385333-1b11bce7-c06e-4a2e-9f43-532072fb24ab.png">

**Comment by fonkwe** [comment]
@Jennifer-tech   @jywarren   @TildaDares   Can I work on it or allow it for First Timers??

**Comment by Jennifer-tech** [comment]
@TildaDares @jywarren @cesswairimu @PeculiarE Please review this issue I raised for FTOs

**Comment by TildaDares** [comment]
Hi @Jennifer-tech, thank you for opening this issue. I believe all of the files that need to updated have been reserved for in https://github.com/publiclab/Leaflet.DistortableImage/issues/1086. Can you double-check to make sure that the file in this issue hasn't already been worked on or assigned in https://github.com/publiclab/Leaflet.DistortableImage/issues/1086? Thank you!

**Comment by Jennifer-tech** [comment]
Hi @TildaDares, I checked that now and found that it has been updated. I also found out that some files in the util Folder need to be updated. Do I need to open an issue on that

**Comment by TildaDares** [comment]
@Jennifer-tech The files in the util folder have also been reserved in #1086. I think we can close this issue so we don’t have clashes with #1086.

Thank you for opening this!!
