### ISSUE TITLE
Replace `var` keyword with `let/const`

### ISSUE THREAD

**Issue by Ibom99** [publiclab/Leaflet.DistortableImage#1135]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [listeners.html](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/listeners.html) in the `Leaflet.DistortableImage` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-26  var map;
+26 let map;

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Ibom99** [comment]
Hi, @TildaDares came up with issue to help out with first-timers.

**Comment by TildaDares** [comment]
Hi @Ibom99, the file link is wrong. Please add the correct link. Thanks!

**Comment by Ibom99** [comment]
@TildaDares I am having issues with linking the file, I'll kindly need your help. Its in the listeners.html file in the examples folder

**Comment by Ibom99** [comment]
@TildaDares I have corrected the link!

**Comment by TildaDares** [comment]
Amazing @Ibom99. Thank you!!

**Comment by TildaDares** [comment]
Reserved for @Bhaybhiisparks for 24 hours!

**Comment by TildaDares** [comment]
@Ibom99 Do you mind informing @Bhaybhiisparks that there’s an issue reserved for them in https://github.com/publiclab/plots2/issues/11105?

Thank you!

**Comment by Bhaybhiisparks** [comment]
Okay. Thanks. I'll work on it

**Comment by Ibom99** [comment]
@TildaDares Thank you so much!! She has claimed it! :)

**Comment by alexanderchosen** [comment]
Good day. Please can i also work on this FTO @TildaDares @Ibom99

**Comment by 7malikk** [comment]
@alexanderchosen Hello, I think @TildaDares is following a particular order based on the list of contributors in [here](https://github.com/publiclab/plots2/issues/11105), if you haven't requested for an issue. I suggested you do. Cheers🎊

**Comment by alexanderchosen** [comment]
@7malikk Thanks a lot for your kind suggestion. I have already requested for an issue and hopefully, I will get some issues to work on soon from @TildaDares 
Thanks

**Comment by RoleyJes** [comment]
Hi, is this issue still available?

**Comment by Jolzyfx** [comment]
@TildaDares 
Can I still work on this issue
