### ISSUE TITLE
Add Fontawesome CSS to our Archive demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1136]
We'd like to start using icons at https://publiclab.github.io/Leaflet.DistortableImage/examples/archive 

Let's add an include for FontAwesome v4 icons to the head!

https://fontawesome.com/v4/get-started/

I'd love if someone who recently completed a first-timers-only issue could take this up!

**Comment by RealRichi3** [comment]
I would like to take this issue

**Comment by jywarren** [comment]
please go ahead!

**Comment by liliyao2022** [comment]
I'd like to take care of this task, thanks!
