### ISSUE TITLE
 Create a new header in the Readme linking to Mapknitter Lite

### ISSUE THREAD

**Issue by 7malikk** [publiclab/Leaflet.DistortableImage#1146]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and look through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [README.md](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/README.md) in the `Leaflet.DistortableImage` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
+ 36  ### MapKnitter Lite 
+ 37
+ 38 Check out an early prototype of the Mapknitter Lite project [here](https://publiclab.github.io/Leaflet.DistortableImage/examples/archive)
+ 39 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by 7malikk** [comment]
Hello, @jywarren, @TildaDares here is an issue to help out with first-timers.

**Comment by liliyao2022** [comment]
Hi, I'd like to take this issue, thanks!

**Comment by TildaDares** [comment]
Hi @7malikk, thank you for opening this issue. I think the initial link should be left as is because it is meant to serve as an example for users. Maybe we create another header with the title `Mapknitter Lite` that contains the link to the new link.

What do you think?

**Comment by 7malikk** [comment]
> Hi @7malikk, thank you for opening this issue. I think the initial link should be left as is because it is meant to serve as an example for users. Maybe we create another header with the title `Mapknitter Lite` that contains the link to the new link.
> 
> 
> 
> What do you think?

That sounds a lot better, I'll make the changes and ping you. Thank you for the feedback.

**Comment by 7malikk** [comment]
@TildaDares Hello again, I've made the changes concerning creating a header new header and not replacing and refactoring. Kindly review and let me know your thoughts. Thank you.

**Comment by Teslimsama** [comment]
Please can I join you guy

**Comment by 7malikk** [comment]
@Teslimsama I believe @TildaDares is following a particular order from [11105](https://github.com/publiclab/plots2/issues/11105), if you have made a request for an FTO, kindly exercise patience you would be assigned to an issue.

In the meantime @TildaDares could you review and attach a label [here](https://github.com/publiclab/Leaflet.DistortableImage/issues/1146), Thank you

**Comment by Teslimsama** [comment]
Thanks

**Comment by TildaDares** [comment]
This looks great @7malikk!

Can you also specify what line in the file the change should be added? This will make it easier for contributors to work on it. Thank you and great work!

**Comment by 7malikk** [comment]
> This looks great @7malikk!
> 
> 
> 
> Can you also specify what line in the file the change should be added? This will make it easier for contributors to work on it. Thank you and great work!

Alright @TildaDares 
Will do that now and ping you.
Thank you for the feedback.

**Comment by 7malikk** [comment]
Hello, @TildaDares Kindly check out the update specifying the line to be changed. Thank you

**Comment by Onyi-X** [comment]
Hi @7malikk and @TildaDares I found this reply beneath my request for an FTO, but going through the chats it seems it should be left as is.. I'd appreciate more clarity on it. 

Thanks

**Comment by TildaDares** [comment]
Hi @liliyao2022, please go ahead. Thank you!

**Comment by TildaDares** [comment]
Great work @7malikk. Thank you!

**Comment by jywarren** [comment]
This looks great, thanks folks!!!

**Comment by Onyi-X** [comment]
@TildaDares @jywarren I'll like to try this issue

**Comment by Onyi-X** [comment]
@7malikk the issue seems to be on line 36 - 49, please confirm this while i work on it, thanks

**Comment by 7malikk** [comment]
> @7malikk the issue seems to be on line 36 - 49, please confirm this while i work on it, thanks

Thank you @Onyi-X, I've made the corrections, you should insert the code in at line 36.

**Comment by 7malikk** [comment]
@TildaDares Hello there, this issue hasn't been resolved and many haven't had a chance to resolve an issue.

**Comment by TildaDares** [comment]
Thanks for the reminder @7malikk. I'll reassign it.

**Comment by TildaDares** [comment]
Reserved for @tolubishops0 for 24 hours!

**Comment by tolubishops0** [comment]
I've been assigned to this issue. Working on it
