### ISSUE TITLE
Change 'var' to ES6 'let' keyword in files under the folder 'examples'

### ISSUE THREAD

**Issue by segun-codes** [publiclab/Leaflet.DistortableImage#1151]
@TildaDares the underlisted files still use 'var' keyword and not the ES6 'let' keyword. There's a need to update the files to use the ES6 keyword.  

/examples/export.html 
/examples/index.html 
/examples/listeners.html
/examples/select.html

**Comment by segun-codes** [comment]
@TildaDares, I'd like to claim this issue.

**Comment by TildaDares** [comment]
Hi @segun-codes, thank you for opening this issue. The listeners.html file has already been addressed in #1135. You can refactor the rest files.

Also, since you’ll be working on the issue, there’s no need to add the first-timers-only label. Thank you!

**Comment by segun-codes** [comment]
Okay.. thank you.

**Comment by segun-codes** [comment]
Hi @TildaDares, I created a PR #1152 could you kindly review. Many thanks.
