### ISSUE TITLE
Display url where images came from, in MapKnitter Lite interface 

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1153]
When using MapKnitter Lite at https://publiclab.github.io/Leaflet.DistortableImage/examples/archive, when images begin to load, we could show a sentence about where they were loaded from (just displaying the URL which was input in the previous step):

![Screenshot_20221014-081354](https://user-images.githubusercontent.com/24359/195727438-6955f463-e65f-4cfb-95e2-8f23242eea2e.png)

We could insert a line outside this block, or possibly before it:

https://github.com/publiclab/Leaflet.DistortableImage/blob/6e426d8370db8a24725f00cc5952e7533dbdf135/examples/archive.html#L116-L123

`input.value` is the URL that was input. We can create a `<p>` tag and say "images fetched from LINK" where LINK is the URL. Even better, it could be a link itself!

Would someone who's done a first timers only issue already like to take this up?

**Comment by 7malikk** [comment]
@jywarren i'd like to claim this issue

**Comment by jywarren** [comment]
Ok @7malikk how would you approach this? Thank you!

**Comment by 7malikk** [comment]
@jywarren I would create an `<p>`  tag with the text like you stated 'Images fetched from here'  where "here" would be wrapped in an `<a>` tag with  `href=input.value` before the code block.

What do you think?

**Comment by jywarren** [comment]
Sounds good, would you like to open a PR?

**Comment by 7malikk** [comment]
> Sounds good, would you like to open a PR?

Yes, I would, I'll get on it right away

**Comment by THEDARKMAN007** [comment]
id like to try this

**Comment by jywarren** [comment]
Maybe you could even just modify line 120?

**Comment by THEDARKMAN007** [comment]
@jywarren thank you, ill work on it

**Comment by jywarren** [comment]
Hi @THEDARKMAN007 it looks like @7malikk has already begun here. Maybe you could look over the PR and offer any suggestions, or we can try finding another task for you soon?

**Comment by Tammy-Ajoko** [comment]
@jywarren I would like to go over the PR or if there is another task i would like to do that

**Comment by 7malikk** [comment]
@jywarren We can close this issue as we already resolved it in #1154

**Comment by TildaDares** [comment]
Resolved in #1154. Thanks all!
