### ISSUE TITLE
Change 'var' to ES6 'let'/'const' keyword in files and folders under the folder 'edit' located in the 'src' folder

### ISSUE THREAD

**Issue by 7malikk** [publiclab/Leaflet.DistortableImage#1155]
Hello @TildaDares, @jywarren, @cesswairimu the following files still use the 'var' keyword and not the ES6 'let'/'const' keyword. These files need to be updated to make use of the ES6 keywords.

-  [src/edit/handles/LockHandle.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/409dc4120c26ead568f4b14e23401ff82e178f09/src/edit/handles/LockHandle.js)
- [src/edit/getEXIFdata.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/edit/getEXIFdata.js)
- [src/edit/actions/EditAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/986edeb4fe23543bbf7fa3bdc729c332e3b6fa50/src/edit/actions/EditAction.js)
- [src/edit/toolbars/DistortableImage.PopupBar.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/edit/toolbars/DistortableImage.PopupBar.js)
- [src/edit/actions/UnlockAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/edit/actions/UnlockAction.js)
- [src/edit/actions/DistortAction.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/24d0eb1bb72ede462289c28d608180dad60cbbc8/src/edit/actions/DistortAction.js)
- [src/edit/toolbars/DistortableImage.ControlBar.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/00ceec2d7332e39cac1abf0e7ff25ffd11b3e063/src/edit/toolbars/DistortableImage.ControlBar.js)

**Comment by sainamercy** [comment]
@7malikk all those files have already been reserved for other applicants

**Comment by TildaDares** [comment]
Hi @7malikk, as mentioned by @sainamercy, all of those files have been listed and assigned in #1086. Thank you!

**Comment by 7malikk** [comment]
@sainamercy @TildaDares 
Oh alright, I didn't notice, thanks for the feedback
