### ISSUE TITLE
[BUG] - MIME type error while hosting `archive.html` on local PC

### ISSUE THREAD

**Issue by RealRichi3** [publiclab/Leaflet.DistortableImage#1156]
**Describe the bug:**
I tried to host the HTML page on my PC but the rendered page only shows an empty map.
![image](https://user-images.githubusercontent.com/76791916/195753547-34495cb8-28df-4b1f-9624-171dc685d7a7.png)

I checked the console and it showed these errors
```
Refused to apply style from 'http://127.0.0.1:5500/dist/vendor.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
vendor.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
archive.html:1 Refused to execute script from 'http://127.0.0.1:5500/dist/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
leaflet.distortableimage.js:1508 Uncaught TypeError: Cannot read properties of undefined (reading 'Action')
    at 280 (leaflet.distortableimage.js:1508:36)
    at leaflet.distortableimage.js:2859:11
    at leaflet.distortableimage.js:2883:3
archive.html:93 Live reload enabled.
archive.html:119 Uncaught TypeError: map.addGoogleMutant is not a function
    at setupMap (archive.html:119:11)
    at archive.html:130:5
:5500/favicon.ico:1          Failed to load resource: the server responded with a status of 404 (Not Found)
archive.html:1 Refused to apply style from 'http://127.0.0.1:5500/dist/vendor.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

What happened vs. what did you expect to happen?
It didn't render the page completely and i expected it to load the map and show a prompt for me to add the archive links for the image

**Reproduce the behavior:**
 Steps to reproduce the behavior. (ex. 1. Go to... 2. Click on... 3. See error...)
- Open repository in VS code
- Open `/example/archive.html`
- Host it on a live server
- Observe the rendered page

**Browser, version, and operating system:**
 - Browser [e.g. chrome, safari] - Brave
 - Version [e.g. 22] - 1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit)
 - Platform: [e.g. iOS, windows] -  Windows 11

**Comment by sainamercy** [comment]
@RealRichi3 I also get the exact same error

**Comment by sainamercy** [comment]
@RealRichi3 try `npm run build`  it should work

**Comment by segun-codes** [comment]
@sainamercy's comment is correct, @RealRichi3 you want to give it a shot.

**Comment by RealRichi3** [comment]
Alright thanks, I'll try it

**Comment by RealRichi3** [comment]
thanks @segun-codes i just tried it and it worked perfectly
