### ISSUE TITLE
Transfer js code in index.html into separate .js file

### ISSUE THREAD

**Issue by segun-codes** [publiclab/Leaflet.DistortableImage#1181]
index.html file currently contains Javascript code, this makes for a less readable and maintainable code especially as the codebase is set to become larger with more contributions from the community members. For this reason, it is important to transfer and maintain javascript code in a separate .js file different from the ./examples/index.html file as much as possible.

**Comment by segun-codes** [comment]
Hi @TildaDares @jywarren  do you want to assign this issue? Not sure if it's qualifies as FTO or not.

If it does not qualifies as FTO, I'd like to claim this issue if okay by you.

**Comment by jywarren** [comment]
Hello, I wonder if maybe doing this for 1 file first would make a good
example to follow, and then we could create FTOs for others based on that
example? So perhaps if one of you would like to try the first one?

**Comment by segun-codes** [comment]
@jywarren, okay I'll try it. Thank you.

**Comment by 7malikk** [comment]
@jywarren That sounds great
@segun-codes We could leave it to @AndroGenius-codes as he just requested to work on  the archive page
You and i can work on converting the rest to FTOs, what do you say?

**Comment by segun-codes** [comment]
> @jywarren That sounds great @segun-codes We could leave it to @AndroGenius-codes as he just requested to work on the archive page You and i can work on converting the rest to FTOs, what do you say?

@7malikk, okay... but not sure how we can achieve that. You can throw more light on this though. I thought @jywarren's idea is the way to go. One example, and then other first-timers can follow the example, something like that.

**Comment by 7malikk** [comment]
@segun-codes So what I'm trying to say is @AndroGenius-codes should make the correction (i.e moving the js to an external js file) 
Then you and I will create FTOs for the other issues. using @AndroGenius-codes implementation as an example.

**Comment by 7malikk** [comment]
> > @segun-codes So what I'm trying to say is @AndroGenius-codes should make the correction (i.e moving the js to an external js file) Then you and I will create FTOs for the other issues. using @AndroGenius-codes implementation as an example.
> 
> > 
> 
> > Does this clarify things?
> 
> 
> 
> @7malikk, not to complicate things, let's just go by @jywarren's suggestion re-affirmed by @TildaDares. So I will simply fix this issue. The first-timers can re-apply from my input if @jywarren find it okay of course.

@segun-codes check your dm for the meet link

**Comment by Ibom99** [comment]
@jywarren can i try out https://github.com/publiclab/Leaflet.DistortableImage/issues/1184 as an example?

**Comment by 7malikk** [comment]
@Ibom99 Hey there, @segun-codes already created a PR at #1186 regarding this.
And is awaiting a review. What you should do is take a look at the above-mentioned PR and create an FTO from the changes made by @segun-codes. 

It will provide issues for others to resolve.
Just a thought, open to revision @jywarren @TildaDares @cesswairimu
