### ISSUE TITLE
Replacing the (') with a (`) in strings in archive.html

### ISSUE THREAD

**Issue by Chinazaekpere-Ike** [publiclab/Leaflet.DistortableImage#1188]
### 💡Format this Issue Into a First Timers Issue

This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labeled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

---

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [archive.html](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/archive.html) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- 112   fetchedFromUrl.innerHTML = 'this Internet Archive Collection';
+ 112   fetchedFromUrl.innerHTML = `this Internet Archive Collection`;
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Chinazaekpere-Ike** [comment]
Hi❗
@TildaDares @jywarren 

I created this FTO for those who are still looking for an issue to solve.
I hope to see it being assigned to someone 🙂

**Comment by Chinazaekpere-Ike** [comment]
> Hello! Thank you -- is there a reason you think the ` character would be better? I'm not that familiar with it in this context. Thank you!

Hi @jywarren 

This ` is called a Back tick and it basically makes modifying code easier for future purposes

Example,
Rather than having this (In Js)

`1     let action = 'dance' `
`2     alert ('I want to ' + action + ' all day')`

We can write -->

`1     let action = 'dance'`
`2     alert(`I want to ${action} all day`)`

The second is more efficient because it's easier to maintain. Supposing we want to add a whole lot more variables/text to the alert, they'll be no need to worry about the overwhelming amount of pluses and quotation marks that would need to be added as well

**Comment by Oluwaseun241** [comment]
Can i claim the issue?

**Comment by sainamercy** [comment]
Hi @Chinazaekpere-Ike @jywarren. I think this could be best implemented where such an occurrence 
`1 let action = 'dance' `
`2 alert ('I want to ' + action + ' all day')`
actually occurs.

**Comment by Chinazaekpere-Ike** [comment]
> Hi @Chinazaekpere-Ike @jywarren. I think this could be best implemented where such an occurrence `1 let action = 'dance' ` `2 alert ('I want to ' + action + ' all day')` actually occurs.
> 
> because this is an implication that all strings use backticks, which isn't necessary according to my opinion

Hey @sainamercy
I completely understand your point but I proposed this issue to make future maintenance easier 

@jywarren What's your input on this?

**Comment by Chinazaekpere-Ike** [comment]
> Can I claim the issue?

Hey @Oluwaseun241 
We're still awaiting @jywarren approval on this

**Comment by Oluwaseun241** [comment]
> > Can I claim the issue?
> 
> Hey @Oluwaseun241 We're still awaiting @jywarren approval on this

I already made a pull request

**Comment by TildaDares** [comment]
Hi @Chinazaekpere-Ike, this is a very good suggestion but this case doesn’t really need backticks since we aren’t making use of string interpolation. Thanks!

**Comment by Chinazaekpere-Ike** [comment]
Okay @TildaDares You make a valid point. 

Closing this issue now.

**Comment by TildaDares** [comment]
Hi @Chinazaekpere-Ike, there's an issue reserved for you in #11501
