### ISSUE TITLE
Missing of the closing </body> 

### ISSUE THREAD

**Issue by liliyao2022** [publiclab/Leaflet.DistortableImage#1200]
**Describe the bug:**
There is a missing of the closing tag</body> 

**Reproduce the behavior:**
  1. Go to https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/listeners.html
  2.   See the missing error

**Browser, version, and operating system:**
 - Browser Chrome 
 
 - Platform: iOS -

**Comment by victory-lydia** [comment]
Please can I work on this??

**Comment by liliyao2022** [comment]
> Please can I work on this??
Yes, It would be great.

**Comment by victory-lydia** [comment]
I think some one did a pull request  all ready

**Comment by victory-lydia** [comment]
@TildaDares So what do we do

**Comment by TildaDares** [comment]
Hi @victory-lydia, @segun-codes created an FTO to include the closing body tag in the html files here #1218. You can look through the issue to make sure that all of the html file were included. Thank you!
