### ISSUE TITLE
Update /examples/js/index.js with missing code

### ISSUE THREAD

**Issue by segun-codes** [publiclab/Leaflet.DistortableImage#1212]
The code `L.Control.geocoder().addTo(map);` was inadvertently left out when js code in `/examples/index.html` was transferred to `/examples/js/index.js` .  There's a need to transfer code in line 42 in the snapshot below to index.js.

![A](https://user-images.githubusercontent.com/1612359/197277934-a8609762-e088-46db-a6b8-c35f52db8719.PNG)

**Comment by Oluwaseun241** [comment]
can i claim the issue??

**Comment by segun-codes** [comment]
H @Oluwaseun241, sorry this issue is peculiar and it has a PR already.
