### ISSUE TITLE
LeafletToolbar is not defined     at leaflet.distortableimage.js:549

### ISSUE THREAD

**Issue by nhannguyen051195** [publiclab/Leaflet.DistortableImage#123]
I am trying to use Leaftlet.Distortable image plugin but I still have problem maybe with the dependency. The way I am doing is to copy to file in dist folder without changing anything, including leaflet.distortableimage.css and leaflet.distortableimage.js, then I add them to my `index.html `file. 

<html>

<head>
  <meta charset=utf-8 />
  <title>Draggable marker</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
    crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js" integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
    crossorigin=""></script>
  <script src="./node_modules/leaflet-toolbar/dist/leaflet.toolbar.js"></script>
  <link rel="stylesheet" href="node_modules/leaflet-toolbar/dist/leaflet.toolbar.css" />
  <link href="./node_modules/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link rel="stylesheet" href="./Plugins/leaflet.distortableimage.css" type="text/css" media="screen" title="no title"
    charset="utf-8">
  <script src="./Plugins/leaflet.distortableimage.js"></script>
  <style>
    body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>

<body style="margin:0;">
  <form id="test_form">
    <input type="file" id="inputimage" accept="image/*">
  </form>
  <div id="map" style="width:100%; height:100%; position:absolute; top:0;"></div>
  <script>

    var map

    (function () {

      // basic Leaflet map setup
      map = new L.map('map').setView([51.505, -0.09], 13);
      L.tileLayer('https://{s}.tiles.mapbox.com/v3/anishshah101.ipm9j6em/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
          '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
          'Imagery © <a href="http://mapbox.com">Mapbox</a>',
        id: 'examples.map-i86knfo3'
      }).addTo(map);

      // create an image
      img = new L.DistortableImageOverlay(
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDA4Jhlt2TGWKs8hSYa4yLTv26x7UqLoVtCbcbh1KNxPjbuo8Ibw', {
          corners: [
            new L.latLng(51.52, -0.10),
            new L.latLng(51.52, -0.14),
            new L.latLng(51.50, -0.10),
            new L.latLng(51.50, -0.14)
          ]
        }
      ).addTo(map);

      L.DomEvent.on(img._image, 'load', img.editing.enable, img.editing);
    })();
  </script>

</html>

**Comment by nhannguyen051195** [comment]
![image](https://user-images.githubusercontent.com/38784929/51804035-62bae400-2264-11e9-8cc4-3fc6d5ac622c.png)

**Comment by nhannguyen051195** [comment]
leaflet.distortableimage.js:549 Uncaught ReferenceError: LeafletToolbar is not defined
    at leaflet.distortableimage.js:549
(anonymous) @ leaflet.distortableimage.js:549
index.html:65 Uncaught TypeError: Cannot read property 'enable' of undefined
    at index.html:65
    at index.html:66

**Comment by rexagod** [comment]
Hey @nhannguyen051195! You need to initialize `enable` first (in the `L.DistortableImageOverlay` constructor) in order to access that on the `editing`' object. Closing this.
```js
editing: e
 dragging: e {options: {…}, _element: img.leaflet-image-layer.leaflet-zoom-animated, 
 _dragStartTarget: img.leaflet-image-layer.leaflet-zoom-animated, _preventOutline: undefined, 
 _initHooksCalled: true, …}
 _distortHandles: e {options: {…}, _layers: {…}, _initHooksCalled: true, _leaflet_id: 94, _mapToAdd: 
 e, …}
 _enabled: true
 _handles: {lock: e, distort: e, rotate: e}
 _initHooksCalled: true
 _leaflet_id: 78
 _lockHandles: e {options: {…}, _layers: {…}, _initHooksCalled: true}
 _mode: "distort"
 _outlined: false
 _overlay: e {_toolArray: Array(6), _url: "example.png", _rotation: undefined, options: {…}, 
 _initHooksCalled: true, …}
 _rotateHandles: e {options: {…}, _layers: {…}, _initHooksCalled: true}
 _transparent: false
 __proto__: e
```

**Comment by sashadev-sky** [comment]
@rexagod should we close this? Its been months

**Comment by rexagod** [comment]
Sure thing @sashadev-sky! I think we should close this! :+1:

**Comment by nielei19920921** [comment]
@rexagod I have the same problem.How to initialize enable?
Please give me an example. Thanks!
