### ISSUE TITLE
Change nameless functions to arrow functions

### ISSUE THREAD

**Issue by Achele** [publiclab/Leaflet.DistortableImage#1235]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [DistortableCollectionEditSpec.js](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/test/src/edit/DistortableCollectionEditSpec.js) in the `Leaflet.DistortableImage` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-1  describe('L.DistortableCollection.Edit', function() {
+1 describe('L.DistortableCollection.Edit', () => {

-41  L.DomEvent.on(overlay3, 'load', function() { done(); });
+41  L.DomEvent.on(overlay3, 'load', () => { done(); });

-44  afterEach(function() {
+44 afterEach(() =>  {

-50  describe('#_decollectAll', function() {
+50  describe('#_decollectAll', () => {

-61  setTimeout(function() {
+61  setTimeout(() => {

-79 setTimeout(function() {
+79 setTimeout(() => {

-109  setTimeout(function() {
+109  setTimeout(() => {

-115  describe('#_addToolbar', function() {
+115  describe('#_addToolbar', () => {

-126  it('it adds a control toolbar to the map', function() {
+126  it('it adds a control toolbar to the map', () => {

-141  describe('#_removeToolbar', function() {
+141  describe('#_removeToolbar', () => {

-142. beforeEach(function() { 
+142  beforeEach(() => { 

-149  it('is invoked on map click', function() {
+149  it('is invoked on map click', () => {

-151  setTimeout(function() {
+151  setTimeout(() =>  {

-173  describe('#_lockGroup', function() {
+173  describe('#_lockGroup', () => {

-174  beforeEach(function() {
+174  beforeEach(() => {

-188  it('does not toggle lock mode', function() {
+188  it('does not toggle lock mode', () => {

-193  it('prevents images in that group from being dragged', function() {
+193  it('prevents images in that group from being dragged', () => {

-201  describe('#_unlockGroup', function() {
+201  describe('#_unlockGroup', () => {

-202  beforeEach(function() {
+202  beforeEach(() => {

-216  it('does not toggle lock mode', function() {
+216  it('does not toggle lock mode', () => {

-223  describe('#_removeGroup', function() {
+223  describe('#_removeGroup', () => {

-224  beforeEach(function() {
+224. beforeEach(() => {

-229  it('removes a collection of layers', function() {
+229  it('removes a collection of layers', () => {
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Achele** [comment]
@TildaDares I created this FTO for first timers who are still looking for an issue to resolve. Please do check it out.

**Comment by Oluwaseun241** [comment]
can i claim this issue?

**Comment by Achele** [comment]
@Oluwaseun241 you would have to wait for @TildaDares to approve and then assign it before claiming it. Thank you

**Comment by TildaDares** [comment]
Amazing work @Achele. This looks great!!

**Comment by TildaDares** [comment]
Hi @Oluwaseun241, contributors can only work on one FTO issue. Thanks!

**Comment by TildaDares** [comment]
Reserved for @Kemmie001 for 24 hours!

**Comment by Achele** [comment]
Thank you @TildaDares

**Comment by jssol** [comment]
Hello @TildaDares, I would love to do this if @Kemmie001 is not available

**Comment by Favour-Cay** [comment]
can i try this? @TildaDares

**Comment by TildaDares** [comment]
Hi @jssol, please go ahead. Thank you!

**Comment by jssol** [comment]
Thanks @TildaDares, I am on it!

**Comment by Achele** [comment]
You are welcome @jssol🤗
