### ISSUE TITLE
Get Bounds of image

### ISSUE THREAD

**Issue by nhannguyen051195** [publiclab/Leaflet.DistortableImage#125]
After modifying images' position, I would like to get new 4 coordinates of image corners after I press lock button on toolbar. 
Is there anyway to do it? Any help would be appreciated!

**Comment by jywarren** [comment]
Would you like them in latitude and longitude, or in pixel locations? I
guess I assume the former but just to check!

**Comment by jywarren** [comment]
Hi, all, yes, you should be able to get 4 LatLng objects (which are basically latitude longitude pairs) by querying:

```js
imageOverlay._corners

// in the demo, the layer IDs are randomly assigned, but for example:
map._layers[59]._corners
```

I'll add this to the README too! Thanks!

**Comment by jywarren** [comment]
https://github.com/publiclab/Leaflet.DistortableImage/blob/main/README.md#corners
