### ISSUE TITLE
Copy "location search" feature to archive.html

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1272]
We have this great new feature for searching for locations:

https://publiclab.github.io/Leaflet.DistortableImage/examples/

<img width="419" alt="image" src="https://user-images.githubusercontent.com/24359/202232952-11ce7311-593a-4486-8909-f5c2412daecb.png">

However we want that same feature at the archive page:

https://publiclab.github.io/Leaflet.DistortableImage/examples/archive.html

It should be a pretty easy change! Here are the changes to index.html that made it possible: https://github.com/publiclab/Leaflet.DistortableImage/pull/1158/files

I'd love help with this! Maybe it could even be a first-timers-only issue?

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by rit-clone** [comment]
Hi @jywarren I would love to work on this issue. Will you please assign it to me?

**Comment by jywarren** [comment]
Sure, please go ahead. No need to be assigned formally - thank you!

**Comment by hs05june** [comment]
[https://github.com/publiclab/Leaflet.DistortableImage/pull/1286](url) Hey @jywarren . Once check my PR. I was struggling on a bug. I was unable to figure that out. Kindly suggest something.
