### ISSUE TITLE
Functionality to Restore welcomeModal to View

### ISSUE THREAD

**Issue by segun-codes** [publiclab/Leaflet.DistortableImage#1294]
There's currently no way to restore welcomeModal to view when closed by clicking the `begin` or `close button`. A user must therefore refresh/reload archive.html to restore it to view, whereas this approach is appropriate in the event of an uncontrolled error on the webpage, it is however counterintuitive in the case of the above stated use cases.

**Please describe the desired behavior.**
Implement functionality that extends the use case of the `stack button` icon already present on `archive.html` to support restoring the welcomeModal to view and focus.

**Additional context (optional)**
See screenshot below for more insight on the issue.

![Screenshot-2](https://user-images.githubusercontent.com/1612359/207566100-49421ef7-9b50-4136-97fd-68b80b02276a.png)

**Comment by segun-codes** [comment]
@jywarren, is it okay to proceed to implement a fix for this issue? 

Note, this task is consistent with task distribution @7malikk and I agreed upon and listed on trello board, many thanks!

**Comment by jywarren** [comment]
Hi, just wondering, would this restart the whole experience? I.e. remove images? or just re-show the modal? What if we made a link from the top of the images sidebar, so that in "minimized" state there's still just one button?

But yes, this sounds like a good idea!

**Comment by segun-codes** [comment]
Apologies, I didn't disclose these thoughts earlier. So my thoughts, there's need for welcomeModal when:
1. The archive.html page is newly loaded - this already works
2. User closes the welcomeModal for whatever reason without loading any image overlay to the tile and needs the welcomeModal back
3. User deletes all image overlays (for whatever reason) and needs to restore welcomeModal to continue using the service - this use case just flashed into my mind

Further thoughts:
1. The whole experience will not be restarted as the page will not be reloaded, the welcomeModal will just be made visible again.
2. Your idea of placing a link on the image sidebar is a good suggestion, we should stick to it. Thanks for this.
3. Then, I will just update the tooltip on the `stack` button to let users know they can restore the welcomeModal by following the "stack" button. I think this is quite important, we don't users left hanging and wondering how to restore the welcomeModal.
4. No new button will be introduced on the tile.

So what do you think @jywarren?

**Comment by jywarren** [comment]
this sounds good, but just to be thorough -- what if someone inputs a new
URL... i never thought of it but do we allow making maps from multiple
sources? Pros/cons?
