### ISSUE TITLE
Generate URL from JSON data

### ISSUE THREAD

**Issue by 7malikk** [publiclab/Leaflet.DistortableImage#1340]
**Please describe the desired behavior.**
onClick of a button, the current tile layer state including its already knitted images should be uploaded in JSON to Archive.org and a link should be generated and returned to the user.

**Comment by 7malikk** [comment]
Hello @jywarren, although I have not successfully found a way to write new data to IA (the way we need to), here is my opinion from the research and attempts so far.

Going through the [IA Developer Portal](https://archive.org/developers/index.html), I found various ways to communicate with IA, but I noticed that in all the various ways especially in cases of writing/updating data, the user had to parse in an `Authorization` header with values `LOW <s3-access>:<s3-secret>`, like so: 

![image](https://user-images.githubusercontent.com/75104021/214850773-8276d169-61f5-47f8-a109-b1085489f6eb.png)
this snippet can be found at [Internet Archive Tasks API](https://archive.org/developers/tasks.html?highlight=services)

After further digging, I found out that these values `s3-access` and `s3-secret` are available to each IA account. 

### My thoughts so far
I stand to be corrected, but I believe it'll be a tad impractical to require these keys from every user interested in sharing via URL.

### Resources
Here are some of the resources I went through backing my thoughts:
- [ias3 Internet archive S3-like API](https://archive.org/developers/ias3.html)
- [Internet Archive RESTful microservices](https://archive.org/developers/iarest.html#get)
- [Internet Archive Tasks API](https://archive.org/developers/tasks.html?highlight=services)
- [Internet Archive Tools and APIs](https://archive.org/developers/index-apis.html)

As I am still researching and performing some trials, I can not come to a conclusion just yet, I would also love to know what you all think. Thank you!
@jywarren @PeculiarE @TildaDares @cesswairimu @segun-codes 

### Sidenote
As discussed and noted in our shared notes, we could work on a step-by-step guide on how to upload JSON files to IA, all within a modal triggered by the share button.

**Comment by jywarren** [comment]
Hi @7malikk this is excellent research. I think it's not surprising that some kind of token or login is required. Otherwise IA could accept uploads from anyone without user login required. gist.github.com used to allow creating a new gist without an account, or if you had an account and were logged in, it'd add it to yours. But I think they had to stop that probably due to spam.

Let's keep brainstorming and researching, but for what it's worth, we could guide people like this perhaps:

```markdown
### Share by URL

To share a map by URL, you'll need to upload your saved map JSON file somewhere publicly accessible online. The easiest way is to upload the `mapknitter.json` file into the same Archive.org collection as your images. Then when you open that collection in MapKnitter Lite, it will auto-detect your saved map and place images as you had them.

### Share by email

You can also share your saved map file by email. Anyone with the file can drag it onto MapKnitter Lite, and it will fetch and place all the images you've saved. 
```

What do you think? This doesn't sound too bad if it's clearly presented in a modal, i think. Most folks will have already created an Archive.org collection, right?

**Comment by 7malikk** [comment]
> Hi @7malikk this is excellent research. I think it's not surprising that some kind of token or login is required. Otherwise IA could accept uploads from anyone without user login required. gist.github.com used to allow creating a new gist without an account, or if you had an account and were logged in, it'd add it to yours. But I think they had to stop that probably due to spam.
> 
> Let's keep brainstorming and researching, but for what it's worth, we could guide people like this perhaps:

Thank you @jywarren, I totally agree, I will keep searching for viable ways to get the files publicly accessible online, maybe not through IA.

> What do you think? This doesn't sound too bad if it's clearly presented in a modal, i think. Most folks will have already created an Archive.org collection, right?

These are good, and yes most folks should have already created an IA collection.

If I can not find another solution as to the auto-upload, I would kick off a PR with the latter.
Thank you for your input @jywarren

**Comment by 7malikk** [comment]
Hello, @jywarren I have resolved to move forward with the modal.

Although I had an idea inspired by this [tool](https://jsonserve.com/) where we have an API to which we send our JSON data in the body of a `POST` request and it responds with a URL to the hosted JSON data.

A friend and I worked on said API that utilizes MongoDB and Express. It was hosted on render.
Here is the post request URL: https://jsonserve.onrender.com/postjson
The codebase: https://github.com/Ojerry/jsonserver

I took into consideration amount of requests and storage, and with these, I came to the conclusion that the modal would be a better choice

I do want your opinion though, thank you!

**Comment by 7malikk** [comment]
Thank you @jywarren I totally agree.

#### Here's the current look: 

![shareMap](https://user-images.githubusercontent.com/75104021/215811756-8f00ba58-4f18-4442-b169-a594ec267fb7.gif)

I believe it looks good, I am finishing up on it, just one little error I want to resolve before making a PR.

**Comment by jywarren** [comment]
Looks wonderful. Great work!
