### ISSUE TITLE
downloadJSON error in JS

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1352]
https://github.com/publiclab/Leaflet.DistortableImage/blame/e451976953ba3d5f810b333be5e5eeaa67c4c27b/examples/js/archive.js#L348

I got an error that downloadJSON was not defined, and I think that variable name was just changed by @7malikk -- can you check this and look for a fix? I wonder if you forgot to check in a corresponding change elsewhere? Thanks!

**Comment by 7malikk** [comment]
I'll get this fixed, must've been an oversight on my part
