### ISSUE TITLE
Write a little documentation for these new MapKnitter Lite features

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1356]
Something to think on - we should write up a very brief description of how this works -- linking to some examples and maybe an example .json file like https://archive.org/download/empire-st-chinatown-providence/mapknitter-1676395083251.json

Not urgent but to consider!

**Comment by jywarren** [comment]
This can also be used in our blog post announcing it!

**Comment by segun-codes** [comment]
@jywarren, yeah it's important. Thanks! 

@7malikk if you could share little documentation on the part of the features you have developed so far, I'd do same for my part and then integrate the two works into a PR. What do you think?

**Comment by 7malikk** [comment]
@segun-codes That sounds great to me, I would get a write-up and send it to you ASAP. Google docs should suffice, right?

**Comment by segun-codes** [comment]
@7malikk, yeah Google doc is okay.

**Comment by segun-codes** [comment]
@jywarren, please where should documentation on the mapknitter-lite application be placed? I understand, documentation for the Leaflet.DistortableImage is located here: https://github.com/publiclab/Leaflet.DistortableImage.

**Comment by jywarren** [comment]
We could make a README.md file in the /examples/ folder, for starters?

**Comment by segun-codes** [comment]
Oh! that's right. Many thanks!
