### ISSUE TITLE
older &json= links don't work now?

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#1372]
Hi, @segun-codes @7malikk - i noticed maybe the older ?json= URLs no longer work --

https://publiclab.github.io/Leaflet.DistortableImage/examples/archive?json=https://archive.org/download/mapknitter-wayback/ceres--2.json

https://publiclab.github.io/Leaflet.DistortableImage/examples/archive?json=https://ia801508.us.archive.org/17/items/sanborn-1885/mapknitter-1676394104542.json

Was this intentional, or maybe we just missed it due to not having tests? No big deal, but I think there's still a strong case for preserving `?json=`, in case people store their JSON files somewhere else. 

No worries, this is the kind of thing tests would help us catch!

**Comment by segun-codes** [comment]
Oh! I removed support for older JSON since we migrated to shorter URL pattern. It was intentionally removed, not an error. Do you want to have it back?

**Comment by jywarren** [comment]
I think it makes sense since people could host .json files in other places
too -- sorry, I should have noticed that! Thank you!!!

**Comment by segun-codes** [comment]
Hi @jywarren, just to be certain. Does this mean support for `?json=` should be limited to only MK-Lite generated Json files and not legacy json files from mapknitter.org?

**Comment by jywarren** [comment]
Hi @segun-codes -- I believe we should support both. Is the code flow set up such that we can simply hand it off to the JSON interpreter function and it will auto-detect which type, and deal accordingly? That would be a really useful way to structure the code. Thanks @segun-codes !!

**Comment by segun-codes** [comment]
Okay, I will ensure the code is structured this way. Many thanks!
