### ISSUE TITLE
Rotate Event Callback

### ISSUE THREAD

**Issue by bencote** [publiclab/Leaflet.DistortableImage#1384]
I cannot find how to wire up an event callback for rotation events.

**Please describe the desired behavior.**
one of the other issues described wiring up an on.('drag') event to the editing subclass but that did not work. the issue was #980. I commented there but it was a closed issue.

**Additional context (optional)**

**Comment by jywarren** [comment]
Redirecting into https://github.com/publiclab/Leaflet.DistortableImage/issues/980, thank you for finding that!!

**Comment by jywarren** [comment]
Ah, and noticing that the 'rotate' event doesn't work with the technique I tested in #980, so modifying a bit for rotation:

Here, we'd have to attach the event to all four corner handles, for the "free rotate" or "rotate" handles:

```js
Object.values(map.imgGroup._layers)[0].editing._handles.freeRotate._layers[132].on('drag', (e) => {console.log('drag handles')})
```

See the different types of handles here:  `Object.values(map.imgGroup._layers)[0].editing._handles`

I'm not sure how easy it is to just listen to everything, but this is at least a way to listen for very specific types of rotation/free rotation. Hope that helps -- I tested the above code and one of the four handles does output log messages, in https://publiclab.github.io/Leaflet.DistortableImage/examples/archive
