### ISSUE TITLE
simpler menu API to add new tools to toolbar, even at runtime

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#141]
As more tools are added, we might use a simpler menu API to add new tools, even after initialization, like, perhaps:

```js
img = new L.DistortableImageOverlay(...);
img.addAction(
  EditOverlayAction.extend({ 
 	initialize: function(map, overlay, options) { 
 		var icon = 'rotate-left'; 
 		options = options || {}; 
 		options.toolbarIcon = { 
 			html: '<span class="fa fa-' + icon + '"></span>', 
 			tooltip: 'Rotate', 
 			title: 'Rotate'	 
 		}; 
 		EditOverlayAction.prototype.initialize.call(this, map, overlay, options); 
 	}, 
 	addHooks: function() { 
 		var editing = this._overlay.editing; 
 		editing._toggleRotateDistort(); 
 		this.disable(); 
 	} 
 })
);
```

The toolbar is built using https://github.com/Leaflet/Leaflet.toolbar, so we can look into how that library works. The API reference is here: https://github.com/leaflet/Leaflet.Toolbar/wiki/API-Reference#ltoolbar2action

**Comment by jywarren** [comment]
Created an issue on Leaflet.toolbar for ability to add actions at runtime!

**Comment by rexagod** [comment]
`_removeTool`(allows user to remove an action) was added in #155.
