### ISSUE TITLE
Develop image geocoding/altitude module using existing example code

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#142]
We have great code to:

1. extract GPS latitude/longitude and compass orientation from image EXIF data: https://github.com/publiclab/mapknitter/blob/20d887f4f3f5cb5302dc9865efe82106650def94/app/assets/javascripts/mapknitter/Map.js#L272-L337
2. create and display an image using LeafletDistortableImage using that data: https://github.com/publiclab/mapknitter/blob/20d887f4f3f5cb5302dc9865efe82106650def94/app/assets/javascripts/mapknitter/Map.js#L180-L238

We could build a function into this library to perform these steps, perhaps with something like:

```js
img = new L.DistortableImageOverlay(...)l
img.geocodeExif();
```

**Comment by rexagod** [comment]
Posting this here for reference: https://www.pic2map.com/nozetk.html

**Comment by rexagod** [comment]
WIP.

![screenshot from 2019-02-25 19-08-55](https://user-images.githubusercontent.com/33557095/53341228-02859380-3931-11e9-8eb1-ae0e97b02488.png)

**Comment by rexagod** [comment]
Apparently, the current `example.png` has no EXIF data associated with it.

![screenshot from 2019-02-25 19-41-46](https://user-images.githubusercontent.com/33557095/53343125-96595e80-3935-11e9-9964-5c65f3cf66c1.png)

**Comment by jywarren** [comment]
Ah, such a good point! I suppose we should swap it back for a .jpg so it can have exif data. Great catch!

Also now that more and more tools are being added, perhaps we should show examples of how to enable/disable the tools, in `/examples/` so as to show fewer/more. 

Great work @rexagod !!!
