### ISSUE TITLE
move code for hotkeys into /examples/hotkeys.html

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#16]
I think this is optional; hotkeys are useful for almost any application, so we can leave them in, too.

**Comment by rexagod** [comment]
Hotkeys can be tested straightaway in the `index.html` file as of now, but we can create a `html` just for the hotkeys. What do you think?

**Comment by rexagod** [comment]
It should be noted that here I'm referring to the ones inside the `DistortableImage.Edit.js` file.

**Comment by sashadev-sky** [comment]
@jywarren do we still need this issue?

**Comment by jywarren** [comment]
I guess not? Thanks!

**Comment by sashadev-sky** [comment]
Ok closing!
