### ISSUE TITLE
Separate each tool into its own file, starting with "toggleExport"

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#161]
Currently all the different tools live in this file:

https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/DistortableImage.Edit.js

I think it makes sense to create a new folder such as:

`/src/edit/tools/`

and have each tool be a separate file like:

`/src/edit/tools/export.js`
`/src/edit/tools/showToolbar.js`

etc. However, this library is not compiled using `browserify` or `webpack` and so we can't use `require()` to do this. 

Is it:

1. to add the tool methods to a subobject of `Leaflet`, like `L.DistortableImage.EditTools`?
2. to refactor this library to start using `require` (a lot of work... maybe not worth it)

In either case, we'll have to pass in some context to the tools; most ask for access to `this`, which in this case is the `L.DistortableImage.Edit` context. We could pass this in like so:

```js
L.DistortableImage.EditTools = L.DistortableImage.EditTools || {};

L.DistortableImage.EditTools.Export = function(edit) {
  function tool() {
    // then we can call it as we had been using `this`:
    // so this: this._lockHandles = new L.LayerGroup();
    // becomes:
    edit._lockHandles = new L.LayerGroup();
  }
  return tool; 
}
```

Then back in the [original `DistortableImage.Edit.js` file](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/DistortableImage.Edit.js#L309), we'd bind it back in like this:

```js
_toggleExport: L.DistortableImage.EditTools.Export(this);
```

The only thing left is that we'd need to add each tool to the concatenation script here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/a3dc6d10cc98716c6106261f47a8b9cee5be3c49/Gruntfile.js#L78-L81

This is a bit convoluted but should result in a simpler set of source files for the tools, where each file represents only a single function. 

@rexagod @sashadev-sky what do you think of this?

**Comment by sashadev-sky** [comment]
@jywarren I think that most modern rails applications use webpack and it wouldn't be difficult to set up a config file. I think we should go for the former because it is encapsulated and clear about what its point is. Would be to take this up once i get the exporter system for Mapknitter running

**Comment by rexagod** [comment]
@jywarren Let's pin this one! That would ensure that we abide by this approach. What to you think?

**Comment by sashadev-sky** [comment]
@rexagod pinned!

**Comment by sashadev-sky** [comment]
adding this here as it explains the end goal that this PR is working towards --

this is branched out of https://github.com/publiclab/Leaflet.DistortableImage/issues/140

<blockquote>
"We have a general need to brainstorm new UI designs for tools as more tools are added. Maybe nested menus or a modal for more tools, as the menu runs out of space?

But to explore this, I'd like to propose that we separate the tools UI from the tool functions themselves.

By abstracting the tools UI from tools functions, we'd allow for alternative tools UIs to be attached instead of default Toolbar..."
</blockquote>

**Comment by sashadev-sky** [comment]
@jywarren did I address this sufficiently in #393 to close this? I was going to do someting like L.LDITool.ActionName but it was so long I just stack gave them each L.ActionName and extended from L.EditAction

**Comment by sashadev-sky** [comment]
This one is good to close now!
