### ISSUE TITLE
Add options setting to determine default tool on load

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#167]
Some people prefer the rotate tool instead of the distort tool as the default. We should let people set the default in the constructor, and document it in the README. 

Any help appreciated!

**Comment by sashadev-sky** [comment]
Linking #51 and https://github.com/publiclab/mapknitter/issues/183 here

**Comment by sashadev-sky** [comment]
regarding that discussion, what did the toolbar UI look like back in 2015? I think as soon as a user sees a toolbar with a bunch of actions its clear that there is a lot they can do? Similar to how when you open photoshop you see all the editing icons. This will be something important to think about when making the UI.

**Comment by sashadev-sky** [comment]
I definitely agree that just switching the default to rotate would only create the opposite problem
