### ISSUE TITLE
Locked image not staying locked

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/Leaflet.DistortableImage#168]
### What happened just before the problem occurred
I was working on a map (the one of tidwell park in Houston) I had a couple images in place and was locking them as I went. One of my images didn't stay locked, it moved when I started on another image. It had the "x"s on the corners to show it was locked, but I was able to move it around. I can't recreate this now, but it happened! I'm on chrome. 

Thanks all !!
-Stevie

**Comment by sashadev-sky** [comment]
hey! I think my PR #158 might have solved this problem. I played around a lot with making sure locking and dragging works as it should. @jywarren do you think we should maybe close this one given I rewrote a lot of the original code already? Also confirming locking is working for me.

**Comment by sashadev-sky** [comment]
closed via #158
