### ISSUE TITLE
Allow images to be initialized as "selected"

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#174]
We should make some function or example code so that we can initialize a map with an image already selected. This will help us solve this:

https://github.com/publiclab/mapknitter/issues/124

**Comment by Polombo98** [comment]
Can I try to help?

**Comment by sashadev-sky** [comment]
@Polombo98 Yes we'd love your help! Please let me know if you have any questions

**Comment by rexagod** [comment]
@Polombo98 Are you still working on this?

**Comment by sashadev-sky** [comment]
@rexagod lets give a few days to respond if no response by Monday one of us can just grab this!

**Comment by Polombo98** [comment]
I'm going to work on that on weekend

**Comment by sashadev-sky** [comment]
@Polombo98 sounds good! Please just keep us updated!

**Comment by rexagod** [comment]
@Polombo98 Are you still working on this? Please do ping us if you're stuck anywhere, we'd be happy to help!

**Comment by sashadev-sky** [comment]
@rexagod I assumed  this one was dropped and I fixed it in detail in #229. 

See the snapshots here: https://github.com/publiclab/Leaflet.DistortableImage/pull/229#issuecomment-488183360

would love your review there also!

**Comment by sashadev-sky** [comment]
closed via #229
