### ISSUE TITLE
event.keyCode deprecated

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#178]
according to the [MDN docs on the `keydown` event](https://developer.mozilla.org/en-US/docs/Web/Events/keydown), the `keyCode`, `charCode`, and `which` attributes have all been deprecated in favor of a `key` attribute. 

There are a few places in the code where we can update this, but we would also want to update our keymaps to match. 

This is the file with the key maps: https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/DistortableImage.Edit.js

**Comment by sashadev-sky** [comment]
@jywarren do you think we should make some FTOs out of this?

**Comment by rexagod** [comment]
@sashadev-sky We can surely branch out some good FTOs out of this! Please let me know if I can be of any assistance. Thank you!

**Comment by sashadev-sky** [comment]
@rexagod Yeah do you know what the new convention is exactly? I think it's `key` but I didn't do a lot of research. But this we would have to plan together how to tackle because we would have to make sure to edit the keymap appropriately and any related functions. 

This is low priority but if you know how you want to move forward to make FTOs out of it, go ahead and I can follow your lead :)

**Comment by sashadev-sky** [comment]
@rexagod closing this because you already made an FTO out of it! Your FTO, once completed, updates the whole keymap so we don't need to reuse this now
