### ISSUE TITLE
How to update the rectangular, circular or x icon location on image overlay corner programmatically once a corner is updated?

### ISSUE THREAD

**Issue by kboul** [publiclab/Leaflet.DistortableImage#180]
Thank you for the nice plugin but I think it is missing a bit of documentation. To be able to use some built in methods it is necessary to dig up the code a bit. 

I would like to ask how to update programmatically the images' location. I am using **_updateCorner(number, coordinates)** to update the corners on the fly but I would like to do the same for the image. Is it possible?

Moreover, I would like to ask whether is possible to use custom images when initializing the distortable image or via css instead of the predefined ones.

Thank you in advance.

**Comment by sashadev-sky** [comment]
Hi @kboul! I am glad to help out. I actually just finished working on a project related to your question. i will be get back to you here later today :)

**Comment by sashadev-sky** [comment]
@kboul `_updateCorner` does update the position of the image (overlay), corner by corner, so are you asking for something else? Please expand!
https://github.com/publiclab/Leaflet.DistortableImage/blob/66301a2a83d27db7dfbae6cb5e96b55d9eadc076/src/DistortableImageOverlay.js#L132-L135

Also feel free to give any suggestions for functionalities you would like to see in the documentation. It's a WIP. For passing in your own image, update the src option when initializing the overlay:
https://github.com/publiclab/Leaflet.DistortableImage/blob/66301a2a83d27db7dfbae6cb5e96b55d9eadc076/examples/select.html#L82-L91

**Comment by kboul** [comment]
I was not clear. I meant the rectangular, circular or x icons on the image overlay edges
Example:
![calling_upadateCorner()](https://user-images.githubusercontent.com/14216599/55276864-96b49300-5301-11e9-9960-a527e9e1dbdb.gif)

I found a temporary solution by calling 

```
img.editing.disable()
img._updateCorner(number, newCornerCoords)
img.editing.enable()
```

and then it works for some reason
Example:
![calling_upadateCorner()_with_disable()_and_enable()](https://user-images.githubusercontent.com/14216599/55276880-cfed0300-5301-11e9-9d42-b78e5dbbbf5f.gif)

I m using React, react-leaflet and extending one of the abstract classes provided by React-Leaflet to use my custom DistortableImage class.

**Comment by sashadev-sky** [comment]
Right so you were just wondering if there is a method this is encapsulated into? Currently there is not because the update calls happen in other functions but in a version bump we are releasing soon there will be an `_updateCorners` method. Basically the same thing but easier to work with. In order to make the markers behave you can add another line at the end `this.fire("update")`. I typically perform some math on a current set of coordinates and the output (new desired coords) I pass in here: 

	_updateCorners: function (latlngObj) {
		var i = 0;
		for (var k in latlngObj) {
			this._corners[i] = latlngObj[k];
			i += 1;
		}

		this._reset();
               
               this.fire("update")

	},

This should synch the image and the markers for you. 
Let me know!

**Comment by kboul** [comment]
Amazing. Calling `this.fire("update")` after `img._updateCorner(number, newCornerCoords)` was exactly what I was looking for. Thank you.

**Comment by jywarren** [comment]
This is really cool... is your custom class open source? We'd love to take
a look at it!

**Comment by kboul** [comment]
I could share it but it is under development :). Where should I do it? Here, in this post or somewhere else?

**Comment by jywarren** [comment]
Sure, if you're comfortable doing so -- we would love to be aware so that
architectural decisions made here keep your coding in mind! Thanks!

**Comment by kboul** [comment]
```
import { withLeaflet, MapLayer } from 'react-leaflet'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'
import L from 'leaflet'
import 'leaflet-toolbar/dist/leaflet.toolbar.js'
import 'leaflet-toolbar/dist/leaflet.toolbar.css'
import 'leaflet-distortableimage/dist/leaflet.distortableimage.css'
import 'leaflet-distortableimage'
import { changeImageOverlayOpacity } from 'redux-local/actions'
import {
    closeColorPicker, changeImageOverlayBorder
} from 'redux-local/actions'
import { defaultBorderColor } from 'constants/defaultBorderColor'
import { leafletTypes } from 'propTypes'

class DistortableImage extends MapLayer {
    createLeafletElement() {
        const { url, topLeft, topRight,
            bottomLeft, bottomRight } = this.props
        const { map } = this.props.leaflet

        const distortableImage = new L.DistortableImageOverlay(url, {
            corners: [
                topLeft,     // nw
                topRight,    // ne
                bottomLeft,  // sw
                bottomRight  // se
            ]
        })

        // center image overlay on the map
        const bounds = new L.LatLngBounds(topLeft, topRight)
            .extend(bottomLeft)
        map.fitBounds(bounds)

        console.log(distortableImage)

        return distortableImage
    }

    updateLeafletElement(fromProps, toProps) {
        // dynamically change the border from outside
        if (toProps.border !== fromProps.border) {
            const { r, g, b } = toProps.border
            const borderEl = this.leafletElement.getElement().style
            if (r === 255 && g === 255 && b === 255) {
                borderEl.borderColor = 'transparent'
                return
            }
            borderEl.border = `3px solid rgb(${r},${g},${b})`
        }
        // dynamically change the opacity from outside
        if (toProps.opacity !== fromProps.opacity) {
            this.leafletElement.setOpacity(toProps.opacity)
        }
        // dynamically change the url of the image from outside
        if (toProps.url !== fromProps.url) {
            this.leafletElement.setUrl(toProps.url)
        }
        // change topLeft corner 
        if (toProps.newTopLeft !== fromProps.newTopLeft) {
            this.leafletElement._updateCorner(0, toProps.newTopLeft)
            // update x icon location on corners
            this.leafletElement.fire('update')
        }
        // change topRight corner 
        if (toProps.newTopRight !== fromProps.newTopRight) {
            this.leafletElement._updateCorner(1, toProps.newTopRight)
            this.leafletElement.fire('update')
        }
        // enable lock
        if (toProps.isLockEnabled) {
            this.leafletElement.editing._toggleLock()
        }
        // enable 4points
        if (toProps.is4PointsEnabled) {
            this.leafletElement.editing._toggleRotate()
            this.leafletElement.editing._toggleLock()
            this.leafletElement.editing._toggleLock()
        }
        // enable scale
        if (toProps.isScaleEnabled) {
            this.leafletElement.editing._toggleScale()
        }
        // enable rotate
        if (toProps.isAlignEnabled) {
            this.leafletElement.editing._toggleRotate()
        }
    }

    componentDidMount() {
        const { map } = this.props.leaflet
        const img = this.leafletElement
        img.addTo(map)
        L.DomEvent.on(img._image, 'load', img.editing.enable, img.editing)
        setTimeout(() => {
            map.setZoom(18)
            // call here it with locked corners 
            // in order edit functions to be defined
            img.editing._toggleLock()
        }, 10)
        const { changeImageOverlayOpacity, closeColorPicker,
            changeImageOverlayBorder } = this.props
        // revert imageOverlay style to default
        changeImageOverlayOpacity(1)
        closeColorPicker()
        changeImageOverlayBorder(defaultBorderColor)
    }
}

DistortableImage.propTypes = {
    leaflet: leafletTypes,
    changeImageOverlayOpacity: PropTypes.func.isRequired,
    closeColorPicker: PropTypes.func.isRequired,
    changeImageOverlayBorder: PropTypes.func.isRequired
}

export default connect(null, {
    changeImageOverlayOpacity,
    closeColorPicker,
    changeImageOverlayBorder
})(withLeaflet(DistortableImage))
```
