### ISSUE TITLE
Update to correct class factory syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#182]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet docs](https://leafletjs.com/reference-1.0.0.html):
<blockquote>

Class Factories
You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');

</blockquote>

**What actually does happen:**

We use Leaflet's built-in `L.map` to initialize our map, but we add a superfluous `new` at the beginning of it. Let's update the code by removing it in the files indicated below.

## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword from the following code blocks:

1) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/66301a2a83d27db7dfbae6cb5e96b55d9eadc076/examples/index.html#L68-L71

2) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/66301a2a83d27db7dfbae6cb5e96b55d9eadc076/examples/select.html#L38-L40

3) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/66301a2a83d27db7dfbae6cb5e96b55d9eadc076/examples/listeners.html#L38-L40

**lets update the `README.md` file for consistency**

4) here:
https://github.com/publiclab/Leaflet.DistortableImage/blob/main/README.md#usage

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by Priyak5** [comment]
hey! Can I work on this issue?

**Comment by sashadev-sky** [comment]
@Priyak5 Yes please do!

**Comment by Priyak5** [comment]
@sashadev-sky Thank you so much!

**Comment by Priyak5** [comment]
@sashadev-sky please review. Thank you.

**Comment by sashadev-sky** [comment]
closed via #183
