### ISSUE TITLE
Bug: Multiple image select with boxZoom

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#186]
Currently to select multiple images, you can use `cmd + click`. There is another feature, found in the file `BoxSelectHandle.js` (https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/edit/BoxSelectHandle.js)
that overrides Leaflet's default boxZoom to allow for using `shift + drag` to select multiple images.

However, there is a bug with it so currently the event listener for this functionality is commented out. To test this bug uncomment this line.
https://github.com/publiclab/Leaflet.DistortableImage/blob/88fe9281cb7c00cc90c4a52029bf2ca7763553de/src/DistortableCollection.js#L16

**Actual behavior** 
![boxSelect](https://user-images.githubusercontent.com/41092741/55284379-6261c680-5343-11e9-967c-8ba4f94beab8.gif)

- After click on the map to deselect, clicking an image in the same area as the previous boxSelect area reselects the images for multiple select (something that typically should only be triggered by `cmd + click` not regular click).

**Expected behavior**
- By leaving an image out of the boxSelect area, I demonstrate the expected behavior (**no reselections on regular click**):
![boxSelect3](https://user-images.githubusercontent.com/41092741/55284416-38f56a80-5344-11e9-98d6-802bd36a4a9d.gif)

**Relevant lines of code**
- the `BoxSelectHandle.js` file linked above overrides the default boxZoom handler
- in the Leaflet.DisortableCollection.js, the event listener runs the code in 
https://github.com/publiclab/Leaflet.DistortableImage/blob/88fe9281cb7c00cc90c4a52029bf2ca7763553de/src/DistortableCollection.js#L64-L78 to decide which images to select. 
- have to figure out what is causing the reselection (event propagation, event execution deferral, etc.?) and stop it

**Comment by sashadev-sky** [comment]
@jywarren the buggy behavior I was referring to in #158

**Comment by shivam15** [comment]
can i try this one?

**Comment by sashadev-sky** [comment]
@shivam15 Yes please!! Let me know if you have any questions because I wrote the original code for it.. just couldn't get it to work properly!

**Comment by rexagod** [comment]
**One more thing:** If I delete an image, then try to drag the selection, it throws an error at every mouse drag movement (see below). Let's see if resolving this issue resolves this one too, otherwise I'll open a separate issue for this.

![boxzoombug](https://user-images.githubusercontent.com/33557095/56820204-e5a20980-6868-11e9-9583-b04f80e91550.gif)

**Comment by sashadev-sky** [comment]
@rexagod I fixed this in my pending PR

**Comment by sashadev-sky** [comment]
@rexagod also not the box select feature only works best if you drag from bottom-right towards top-left. Cannot explain exactly why this is

**Comment by rexagod** [comment]
```
leaflet.distortableimage.js:915 _deselectOthers
leaflet.distortableimage.js:904 _toggleMultiSelect
leaflet.distortableimage.js:929 _addSelections
```

For some reason, ` _addSelections` is getting unexpectedly triggered after some particular functions, even after I suppress the event propogation.

**Comment by rexagod** [comment]
Okay so the "boxzoomend" is definitely not firing when it should, either that, or something else is triggering the `_addSelections` method.

**Comment by rexagod** [comment]
Okay so the `boxzoomend` by default, in the leaflet library, is triggered on the "mouseup" event. This leads to the triggering of the `_addSelections` whenever a "mouseup" is detected, hence causing these "reselections".

Now I did try to `unbind` "mouseup" and "boxzoomend" listeners at different places in the code, and enable them back again, but there are some corner cases the eventually always remain.

Looking into this, @sashadev-sky.

**Comment by rexagod** [comment]
Also, currently, `_deselectOthers` only removes the markers from the other images (other than `e.target`) while it should also remove the "selected" class as well.

**Comment by rexagod** [comment]
To further clarify  on this, notice two different subroutines that occur.

- `_addSelection` gets executed on every single "mouseup" event
- Reselection takes place respective to the sequence in which the images were selected (was bottom-left to top-right below)

![Peek 2019-04-28 14-14](https://user-images.githubusercontent.com/33557095/56861603-10eb3c80-69c0-11e9-9fe8-8598a72d1399.gif)

**Comment by rexagod** [comment]
We're close (no reselections bug)! Just need to implement a few final changes to make sure everything's working as expected.

![ezgif-5-50d5d5aebad0](https://user-images.githubusercontent.com/33557095/56862549-c1117300-69c9-11e9-8638-b49ff499a74f.gif)

**Comment by rexagod** [comment]
@sashadev-sky I'm letting go of the above implementation and in fact considering some ideas that I'd like your thoughts on.

- We need to rewire the listeners on the `_addSelection` functionality, to avoid the confusion b/w "boxzoomend" and "mouseup" events.
- At the moment, I'm considering extended "boxzoom" functionality wired to a more _convenient_ key binding (something other than mouseup so that it doesn't go off unexpectedly) in order to inherit the nice little box selection property while disabling the "mouseup" listener at `initialize`.
- This way we can actually avoid overriding the boxzoom functionality since we very well might need it in the future, or now.

**Comment by sashadev-sky** [comment]
Woah amazing! I can't imagine ever needing "boxzoom" for its original purpose, to zoom into a specific area. Seems like a very inconvenient way to just increase zoom. So I manually fire `boxzoomend` from the `_mouseUp` method, so I guess we could realistically fire it anywhere.

I think whatever we do it should definitely `select` them immediately (yellow highlight) without having to click on them. Is it possible to just make `_addSelection` listen for `boxzoomend`? Then there will be no confusion between them?

**Comment by rexagod** [comment]
It is possible to make `_addSelection` listen for`boxzoomend` and pardon me, but isn't that what we are doing in the lib right now? The catch here however, as I stated above, is the fact that `boxzoomend` by default, in the leaflet library, has been wired to the mouseup event, overriding which, is causing compatibility problem as discussed above. Therefore, I suggested [some workarounds](https://github.com/publiclab/Leaflet.DistortableImage/issues/186#issuecomment-487391635) above that should make this work, while alternatively we can open up on issue regarding the same in Leaflet that could potentially save us some efforts.

**Comment by sashadev-sky** [comment]
@rexagod can you move these changes into a new feature BR and upload a PR so I can look into what we have now?

**Comment by sashadev-sky** [comment]
so excited to get this one fixed!!!

**Comment by sashadev-sky** [comment]
closing via #314
