### ISSUE TITLE
Update tests in edit folder to correct class factory syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#189]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

In a previous FTO #182, initializing the L.Map class was updated to use the Leaflet libraries standard, shorter class factory syntax:

From the official [Leaflet](https://leafletjs.com/reference-1.0.0.html) docs:

<blockquote>
Class Factories

You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');
</blockquote>

Since testing is a form of documentation in addition to a way of ensuring stable functionality, we want to keep our tests consistent with our code syntax. Let's make updates to all our test files to match this class factory syntax.

## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword and change `L.Map` to `L.map` in the following code blocks:

1)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/edit/DistortableImageEditSpec.js#L6

2)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/edit/RotateAndScaleHandleSpec.js#L7

3)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/edit/RotateHandleSpec.js#L7

4)
https://github.com/publiclab/Leaflet.DistortableImage/blob/2a70c099387fad4e5b7c84cf866ee55e787a7e20/test/src/edit/ScaleHandleSpec.js#L7

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by shivam15** [comment]
I would like to take this. Please assign it to me

**Comment by sashadev-sky** [comment]
@shivam15 Thank you! Go for it!

**Comment by DilanLivera** [comment]
@sashadev-sky is this still open, If it is could I take it please?

**Comment by gauravano** [comment]
hey @DilanLivera, this one is claimed. But, we would love to have your help with other issues, you can check https://code.publiclab.org/#r=all for issues. In case, you don't see any unclaimed or unassigned FTO,  feel free to comment at https://github.com/publiclab/plots2/issues/4963 and we'll create a FTO for you. Thanks!

**Comment by shivam15** [comment]
@sashadev-sky created pull request

**Comment by shivam15** [comment]
if you have any more issues please assign it to me

**Comment by sashadev-sky** [comment]
@shivam15 if you like working in this repo, check out the [issues page](https://github.com/publiclab/Leaflet.DistortableImage/issues) look for labels "Help Wanted". It a very cool repo to get involved in! 

I cant assign you any more FTOs but you can either move on to a Help Wanted issue or create your own FTO for someone else to solve.

**Comment by sashadev-sky** [comment]
closed via #192
