### ISSUE TITLE
icons for Rotate and Scale for custom toolbars

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#208]
It currently does not. If not, why?

@jywarren @rexagod 

==========
**UPDATE** - have decided that we will make icons for these so that a user can add them to the toolbar if they would like, but they will not be default actions in it. So before this, must first implement **custom toolbars**

**Comment by rexagod** [comment]
I guess we can include this using the `reveal` functionality, since the toolbar is already pretty packed at the moment. Let's see what @jywarren has to say on this. Thanks!

**Comment by sashadev-sky** [comment]
@rexagod shouldn't ever keymap option also have a non keyboard option? For mobile compatibility? Like how would you access the scale handles on an iphone?

**Comment by rexagod** [comment]
I see. Keeping this in mind for #207.

**Comment by sashadev-sky** [comment]
Renaming this issue since we decided to keep these actions. @rexagod any ideas on how to implement this? I was thinking maybe `distort` would have its own icon, and `rotateScale` will toggle with the regular `rotate` action. Then `scale` will just have its own icon? Then we can keep building out how we categorize and compartmentalize the toolbar actions in a sensible way? 

Maybe this is something I can quickly update in my open PR #255? I would update the keybindings to toggle between RotateScale and Rotate as well. 

@jywarren

**Comment by jywarren** [comment]
Do we currently use FontAwesome icons? I can never remember. Oh looks like it: https://github.com/publiclab/Leaflet.DistortableImage#image-ordering

Maybe we should link to these in the README: https://fontawesome.com/v4.7.0/icons/

**Comment by sashadev-sky** [comment]
@jywarren sure, should I add this as something to address in #255?
