### ISSUE TITLE
Weekly Community Check-in #18 - Ask or Answer

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#215]
Hello Everyone!!!

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal dart. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check:

If you're new here, welcome :balloon: and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.
You can find them at 

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom :open_hands:

**Gitter**

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation page.

**This Week's Theme**

**Ask or Answer** means either answer a question posted by a contributor here, or ask a new one. Questions can be about anything that furthers your path as a developer or PL contributor. 
   - You can do both!
   - Preferably no questions about GSoC
   - If you answer a question with a link, please provide some sort of further commentary onto it

**Google Summer of Code & Outreachy**

~~ Applications are in review ~~

**Community Survey**

@ebarry has compiled the results of the community survey, which was open from January 14 to March 21, into a comprehensive code community report. Please add your comments here to this thread for what we are inspired to do/change as a result of reading:[https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey]( https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey)

This is a really unique opportunity to contribute to open source from a greater scope, and a reminder of the greater meaning behind the work all of you have been doing!! 

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 
@niravasher

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-

Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva
Harshith Pabbati (@Harshithpabbati)
Harman Jolly (@CoderJolly )
Divya Baid (@divyabaid16)
Gautami Gupta @gautamig54
Sasha Boginsky

Have a great week everyone :balloon: :tada: :sparkler:

**Comment by sashadev-sky** [comment]
@marieram @swiatek7 @kaunair @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps

@subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi

**Comment by sashadev-sky** [comment]
@shubhi2000 @Priyak5 @vaarigupta @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @jtmims @scheleon @mahmodHammad @santushk @jillpena @stoic-plus
@vaarigupta @alonpeer @madeofhuman

**Comment by sashadev-sky** [comment]
@ibnjunaid @HarshKhandeparkar @aashna27 @Harshithpabbati @niravasher @mmmelissa

**Comment by sashadev-sky** [comment]
I will start: What tools would a developer use to test a UI for Android from a MacOS?

**Comment by ebarry** [comment]
Hi all! The final survey results are posted to the original issue which i've re-opened and pinned to the top of the PLOTS2 repo to host any discussion. I'm imagining we might chat about what we learned and reflected upon after reading it, and what ideas are occurring to us about how to be a community together? https://github.com/publiclab/plots2/issues/4614 Thanks!

**Comment by cesswairimu** [comment]
Hello everyone :wave: ,

This week I am still working on mapknitter. 
@sashadev-sky I normally use `browser stack` it gives you all the interfaces of different OS and various versions and different browsers, one setback is the free version has limitations on the browser versions you can use but if you wonna test using the lastest browser versions you are good. 
Awesome theme.
Nice week ahead everyone :balloon:

**Comment by sashadev-sky** [comment]
@ebarry I put a section in the check-in regarding the discussion thread, feel free to make any edits to it!

**Comment by sashadev-sky** [comment]
@cesswairimu Thank you!! I will try this out

**Comment by sagarpreet-chadha** [comment]
Hi all :balloon:  ,
Great theme @sashadev-sky :+1:  :100: ,
I will be working on leaflet blurred projects along with some minor/major UI work of maps on plots2 .
The work on community survey analysis in commendable @ebarry @jywarren :raised_hands: :clap:  :medal_sports: .

Following this week's theme , i would like to ask if i can open next week's community checkin :smile:  ?
Thank you !!!

**Comment by sashadev-sky** [comment]
> Hi all 🎈 ,
> Great theme @sashadev-sky 👍 💯 ,
> I will be working on leaflet blurred projects along with some minor/major UI work of maps on plots2 .
> The work on community survey analysis in commendable @ebarry @jywarren 🙌 👏 🏅 .
> 
> Following this week's theme , i would like to ask if i can open next week's community checkin 😄 ?
> Thank you !!!

Yes please do! You might want to mention again here on Saturday you'll be opening it to remind everyone!

**Comment by gauravano** [comment]
Hi everyone!

Great check-in Sasha!

Sorry @ebarry, wasn't able to help with survey compilation.

To everyone, please label your PR `review-me` if it's ready to review and
reviewers can add `ready` label after approving PR. My inbox is a little
wild right now, but I will be all caught-up before weekend.

Specifically in plots2, if your PR/issue is waiting sorry for delay. Feel
free to mention @reviewers/plots2-reviewers

Have a great week ahead :100:

Gaurav Sachdeva

**Comment by sashadev-sky** [comment]
@cesswairimu just used browser stack here #38 worked really well thank you!!

**Comment by gauravano** [comment]
@kingingcole @MattMski @kaustubh-nair @igniteeng000 @shivam15 @rkpattnaik780 @manansingh96 @skilfullycurled @subhahu123

**Comment by skilfullycurled** [comment]
Hey everyone,

I made my first PR!  With special thanks for the encouragement and @gauravano for doing the review.  It was a great experience and I hope to continue.  It also gave me a lot of ideas about tiny things I can add to documentation, and some other things to be discussed.  I'll be writing about them.  I'd really like to do something else this week of the same difficulty: having already worked on a "first-timers" issue (and therefore no longer a "first timer", am I no longer able to claim them?

**Comment by sashadev-sky** [comment]
Hi @skillfullycurled! I’m glad you had a great experience! After completing an FTO, we encourage users to move on to a help-wanted issue. 

The difference between these is that FTOs generally don’t involve any “coding” - the challenge in them is to be able to successfully make a PR following the PL workflow. 

The helpwanted issues build on this skill and you do a coding task with more abstract instructions (you are not given the solutuon directly) following the same workflow

if you want to practice the git workflow again, mention me here and I would be glad to create an FTO for you that will strengthen your understanding of Git. Let me know!

**Comment by gauravano** [comment]
Also @skilfullycurled, you figured out many things on your own - https://github.com/publiclab/plots2/pull/5459, which is great! , so I think you'll not require another FTO, but as Sasha mentioned, if you want to practice Git, then you can work on another one. As you did the changes from GitHub for your current PR so for next FTO, I will suggest - you should install the repo, do the changes locally and you know the rest.

Thanks!

**Comment by skilfullycurled** [comment]
Gotcha.  Sounds good.  In the future, I'd like to update Liz's tutorial ["How to make the most basic github contribution"] (https://publiclab.org/notes/liz/11-02-2016/make-the-most-basic-github-contribution) to include the review process.  I also think a link to her tutorial should be added to the ["check out our work flow"](https://github.com/publiclab/plots2/blob/master/README.md#first-time) on the wiki.  It's really essential if for whatever reason you don't want to use the terminal route.  I'll file an issue about it, and if people are game for the change, then perhaps I can [create my own FTO issue](https://github.com/publiclab/plots2/issues/4963) issue in which I make a change to the wiki so that I can take accurate screenshots?

I'd like to do more work on the stats page which I hope will involve creating more complicated versions of what I just did.  So this week I'll just make a mention [there](https://github.com/publiclab/plots2/issues/3498) and see how to get started.

**Comment by MattMski** [comment]
Hello everyone,

Well first off, I want to say thank you for making my first PR experience fun, helpful, and educating. I'm taking a college class where we actually have to contribute to any open source project on GitHub, etc. I had found something but had slacked off until last week when i stumbled upon this project. And the fact that there are so many first timer issues is amazing for someone like me. You guide them into what they need to fix and pretty much tell them how to do it, and it helps make both sides good. That's amazing, this was truly an amazing experience and i hope to do more contributions to open source, especially your project. I'm going to be posting some of the communication between us, as well as the work I did, because we have to do a presentation based on our experience and talk about every aspect of it. Once again, thank you very much for really saving me the last few weeks of my class. And thank you for just making it so simple as long as you read, anything can get done fast.

**Comment by ebarry** [comment]
Hi all, over in https://github.com/publiclab/plots2/issues/4614, i just posted a poll to identify a good time to meet and discuss the recently posted survey results. reposting here, thanks!
https://www.when2meet.com/?7773453-c7gAs

**Comment by sashadev-sky** [comment]
@skilfullycurled I think to make edits to a PL wiki, you can only do this in the browser and you also need to have posted at least 1 wiki or research note yourself (this is to prevent spam). So you will either need to do that or collaborate with @ebarry to make the updates!

**Comment by skilfullycurled** [comment]
Poor choice of words.  I was referring to the README.md on the front page (changing the link/adding text to differentiate between the terminal workflow and the browser workflow). I was also referring to the .md docs for the repo ([for example](https://github.com/publiclab/plots2/tree/master/doc)).  I always forget that they are not in the GitHub repo wiki.  

It's not a well formed idea yet.  My main point was that at some point it would be great to have another FTO for the sake of documenting the process.  Perhaps there could even be an activity where the goal is simply to add your name to one of the docs.  Again, not well a well formed idea.  I'll create an issue to discuss in the future.

**Comment by jywarren** [comment]
Hi all! so late in the week, i'm sorry! As you may have noticed, I've been in a big backlog after traveling for work over the past weekend. 🔙 🌳 <= (back log)

But I'm working my way out of it with your help! @sagarpreet-chadha saw your amazing work, great job! And @Divy123 @VibhorCodecianGupta @tech4GT and many others in [Image Sequencer](/publiclab/image-sequencer) have been doing really great work, resulting in super great bugfixes and new features, from image warping to test coverage and more. 🎉 🤝 

Noting that @kaustubh-nair made a big breakthrough ⚡️ in getting CodeCov installed in MapKnitter (https://github.com/publiclab/mapknitter/pull/543) after we did the same in Image Sequencer, and it's just very cool to see this visualization of coverage:

![image](https://user-images.githubusercontent.com/24359/56392748-46459c80-6200-11e9-8387-453b3bbaf75f.png)

This is so important, because in all our projects, as the code grows, matures, and also becomes more complex, we need good tests or we'll keep breaking things as we work. This reminder in PRs is really nice to keep an eye on the tests, and to encourage us to write them as we go, laying a protective shield over our work! 🛡 👁 📊 🛠 

Thanks everyone!!!!

**Comment by ebarry** [comment]
*** apologies for cross-posting from publiclab/plots2#4614 ***

We've got a clear choice: Sunday 10:30-11:30 PM India time, 1-2 PM East Coast US time. 

Topic: Public Lab Software Contributors 2019 Survey Report: Discussion
Time: Apr 21, 2019 10:30 PM India Time / 1:00 PM Eastern Time US and Canada
Place: https://zoom.us/j/346913422
Notes: https://pad.publiclab.org/p/developers

### Ahead of time:

* Please enter the discussion topics you wish to discuss on the pad. Please attempt to organize questions and comments under the appropriate headings which correspond to each section of the report: https://pad.publiclab.org/p/developers  Thanks!

cc @gauravano @cesswairimu @skilfullycurled @CleverFool77 @rexagod @sashadev-sky @jywarren @SidharthBansal @HarshKhandeparkar and everyone on this thread :)

**Comment by skilfullycurled** [comment]
![its_merrrrged](https://user-images.githubusercontent.com/950291/56463898-c9572600-63ab-11e9-8947-8bfe1fa4cdb0.gif)

**Comment by HarshKhandeparkar** [comment]
@gauravano has anyone booked the next check-in?

**Comment by cesswairimu** [comment]
@Harshithpabbati , @sagarpreet-chadha booked the next maybe you can open the next after him?

**Comment by HarshKhandeparkar** [comment]
Ok. Thank you. Btw, I am HarshKhandeparkar 😂. People do this very often.

**Comment by cesswairimu** [comment]
My bad :woman_facepalming: sorry

**Comment by HarshKhandeparkar** [comment]
Np

**Comment by Harshithpabbati** [comment]
😂

**Comment by cesswairimu** [comment]
Hello @Harshithpabbati, sorry for unneccesarry tagging

**Comment by Harshithpabbati** [comment]
Ha thats not a problem leave it :)

**Comment by sagarpreet-chadha** [comment]
Thank you @sashadev-sky for the check-in 😄 !
Next check-in opened in LBL : https://github.com/publiclab/leaflet-blurred-location/issues/198
Closing this issue 🎈 .
