### ISSUE TITLE
edgeMinWidth and edgeMinHeight properties

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#219]
This library was experiencing a few bugs before adding the `edgeMinWidth` and `edgeMinHeight` properties available to pass to an image on initialization. 
- such as #172 
- and #85 

These limit the minimum height and width that you can scale the image down to, by passing these properties when creating the image and setting them to a number larger than the actual respective w/h of the image https://github.com/publiclab/Leaflet.DistortableImage/blob/b84229e727538e44f7e386243161b9bae379dd41/examples/select.html#L63-L74

It sets this limit here:
https://github.com/publiclab/Leaflet.DistortableImage/blob/b84229e727538e44f7e386243161b9bae379dd41/src/edit/RotateAndScaleHandle.js#L23-L38

I hardcoded a quick fix for the example images our repo uses in #158 , but to really implement it we need to:
- 1) Set reasonable default options in `Leaflet.DistortableImageOverlay` so that the user doesn't have to pass the image dimensions manually. Currently only have `EdgeMinWidth` set. (Currently about 2x the width of the image, which looks reasonable, but review this value).
https://github.com/publiclab/Leaflet.DistortableImage/blob/b84229e727538e44f7e386243161b9bae379dd41/src/DistortableImageOverlay.js#L8
- 2) Document these properties in the README if we want to define them as part of the API. (Leaning towards removing the passed options in the html file and considering them 'internal' properties we set)
- 3) When calculating image dimensions update the properties dynamically to adjust to the new image - image can always change sizes and proportions through distortions.
- 4) Create tests - shell here: https://github.com/publiclab/Leaflet.DistortableImage/blob/b84229e727538e44f7e386243161b9bae379dd41/test/src/edit/RotateAndScaleHandleSpec.js#L23-L25 and document if statically proportioned values still prevent distortions if the image is distorted to a different shape and then scaled + do some UI testing. (most likely will need to be dynamic props)
- 5) add the method to `ScaleHandle.js` as well

**Comment by sashadev-sky** [comment]
@rexagod @jywarren

**Comment by jywarren** [comment]
OK, i agree with this needing some work. But I don't think it's a priority vs. the new exporting system. 

I do note that in this demo, I can scale these images smaller than the set min width/height:

https://publiclab.github.io/Leaflet.DistortableImage/examples/select.html

![image](https://user-images.githubusercontent.com/24359/56441560-874eb700-62bb-11e9-9ab4-41faec899bcf.png)

So it looks like it needs some debugging as well! 

I don't mind it being a public API, if it's well tested. Thanks!!

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by sashadev-sky** [comment]
linking #320

**Comment by jywarren** [comment]
Fix in #340 - and noting that `edgeMinWidth` is expressed in container (screen) pixels, so it should be scale invariant. Basically, we're saying "don't allow scaling down if the image is already less than X pixels wide on the screen (because it'll be too small to manipulate anyways)" with the implication that you should just zoom in if you want to make it smaller; then regardless of map zoom level, you'll be able to get it down to ~X pixels in width. I think this should be good!

**Comment by sashadev-sky** [comment]
@jywarren should we add some `edgeMinWidth` tests and open it to the API? I think it could be a really cool customizable aspect of the overlay and used for different things

**Comment by jywarren** [comment]
Sure, that sounds good!
