### ISSUE TITLE
Toolbar disappears when clicking on rotate icon, then on image (in simple demo)

### ISSUE THREAD

**Issue by flopail** [publiclab/Leaflet.DistortableImage#221]
... and no way to increase/reduce proportionally image size. Does something change recently in simple demo (below) ? https://publiclab.github.io/Leaflet.DistortableImage/examples/

Thanks,
:)

**Comment by rexagod** [comment]
@flopail This has been fixed in #201. As for the proportional resize, we have  a "scale" function for the same, and we are working on including it in the toolbar. Thanks!

**Comment by sashadev-sky** [comment]
@flopail ^ to add on I think you can access it now with the hotkey `s` but in the PR referenced above we are also fixing a bug where hitting `s` again won't toggle you out of scale mode so you'll have to hit a hotkey for another handle if you want to get out of it .. until we merge mentioned PR

**Comment by flopail** [comment]
Thank you @rexagod and @sashadev-sky !

**Comment by sashadev-sky** [comment]
closed via #201

**Comment by sashadev-sky** [comment]
ok this is fixed now via #201 ... @jywarren do we need to do anything else to make sure the demo itself is updated?

**Comment by jywarren** [comment]
I can update the demo now! I merge to gh-pages with a merge commit and
install any necessary new npm packages, then push.

**Comment by sashadev-sky** [comment]
@jywarren awesome! Updates are live there.

@flopail please revisit demo now and your issue should be resolved! 

Thank you, closing via #201

**Comment by maximebizeray** [comment]
Hi guys! 

I'm facing almost the same issue as this one. The toolbar is active when I load my image but sometimes when I click on the map or on the image, the toolbar disappears. And  I can't make it come back when I click on the image like in the demo.

Any idea what I do wrong ?

Here is my code:
`map = Leaflet.map('map').setView([51.505, -0.09], 18);
      map.addGoogleMutant();

      img = Leaflet.distortableImageOverlay('image.png', {
          selected: true,
          actions :[Leaflet.DragAction, Leaflet.ScaleAction, Leaflet.RotateAction, Leaflet.OpacityAction]
        }).addTo(map);`
