### ISSUE TITLE
Update L.DistortableCollection test to use class factory syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#228]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet](https://leafletjs.com/reference-1.0.0.html) docs:

<blockquote>
Class Factories

You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');
</blockquote>

We have recently added a factory method to the `L.DistortableCollection` class and updated our code to initialize new instances of this class using it: 
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec123048635660e1f79ed30ceaf2747e7e664e2e/src/DistortableCollection.js#L182-L184

Since testing is a form of documentation in addition to a way of ensuring stable functionality, we want to keep our tests consistent with our code syntax. We'll need to update our test files. 
 
## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword and change `L.DistortableCollection` to `L.distortableCollection` in the following code block:

1)
https://github.com/publiclab/Leaflet.DistortableImage/blob/ec123048635660e1f79ed30ceaf2747e7e664e2e/test/src/DistortableCollectionSpec.js#L29-L34

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by Shal1928** [comment]
I am try this issue.

**Comment by sashadev-sky** [comment]
@Shal1928 did you comment here that you wanted to try this? Did you change your mind? Sorry just want to make sure because I received it in an email but don't see your comment here

**Comment by Shal1928** [comment]
@sashadev-sky , Hello. Yes, changed my mind. I'm sorry.

**Comment by sashadev-sky** [comment]
@Shal1928 No problem!

**Comment by Shal1928** [comment]
@sashadev-sky , But I would like to understand the following. This issue created is artificially (falsely), **only for** pass by checkpoints for begginers?

**Comment by sashadev-sky** [comment]
> @sashadev-sky , is artificially (falsely), **only for** pass by checkpoints for begginers?

Not sure if you're saying the issue itself is falsely created or suggesting that it's false that this is for beginners. Please clarify! 

But in case this answers your question: these are actual issues we spot in the repo, then instead of opening a PR for them ourselves, we open a step by step issue explaining exactly what lines to change and how to make a PR. They are intended for beginners because their point is to familiarize the new contributor with the Git workflow, and takes out all the doubt about the code needed to fix the issue.

**Comment by GauravJ3** [comment]
hi, i want to contribute

**Comment by Shal1928** [comment]
@sashadev-sky, thank you for answer. You Do not mind if I ask to add me to the reviewers this issue for better understanding process?

**Comment by sashadev-sky** [comment]
@GauravJ3 Hi, we would love your help! This ones all yours

**Comment by sashadev-sky** [comment]
@Shal1928 if you want to understand the process please complete a first-timers-only issue. I can make you one in this repo if you would like
