### ISSUE TITLE
change rotate/distort hovertext in Toolbar when swapping between them

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#246]
saw this mentioned by @jywarren in https://github.com/publiclab/mapknitter/issues/124 and this bug still needs to be resolved! 

Additionally, I think maybe could be helpful to change the icons that are used. Currently, I always get confused about which one is meant for rotate vs distort as I can't make the connection between the icon and the action.

**Comment by jywarren** [comment]
maybe FontAwesome icons have expanded enough that we could try to find a
more suitable one?

**Comment by sashadev-sky** [comment]
@jywarren just opened a PR so i'll post icon suggestions there! #255

**Comment by sashadev-sky** [comment]
closed via #255
