### ISSUE TITLE
Refactor out `_calculateAngle` method

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#260]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We rewrite the same function, `_calculateAngle` in a few of our files for each new "handle" class to have. Instead, we can define this function on `L.EditHandle`, the common class the other handle classes extend, and it will be available to all of them.

## Solution

**Where to find the relevant lines of code**: 

Delete  the `_calculateAngle` function from the following files:

1) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateHandle.js#L28-L40

2) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/RotateScaleHandle.js#L44-L56

3) 
https://github.com/publiclab/Leaflet.DistortableImage/blob/d91b2d7e946ae8ce064535dea8a0320683934b1f/src/edit/ScaleHandle.js#L29-L41

4) Then, copy it into `src/edit/EditHandle.js` (you can add it as the last function defined on the `L.EditHandle` class).

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
assigned to @AdityaShD!

**Comment by AdityaShD** [comment]
hey! @sashadev-sky thanks for assigning, I'll get right on it :)

**Comment by dannomayer** [comment]
Hello @sashadev-sky ! Love the description. I am looking to make my first contribution to an open source project and the documentation you've provided on how to do so is really helpful. I feel so overwhelmed whenever I try and contribute but this is clear and concise. Unfortunately... Both first timer issues I've found through this project appear to have been claimed. And this one in particular was assigned, causing me to wonder if there is some list you are pulling from of people who have expressed interest in contributing? Unfortunately I am not from an underrepresented group, but I am still very interested in contributing to open source!

**Comment by AdityaShD** [comment]
@sashadev-sky I am done with making changes on my local machine, what are the steps which i need to follow now?

**Comment by AdityaShD** [comment]
and also commited the code to a branch 'calculateAngle' .

**Comment by sashadev-sky** [comment]
@dannomayer Hey, welcome to PL! You do not have to be from an underrepresented group to join!! Navigating PL takes a minute to get used to so i'll explain a little bit. 

The most active repo currently is plots2, which is the source code for PL's website publiclab.org. There we have a [pinned issue](https://github.com/publiclab/plots2/issues/4963) where we keep a list of users in need of FTOs and assign them out. 

The FTO you receive will not necessarily be for plots2. I post a bunch for this repo there. You can feel free to comment there, so we'll add your name to the list and you'll be randomly assigned to an FTO shortly. If you want one in this repo specifically you can skip that and I'm glad to just make you one!

**Comment by sashadev-sky** [comment]
@AdityaShD great! I think all you have left to do is:
1) `$ git push origin calculateAngle` to submit a pull request 
2) visit the [main repo](https://github.com/publiclab/Leaflet.DistortableImage) page on Github and you'll see a prompt to create your PR

Let me know if you have more questions :)

**Comment by sashadev-sky** [comment]
closed via #267
