### ISSUE TITLE
change rotate/distort icons in Toolbar when using hotkeys

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#27]
These are not updated when you use hotkeys

**Comment by sashadev-sky** [comment]
I fixed this in #187 but I thought it might be easier to just add the gif here because it's very small:

![hotkeys-fix](https://user-images.githubusercontent.com/41092741/55553226-a0494c80-56ad-11e9-8c95-b3af292a168f.gif)

**Comment by jywarren** [comment]
awesome!!!

**Comment by sashadev-sky** [comment]
closed via #187
