### ISSUE TITLE
New issue templates

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#290]
Hi, I made 3 issue templates for this repo using Github's new workflow - 🐛Bug report, 🧨Feature request, 📖Help with Leaflet.DistortableImage

Please click "new issue" and then select them further to see if you like them! They are all pretty similar but different. Let me know your opinions and improvement suggestions

**Comment by gauravano** [comment]
Done @sashadev-sky! #291 #292 #293

**Comment by sashadev-sky** [comment]
@gauravano thank you!! I didn't double space the bug report's template prompts like the rest. Feel free to open a PR for that to fix it if you think it helps readability! I already opened too many for this so I'm cutting myself off

**Comment by gauravano** [comment]
Will do @sashadev-sky. Thanks for all the great work!!

**Comment by sashadev-sky** [comment]
Spaced updated by @gauravano! Keeping this open until @jywarren gets a chance to look over them!
