### ISSUE TITLE
Add this feature..

### ISSUE THREAD

**Issue by gauravano** [publiclab/Leaflet.DistortableImage#292]
hello!!
**Please describe the desired behavior.**
Describe the solution you'd like.

Follow modular approach while building and ..

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.
:+1:

**Comment by gauravano** [comment]
How about having `feature` label too? @sashadev-sky

**Comment by sashadev-sky** [comment]
@gauravano would that be a totally new label across PL? I was thinking too they should be categorized when you go through issues in the same way they are categorized when you create them

**Comment by gauravano** [comment]
We use `new-feature` in Image sequencer and `feature` at plots2. We can settle on any one. What do you think?

**Comment by sashadev-sky** [comment]
@gauravano Oh ok cool! Either works! Would you want to open the PR for this I did too many . We can remove `discussion` and just do `feature` or `new-feature`?

**Comment by sashadev-sky** [comment]
@gauravano maybe the help template could be `discussion`  instead of `documentation`? wasn't sure what to go with

**Comment by gauravano** [comment]
How about `help-wanted` and `discussion` for Help template and `feature` for Feature template?

**Comment by sashadev-sky** [comment]
well `help-wanted` is when we need help not the other way around. But yes to the rest of that!

**Comment by gauravano** [comment]
If someone is filing an issue, asking a question and if the issue template is -- Help with Leaflet.DistortableImage, then I think, that user is asking for help? But, as you mentioned if it doesn't resonate perfectly then let's ignore it for now, and we can change anytime.

**Comment by sashadev-sky** [comment]
@gauravano yeah I don't know. I don't think we shouldnt automatically label it that. Because we tell 2nd time contributors to take those on, so we want to check them out first. And if its just answering a question then the user isn't really doing a 2nd time "help-wanted" issue. 

But I just merged your PR! So going to close this via #294
