### ISSUE TITLE
Resize image feature and keep image ratio (No distortion)

### ISSUE THREAD

**Issue by wawanopoulos** [publiclab/Leaflet.DistortableImage#298]
**Please describe the desired behavior.**
One missing feature to add in this plugin is the capability to resize the image and keeping the image ratio. (No distortion)
Today, this plugin offers only capability to play with the 4 corners of the image. Consequently, image ratio is not kept and the image is distordabled.

**Comment by flopail** [comment]
Hi @wawanopoulos, there is a Scale mode you can active with hotkey "S" after having selected image. This mode gives possibility to keep image ratio, but sometimes it bugs (see my recent issue #301). I hope it will help you.

**Comment by sashadev-sky** [comment]
Closing this one! Thanks @flopail 

We are working on updating documentation so the features are more obvious!
