### ISSUE TITLE
must click images first to select before dragging

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#30]
Preferred behavior is that you can just grab and drag images without 2 clicks.

This happens because the Draggable instantiation and initialization occurs on the same event as the selecting/enabling, and presumably _after_. Maybe some combination of firing events like .fire('mousedown') could help, but I don't understand how Leaflet's Draggable really works...

**Comment by sashadev-sky** [comment]
@jywarren my PR #158 has resolved this issue. 🎊🎊. Let me upload a GIF here for you

**Comment by sashadev-sky** [comment]
![bug3](https://user-images.githubusercontent.com/41092741/54598824-c0231400-4a0f-11e9-999c-b88ad4e900c3.gif)

Also thank so much for showing me Licecap!! It actually works. And has made my life so much easier

**Comment by jywarren** [comment]
Awesome!!!

**Comment by sashadev-sky** [comment]
closed via #158

**Comment by jywarren** [comment]
Hi! I wasn't able to see this working in the latest release's `select` demo - http://publiclab.github.io/Leaflet.DistortableImage/examples/select

But it does work in the main demo: http://publiclab.github.io/Leaflet.DistortableImage/examples/

Do we have to make a constructor settings change to enable this behavior? Just checking, thanks!

**Comment by sashadev-sky** [comment]
@jywarren this behavior is working for me in http://publiclab.github.io/Leaflet.DistortableImage/examples/select

see gif:
![selectdrag](https://user-images.githubusercontent.com/41092741/60890722-e6242c80-a229-11e9-85cc-eebd483e9f33.gif)

It's just the way it is implemented, it's not enabled through any option or anything like that. Perhaps maybe try it again?

**Comment by jywarren** [comment]
Confirmed this is fixed in MapKnitter! Thank you!!!!
