### ISSUE TITLE
Hotkeys don't work in Safari 9 and earlier

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#308]
We recently updated to the new `key` API as specified by WC3 but I see it's not working for Safari versions 9 and under. We may need to go back and implement fallbacks using the older API. Haven't checked where else won't work.

**Comment by sashadev-sky** [comment]
@rexagod @jywarren where do you see this on priority

**Comment by jywarren** [comment]
Thanks for this! I think low priority but MUCH appreciated!

**Comment by sashadev-sky** [comment]
Closing this its not really an issue
