### ISSUE TITLE
MultiExport follow-ups (just docs now)

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#316]
follow-ups to #314:

- [ ] show a spinner, and hide it when complete! **pending**: hide when completes
  - loader UI: considering for now just adding animated SVG loader icon to replace Export icon during load
- [x] prompt('Choose a scale in real-world centimeters per pixel, or click OK to use our best guess. Keep this window open to wait for your export to complete.', this._getAvgCmPerPixels()) (i think?) to prompt for a scale, but default to the average size?
- [x] open an issue for the "use the updated status_url value" which i tried to implement but it's not working. We should rejigger the section of code above that tries to match "complete" and the new JSON address. I think if we fix it, things will run a lot smoother!
- [x] and then MK integration!
- [ ] Move documentation from #310 in once figure out how to expose the `startExport` method or confirm working well enough for API exposure

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by jywarren** [comment]
Awesome! Also linking to https://github.com/publiclab/mapknitter/issues/756 `Insert custom updater function into Leaflet.DistortableImage for displaying export status`

**Comment by jywarren** [comment]
Linking from https://github.com/publiclab/Leaflet.DistortableImage/issues/203 too - looking great!

**Comment by jywarren** [comment]
We can check off Spinner too, but I'm actually not seeing it on http://mapknitter-stable.laboratoriopublico.org/maps/test6/edit -- do you know why? 

Aha - http://mapknitter-stable.laboratoriopublico.org/assets/leaflet-distortableimage/package.json currently shows `0.4.3` - let me update that!

**Comment by jywarren** [comment]
OK, I ran `sudo yarn install` and moved `/public/lib` so it should be defaulting to `/node_modules/`, but it's still showing `0.4.3`, so I'm going to restart the container to be sure it flushes any caching.

**Comment by jywarren** [comment]
Also deleted the `/assets/*` dir to get it to correctly show `0.7.7` - now it's showing correctly, so I'll restart the container again.

**Comment by jywarren** [comment]
We'll look here to test once it's rebuilt: http://mapknitter-stable.laboratoriopublico.org/maps/test6/edit

**Comment by jywarren** [comment]
Hmm. Error. Looking it up!

**Comment by jywarren** [comment]
Moving to https://github.com/publiclab/mapknitter/issues/1042 for unrelated issue...

**Comment by jywarren** [comment]
OK we are at `0.7.7` now in stable, so now, i think we need to stop overriding the default updater so that the new default (with the spinner) can start appearing? 

Ref: https://github.com/publiclab/Leaflet.DistortableImage/pull/385

**Comment by jywarren** [comment]
Now looking at #1124 to get this working with v0.8.7!

**Comment by jywarren** [comment]
Yay https://github.com/publiclab/mapknitter/pull/1126 !

We do need docs for this type of exporting, however!

**Comment by jywarren** [comment]
Especially for example how to switch between these two distinct cloud-based export systems:

* https://github.com/publiclab/image-sequencer-app
* https://github.com/publiclab/mapknitter-exporter/

**Comment by sashadev-sky** [comment]
@jywarren for now I opened https://github.com/publiclab/Leaflet.DistortableImage/issues/470

**Comment by jywarren** [comment]
Closing this in favor of https://github.com/publiclab/Leaflet.DistortableImage/issues/474 !
