### ISSUE TITLE
Move Exports and Delete into L.DistortableCollection namespace

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#317]
`Exports` and `Delete` are in the global namespace, and I think it's best we move them into `L.DistortableCollection` -- aren't they actions for `DistortableCollection`? maybe:

* `L.DistortableCollection.ExportAction`
* `L.DistortableCollection.DeleteAction`

https://github.com/publiclab/Leaflet.DistortableImage/blob/d9347144917d60c3cd81694c3f38131dc33f0902/src/edit/tools/DistortableImage.ControlBar.js#L24-L44

What do you think, @sashadev-sky ?

**Comment by sashadev-sky** [comment]
@jywarren I was thinking about this a bit! This would be a decision we would ultimately make for all the actions, the overlay ones too. 

I think we are going to have to expose them as a class if want them to be customizable. This would be the last piece to #161. I am also opening a PR next to make an `L.DistortableCollection.Edit` class to match the overlay API. (the editing functions will go there, functions having to do with the collection itself stay).

In that PR I will address the expose of actions too. I think they could all just be `L.EditAction.<ActionName>`? I was just worried that it is an overkill to make all of them their own class but is it the only solution?

**Comment by jywarren** [comment]
Hm, is it not possible to simply append them as properties of a namespace,
rather than fully-fledged classes themselves? Even `L.______` namespace is
available, although we'd want to name them something more specific like
`L.DistortableExportMultiple` maybe.

**Comment by sashadev-sky** [comment]
Going to close this one! Mostly have the actions down but still working on hashing it out. Some actions are indiscriminate for multiple or single images (Export and Delete). I explained this in one of the action files:

https://github.com/publiclab/Leaflet.DistortableImage/blob/d1cd4ff6ebf4763274d95f60335ca24e8f2ce051/src/edit/actions/DeleteAction.js#L6-L9

So they don't go under either cat. But the action `Lock`, for ex. had to be split into Lock and Unlock for the collection
