### ISSUE TITLE
Make locked images selectable

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#321]
This is important because for multiple image select, many images may be locked even as you're looking to export them. Let's make this change, and think through next steps:

If the lock icons still show, we should be OK, although perhaps we want to make groups unlockable. 

But if the lock handle icons (`X`s) /don't/ show, we may need to add that (not in the initial fix but in follow-up) so that it's clear why you can't drag the images together. That should resolve any ambiguities!

**Comment by jywarren** [comment]
@sashadev-sky if you're able to help untangle this one, that'd be awesome!

**Comment by sashadev-sky** [comment]
@jywarren ok let me try to make an "unlock all" action! Doing this now

**Comment by sashadev-sky** [comment]
"unlock selected group"***

**Comment by jywarren** [comment]
Ah, if it's possible, maybe preferable to leave them locked (even though
selected), as we may want to export even without deciding to unlock, so we
don't accidentally move them? Is that possible? Thanks!!!!

**Comment by sashadev-sky** [comment]
@jywarren yes I think I have implemented what you were requesting in #324! They can now be selected and exported while locked. In doing that I also added a sensible way to dealing with locking and unlocking groups. I think to make things the most clear, we should do similar to what I did for multi-delete and a message "you are exporting x num of images".
