### ISSUE TITLE
CSS selectors without class or id in v0.6.0

### ISSUE THREAD

**Issue by flopail** [publiclab/Leaflet.DistortableImage#330]
**Describe the bug:**
In leaflet.distortableimage.css, several CSS selectors include only HTML tags and no cleaner selectors such as class or id. As a result, these styles sometimes override other CSS styles you have in your app or website.

**Reproduce the behavior:**
Have a look to leaflet.distortableimage.css in dist folder, especially these CSS selectors: 
- svg
- td
- th
- kbd

**Browser, version, and operating system:**
- Browsers : Firefox 67, Chrome 75
- Leaflet DistortableImage v0.6.0
- Operating system: Windows 10

**Comment by jywarren** [comment]
Oh gosh, thanks for this catch! We'll issue a patch promptly. You don't
have one already created, do you? Just asking in case! Thanks again.

**Comment by flopail** [comment]
Hi @jywarren, no patch created on my side. Thanks!

**Comment by jywarren** [comment]
I /think/ this will work, although I want to double check with @sashadev-sky that the existing styles are preserved. You can point at that branch in the meantime if it's urgent, but I think we can get this resolved in a few hours. Thanks again!

https://github.com/publiclab/Leaflet.DistortableImage/pull/331

**Comment by sashadev-sky** [comment]
was `svg` overriding anything? I was thinking if we're mostly using `svg` for icons, then we should globally set it to 18px. Then in an instance where we don't want something to be 18px, we add more specific styling. Is this ok or do we not like this? I can add a comment above it in the css file explaining that?

**Comment by jywarren** [comment]
Ah well if this library is used in conjunction with any other code that has
an svg, the style would be applied to everything. We'd best namespace our
styles to avoid this! It's like using a global variable. Make sense?

**Comment by sashadev-sky** [comment]
@flopail all fixed :) thank you for reporting this!
