### ISSUE TITLE
Inline SVG

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#332]
We are currently using an external SVG sprite sheet to render our SVG's. In MK, this creates an issue with finding that external file because of some quirks with Rails asset path. 

To resolve this issue and ensure it doesn't happen in the future, I am thinking to just inline the SVG. 

This would be followed by a version bump and an attempt to reconnect back in MK and delete the extraneous overrwritten actions.

(And also relevant documentation updates ie. our wiki)

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by jywarren** [comment]
OK, this sounds good!
