### ISSUE TITLE
Refine `Lock` mode and update docs

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#333]
Currently, `lock` mode prevents image deletion and any movements (distort, rotateScale, drag), but `ToggleTransparency`, `ToggleOutline`, `ToggleOrder`, `Export` and `Restore` still work on a locked image. 
- @jywarren is it ok for me to open a PR to prevent these editing actions, except for `Export` in `lock`? - I can add doc that only Export and Exports is available for locked images. 
- alternatively I can update the doc to say that locked images can't be "moved" but can be "edited", but I think the former makes more sense?

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by jywarren** [comment]
Let's think of what would be the "destructive" actions we want to prevent
-- movement for sure, but so Restore as well? Transparency, export and
outline seem non-destructive, but i'm not sure about order. I guess if we
are saving order on the server (at some point soon) then it is destructive
too...

**Comment by sashadev-sky** [comment]
Ok this has been resolved organically throughout a bunch of PRs and is already documented, so closing! 

From the README:
> lock: Locks the image in place. Disables any user gestures, toolbar actions, or hotkeys that are not associated with mode. Exception: L.ExportAction will still be enabled.

@jywarren note how it says "not associated with mode". This is meaning when an image is locked, you can unlock it by toggling lock or by clicking any other mode. 

To make things even more clear, the new UI really shows you what you can and can't do in lock mode by greying out the icons that can't be clicked!

![image](https://user-images.githubusercontent.com/41092741/65288057-6e208f80-db13-11e9-8515-b1bcedab8fcc.png)
