### ISSUE TITLE
readOnly flag not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#351]
Our embed view has a `readOnly` flag in MapKnitter: 

https://mapknitter.org/embed/belle-isle-globe

But i think this flag got removed at some point. We should ensure the menus and handles are all inactive when this is set in the constructor. @sashadev-sky would you mind taking a look at this? Thanks a lot! 🙌 

```js
<script>
--
  | var map
  | (function(){
  | window.mapKnitter = new MapKnitter.Map({
  | latlng:     L.latLng(42.3432541, -82.9743495),
  | zoom:       14.0,
  | readOnly:   true,
  | logged_in:   true,
  | anonymous:   false,
  | warpablesUrl:   "/maps/belle-isle-globe/warpables.json"
  | });
  | })();
  | </script>
```

**Comment by sashadev-sky** [comment]
@jywarren how do I test this locally? (Where do I find embed view?) Is this bug new? (Came from my PR?) Should be quick to fix

**Comment by sashadev-sky** [comment]
This is probably best fixed in mapknitter to clean up that code

**Comment by jywarren** [comment]
I think some code may have been deleted, or maybe just a default? Trying to trace this... 

https://github.com/publiclab/Leaflet.DistortableImage/issues/13

**Comment by jywarren** [comment]
Yeah maybe you're right we implemented this in Mapknitter? We need to read through this code:

https://github.com/publiclab/mapknitter/blob/9299d74667032a64d6d1cfc2501dff3235cea1c3/app/assets/javascripts/mapknitter/Map.js#L126

I guess we could move this behavior into ldi and write a test for it... Let's look closer first though. Thanks!

**Comment by jywarren** [comment]
I think the integration with mapknitter is manually setting up the click handlers here. And we don't do it if it's got "readOnly" set.

https://github.com/publiclab/mapknitter/blob/9299d74667032a64d6d1cfc2501dff3235cea1c3/app/assets/javascripts/mapknitter/Map.js#L130

 Maybe we have to standardize how we connect or turn off click listeners?

**Comment by jywarren** [comment]
This example is supposed to show how event listeners can be set up. But maybe it's now out of date vs the docs?

https://github.com/publiclab/Leaflet.DistortableImage/blob/main/examples/listeners.html

**Comment by jywarren** [comment]
Also, i notice the locks are shown in embed mode. What changes in MapKnitter do we have to make to not show those? 

![image](https://user-images.githubusercontent.com/24359/61911232-6e7a2100-aefc-11e9-94ac-3c01519e1b00.png)

**Comment by sashadev-sky** [comment]
@jywarren For the locks,  I have been thinking that if a map is a `readOnly`, there could just be one lock somewhere on the map indicating the images are locked, we don't need the x's. And the x's are like "development mode" lock ie. when the user is  editing.

**Comment by sashadev-sky** [comment]
@jywarren readOnly problem is fixed! I see lock handles don't show in `readOnly` already so this should be fixed there too after merge! Check out #892 👍Sorry for that, I didn't know about this feature at the time

**Comment by jywarren** [comment]
Aha! Super rad! Thank you! Yes, we ought to document this feature more! I'll look today. Many thanks.

**Comment by sashadev-sky** [comment]
closed via https://github.com/publiclab/mapknitter/pull/892
