### ISSUE TITLE
When I rotate the image many times, it deforms

### ISSUE THREAD

**Issue by nielei19920921** [publiclab/Leaflet.DistortableImage#352]
**Describe the bug:**
When I rotate the image many times, it deforms.There is a quite similar issue #301,but is there a solution to the accuracy problem?

**Reproduce the behavior:**
 Figures 1 through 2
![img1](https://user-images.githubusercontent.com/27334643/61351885-83bcd300-a89e-11e9-8153-6e1909c8b3b6.jpg)
![img2](https://user-images.githubusercontent.com/27334643/61351887-84ee0000-a89e-11e9-860a-c3c19c8aea77.jpg)

**Browser, version, and operating system:**
Leaflet.DistortableImage v0.6.2
Chrome 71.0
Windows 10（64bits）

**Comment by themacboy** [comment]
I noticed the same. Actually the only solution is revert the image, with the toolbar function. Not sure if there is a trigger to do that from code.

**Comment by sashadev-sky** [comment]
@nielei19920921 @themacboy all scale and rotation distortions should be fixed in our newest release, 0.7.0. Try it and please feel free to re-open this issue if you discover any problems
