### ISSUE TITLE
Aftert unlock set mode is not acurate ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#360]
I have created a distortable element, by default I have set it to "rotate" mode (not scale permited) but after use lock/unlock it return to "scale" or "rotatescale" mode.

I suggest that it is very important to return to his original and default mode "rotate"

thx

**Comment by sashadev-sky** [comment]
@themacboy Thank you for reporting this bug! I've been meaning to fix that. We're on it.
