### ISSUE TITLE
How to trigger actions 

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#361]
I like to konw if it si possible to trigger any action (example: Revert, transparency, Delete, ...) and selected/unselected manually.

For example: 
When I need to export or print all map, I need to revert all elements and hide all distord visual and selection handlers. How can I revert and unselect all elements without using the mouse.

Is there any trigger function?

==================
- [x] select
- [x] unselect
- [ ] revert 
- [ ] transparency
- [ ] delete

**Comment by sashadev-sky** [comment]
@themacboy You would like to write your own code that does x, y, z on export or print and you would like the method names to use for doing so - am I understanding correctly? If you literally mean without the mouse we have keybindings too
