### ISSUE TITLE
Hotkeys should only be available for present toolbar actions

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#376]
PART 1: COMPLETE
For ex., if the developer doesn't add the `ToggleRotate` and `ToggleScale` actions, which are not in the toolbar by default, then we shouldn't be able to access them with their hotkeys. 

This would make more sense, and is also important for situations where a developer wants to forbid a certain action.

======= 

PART 2: PENDING
The only part left to resolve is how to make this work for the collection group. If you have one image that has scale in its toolbar, for ex, but another that doesnt, how do you make scale available on only one of them?

=======

**Comment by sashadev-sky** [comment]
@rexagod would you be interested in taking a try? 

I took a shot at writing a DRY implementation for this by moving all `keymap` / `Keyboard` event handling logic into `EditAction.js`. It worked but I got stuck on a bug (probably related to event propagation) and just scrapped the attempt.

**Comment by rexagod** [comment]
Hmm. I could look into that bug if you can push it here. Else, I'll just proceed from scratch. No worries, I'm good with either of these approaches.

**Comment by sashadev-sky** [comment]
@rexagod I just scrapped it. I have been finding a lot of the time for this library that bugs just mean my implementation idea is no good

**Comment by sashadev-sky** [comment]
@rexagod see pt 2 above! Any ideas?

**Comment by sashadev-sky** [comment]
heres the main issue: if the first image you click on doesn't have the tool, then the keybinding won't fire. But, if the next image you click on does have it, then the keybinding will fire for it and when you click back on the first image the keybinding will now fire for it too @rexagod

**Comment by sashadev-sky** [comment]
an alternative solution I would also think is good (maybe better) is making it so that when there's a collection, any tools you limit / specify on one image will be the tools on all of them. I can't think of many use cases where one image needs an action where others don't. This will also involve some complicated structural changes, though, I think

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by jywarren** [comment]
Ah, interesting - so we're looking at any collection having the "lowest common number of tools" based on the collection member that has the fewest tools? Kind of a venn diagram of the tools which are available on ALL collection member images?

**Comment by sashadev-sky** [comment]
@jywarren hotkeys problem is fixed and ready for review in #393 :)
but yes looking foward we need to think critically about how we will proceed. Very cool that were still sticking with the multi-toolbar idea - its been awesome thinking up ideas how to turn it into a functional UI / UX / API  🙌🏻
