### ISSUE TITLE
get Toolbar to continue to appear on Firefox Android and Chrome Android after deselecting and re-selecting an image

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#38]
Toolbars are not showing after the first image on Firefox Android, and Chrome Android. To reproduce:
1. [open example](http://publiclab.github.io/Leaflet.DistortableImage/examples/select.html) in FF or Chrome, both on Android
2. click on an unlocked image, see Toolbar appear
3. click on the image again in a different spot, see Toolbar disappear and reappear in new mouse location (correct behavior)
4. click on another image
5. click on the original image again, see Toolbar appear
6. click on the image again in a different spot, but Toolbar does not move or reappear

Step 6 can also be done by moving the image and trying to get the Toolbar to reappear. This bug can be circumvented by clicking another image and then clicking the first image again; Toolbar appears on first click, but not on subsequent ones. 

Leaflet events reference: http://leafletjs.com/reference.html#events

Key observations: 
- this only affects **unlocked** images. But I've found it hard to monitor attached events on a mobile device, and the bug does not appear on a desktop browser
- this occurs for touch or mouse click events; I plugged a mouse into my Android phone and found the same behavior
- no other events (dblclick, for example) attached appear to be triggered anymore after the first time the Toolbar appears (i.e. after step 5 above)
- originally, the Toolbar did not appear at all after step 4 above, but [changing this line](https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/edit/DistortableImage.Edit.js#L61) to use `L.DomEvent.on()` instead of `overlay.on()` got the initial selection click to trigger Toolbar appearance.

**Comment by jywarren** [comment]
Key observation: this only affects **unlocked** images. Check stopPropagation calls!!!

**Comment by sashadev-sky** [comment]
@jywarren what tool can I use to this from a Mac?

**Comment by sashadev-sky** [comment]
The toolbar doesn't update locations based on the location of mouse click anymore, so I think this can be closed! But managing DOM events for this library has been a source of bugs to this day for sure.

Tested in Chrome on Android just in case:
![android-chrome-test](https://user-images.githubusercontent.com/41092741/56179635-73156c00-5fd4-11e9-8620-77d68dbe777b.gif)

**Comment by sashadev-sky** [comment]
and firefox (note browser stack is very slow): 
![android-ff-test](https://user-images.githubusercontent.com/41092741/56179845-2d0cd800-5fd5-11e9-9a62-3894af5cc825.gif)

**Comment by jywarren** [comment]
Great!!!
