### ISSUE TITLE
Disable mouse pointer on disabled images

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#382]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Problem

We can disable image editing using `img.editing.disable()`, meaning it will be non-interactive until re-enabled again (`img.editing.enable()`), but the mouse pointer is not updated to differentiate this visually to the user. 

See how its still the 'hand grabbing' pointer:

![ex](https://user-images.githubusercontent.com/41092741/64925475-04c11980-d7bf-11e9-8ac9-a63f06d14d5a.gif)

# Solution

The `DistortableImage.Edit.js` file holds the handler class that wraps the image overlay and allows us to interact with it. You will find there two methods `addHooks` and `removeHooks`, that are called when you `enable` and `disable` editing, respectively. 

- [ ] We can use these to add a css class to the image, `disabled`, in the `removeHooks` and remove that class in the `addHooks`.

Here's the leaflet way to do this: - note that `overlay.getElement()` returns the HTMLImageInstance
```JS
 L.DomUtil.addClass(overlay.getElement(), 'disabled');
```

- [ ] in our css file `leaflet.distortableimage.css`, we already have the relevant selector written out to add the pointer events: https://github.com/publiclab/Leaflet.DistortableImage/blob/d1cd4ff6ebf4763274d95f60335ca24e8f2ce051/dist/leaflet.distortableimage.css#L1-L3

just write this selector again but this time with an `img.disabled` at the end. (We keep very specific selectors bc this library is meant to be used by others and we don't want to overrwrite their css). Inside, set a declaration   `cursor: default`.

- [ ] double check how the cursor looks when you hover over the image after disabling it, and then also after re-enabling it.

**Comment by sashadev-sky** [comment]
@ViditChitkara @rexagod @jywarren

**Comment by rexagod** [comment]
Should we scoop this in the milestone?

**Comment by sashadev-sky** [comment]
Sure! @rexagod lol glad we keep opening new issues for ourselves to solve for the milestone

**Comment by sashadev-sky** [comment]
this one should honestly take like 2 minutes I was just too tired to do it on the last PR

**Comment by debck** [comment]
**Uploaded to Dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by sashadev-sky** [comment]
@debck @SidharthBansal why did we make this a medium level issue? Its a 1-line code change and I give the answer
