### ISSUE TITLE
Remove try...catch from _addToolbar

### ISSUE THREAD

**Issue by rexagod** [publiclab/Leaflet.DistortableImage#383]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

# Problem

We would like to remove an unnecessary `try...catch` block from our code.

# Solution

 Remove the `try...catch` around the toolbar adding logic from the `#_addToolbar` method found here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/af4bea824707298cc47739b14c5f0d7f57228910/src/edit/DistortableImage.Edit.js#L536-L542

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention @rexagod & @sashadev-sky for a review.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by rexagod** [comment]
cc @sashadev-sky

**Comment by rexagod** [comment]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** In this one, we need you to remove the try catch blocks and instead add a check before the try block to see if `this` object has `toolbar` property present in its `Object,keys` output.
https://github.com/publiclab/Leaflet.DistortableImage/blob/4a4496f296a49698fe74dd2a08eaf08804efd5f0/src/edit/DistortableCollection.Edit.js#L277-L286
 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)


### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by BrooksPatola** [comment]
may i have a go at this?

**Comment by sashadev-sky** [comment]
@BrooksPatola yes go for it! Thanks :)

**Comment by fgkolf** [comment]
I will have a try on this since it seem unassigned

**Comment by sashadev-sky** [comment]
@fgkolf it looks like you abandoned this one. Did you get stuck anywhere / need help?  This one is now up for GCI students only but I could make a new one for your if you'd like!

**Comment by sashadev-sky** [comment]
**Uploaded to GCI Dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by alexbertis** [comment]
Hi! I would like to claim this issue

**Comment by sashadev-sky** [comment]
@alexbertis this one is reserved for GCI, are you a GCI student? If not I can open a different one for you :)

**Comment by alexbertis** [comment]
Yep, I am a GCI student (alias alexberti02)

**Comment by SidharthBansal** [comment]
Go for it

**Comment by alexbertis** [comment]
I submitted the task a couple of days ago... Could you please review it? Thank you very much.

**Comment by sashadev-sky** [comment]
So sorry! I have a fulltime job and sometimes when a new feature has to come out I need to give that prtiority. Anyway i will review now :)
