### ISSUE TITLE
Document and finalize standardized code formatting

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#389]
as a follow up to #378, I wanted to confirm some straggling syntaxes still not sure about, and also just document our code syntax in a wiki maybe (eventually we can make a `contributing.md`) 

So far the standard we will implement is:
- [x] 2 space indent
- [x] single quotes
- [x] space in blocks, no space in objects
<blockquote>Yep. Makes sense. You see, { return; } qualifies as code, or more specifically a block of code that runs (executes one line per session by the intepreter), whereas { deselect: true } is not the same but an object, and is interpreted in one go, unlike some block of code, hence the rules for both differ.</blockquote>

- [x] column limit: 80 recommended. No column limit on comments but be reasonable
- [x] No space before parentheses:  `function() {}`
- [x] no comma after var declaration style
- [x] trailing commas for objects
- [ ] camelCase variables

Pending:
- [ ] comment syntax

**Comment by sashadev-sky** [comment]
@rexagod I was curious about: 

```JS
    if (!this._moved) {
      return;
    }
```

Sometimes we will see the above syntax, sometimes we will see:
```JS
    if (!this._moved) { return; }
``` 

Is there a linter we can add that keeps it on the same line unless the line goes over length limit, and in that case goes to a new line? Is this something we want? Also what is the current line length limit that is set?

**Comment by sashadev-sky** [comment]
Ok I added 3 configs:
```JS
        "curly": ["error", "multi-line"],
        "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
        "block-spacing": ["error", "always"],
```
that basically allow `if (!this._moved) { return; }` in terms of having the return on the same line and spaces in between the braces and the return.

It does not allow spaces in between objects still: so `map.fire('singleclick', {deselect: true});` is ok but `map.fire('singleclick', { deselect: true });` is not.

let me know what you think!

**Comment by rexagod** [comment]
Yep. Makes sense. You see, `{ return; }` qualifies as _code_, or more specifically a **block** of code that runs (executes one line per session by the intepreter), whereas `{ deselect: true }` is not the same but an object, and is interpreted in one go, unlike some block of code, hence the rules for both differ.

Maybe https://eslint.org/docs/rules/object-curly-spacing could help here?

**Comment by sashadev-sky** [comment]
what are your thoughts on the var? (last point). Google says no to the one declaration followed by comma syntax. I kind of like how it looks compared to doing something like what we currently have:
```JS
rotateBy: function(angle) {
    var map = this._map;
    var center = map.project(this.getCenter());
    var corners = {0: '', 1: '', 2: '', 3: ''};
    var i;
    var p;
    var q;

    for (i = 0; i < 4; i++) {
      p = map.project(this.getCorner(i)).subtract(center);
      q = L.point(
          Math.cos(angle) * p.x - Math.sin(angle) * p.y,
          Math.sin(angle) * p.x + Math.cos(angle) * p.y
      );
      corners[i] = map.unproject(q.add(center));
    }

    this.setCorners(corners);

    // window.angle = L.TrigUtil.radiansToDegrees(angle);

    this.rotation -= L.TrigUtil.radiansToDegrees(angle);

    return this;
  },
```
I thought also it was pretty standard to do that in ES6, like with object destructuring too for ex. honestly just curious

**Comment by sashadev-sky** [comment]
@rexagod prepared to get this serious about our style guide?

<blockquote>This Style Guide uses RFC 2119 terminology when using the phrases must, must not, should, should not, and may. The terms prefer and avoid correspond to should and should not, respectively. Imperative and declarative statements are prescriptive and correspond to must.</blockquote>

**Comment by rexagod** [comment]
Haha. I am, but the question is, will the first timers be okay with this standard? Also, I agree with the no comma after var declaration style, looks more cleaner to me. So +1 for that!

**Comment by sashadev-sky** [comment]
@rexagod the block of vars look cleaner to you you’re saying?

I felt the opposite, but I can see your perspective too and functionally it is actually cleaner. So +1 from me too

**Comment by sashadev-sky** [comment]
@rexagod up next: trailing commas? We don't do that at all, but I'm kinda with it. Makes sense functionally. Thoughts?

**Comment by sashadev-sky** [comment]
@jywarren looping in

**Comment by rexagod** [comment]
Trailing commas? Sorry, can you provide an example of those?

**Comment by sashadev-sky** [comment]
like commas on the last key value pairs in objects and after the last method in the class. Even though nothing follows it. Makes it easier to add new methods

**Comment by rexagod** [comment]
Oh. Those! Yeah they definitely do, all good from me!

**Comment by sashadev-sky** [comment]
ok last one (for now): 
Leaflet always puts a space before parentheses in function declarations like `function () { }`

Do you have any opinions on this one? I kinda think `function() { }` is more standard right?

**Comment by rexagod** [comment]
I'm glad to see that we're working on such minute levels, kudos to your
research! Hmm. I guess `function() {}` is standard, but since this is a
Leaflet library after all, maybe `function () {}` should be our choice? I'm
+1 with whatever decision you make here.

Pranshu Srivastava | @rexagod

**Comment by jywarren** [comment]
Just a note on "function() {}" vs "function () {}" -- actually "function
someDescriptiveName() {}" is really helpful for debugging as it shows up
better in the console, which would also answer the question of whether the
space is required (in that case, yes!). What do you think?

**Comment by jywarren** [comment]
Oh no, sorry i mean having the function named instead of anonymous is
better for debugging. But adding a function name then means you must have a
space -- like, function myFunctionName(). Oh, i see -- yeah, well, no space
between the function name and the (). But yes between the word function and
myFunctionName. Sorry, i didn't think of that way of reading it! Thank you!

**Comment by rexagod** [comment]
I'm all +1 for named functions as well, they are way more distinguishable in the error stack trace, hence better debugging!

**Comment by rexagod** [comment]
Okay so it seems we'll be going ahead with no spaces, right?

**Comment by sashadev-sky** [comment]
@rexagod yes!

**Comment by sashadev-sky** [comment]
@rexagod @jywarren ok i think this is last! Comments -
should we say 

1. 
```JS
// this one is for a one-liner on its own line
```

2.
```JS
return exampleCode; /* this one is for a one-liner that is inline with the code */
```

3.
```
/**
 * this is a multi-line comment block
 * it is integrated with JSDoc - JSDoc comment snippet is suggested after typing `/**`
 * guessing its personal config but if we start using JSDoc later, can suggest ppl integrate that
 */
```

4.
```
// this is fine too
// for multi-line comments
```

5. 
I set Max Length for comments to be ignored: `"max-len": ["warn", { "ignoreComments": true }]`
Agree / Disagree? Should we compromise for instead a more lenient max length for comments or does this just really not matter? I just don't like the way comments will span over more lines and take up more space following the current max length of 80.

6. 
For JSDoc commenting, for now maybe lets hold off on that until we get our code standard and then reopen the issue later as part of a 'standardizing documentation' discussion?
   - `"valid-jsdoc": 2` is in `.eslintrc.js` but has been deprecated as of ESLint v5.10.0 (we are on 6.1.0) so either way lets change to `"valid-jsdoc": 0`? 
   - getting errors for  `eslint(require-jsdoc)` even though its also deprecated and not even included under rules in `.eslintrc.js`. So let's add `"require-jsdoc": 0?
   - `eslint-plugin-jsdoc` suggested by eslint instead in [deprecation notice](https://eslint.org/blog/2018/11/jsdoc-end-of-life). we can install when decide we want to start jsdocing?
