### ISSUE TITLE
long press (touch) to unlock, switch modes

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#39]
"contextmenu" event: http://leafletjs.com/reference.html

**Comment by sashadev-sky** [comment]
@jywarren did you want this to be just for mobile? Otherwise it also fires on right click

**Comment by jywarren** [comment]
Sometimes I think I've seen long press be the equivalent of right click so
there's similarity across desktop/mobile. What if we adopt that convention?
