### ISSUE TITLE
Revert Bug / Restore idea branchout

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#396]
Two issues with the revert action:

1) It returns the image back to its natural proportions (the proportions it would have if we added it to the map without specifying corners) - @jywarren perhaps this is actually something we may want and not a bug? But it looks awkward as part of the revert tool. So I say maybe let's fix the revert tool to revert to the proportions set out by the `corners` if given.

and for a part 2, add a new tool `restore` that restores the images back to its natural measurements?

2) each time revert is pressed the image is moved slightly southeast of what it was originally, even though all other aspects are reverted correctly

**Comment by jywarren** [comment]
Oh, sorry - yes, the revert tool is intended to return an image to it's "natural" proportions, yes! Not to it's previous position -- that is handled in the image versioning Divya did in MapKnitter! So, it's not an "undo" but a "revert to original". Does that make sense? 

Would your proposal then have more like a version history sort of? We'd want to reconcile it in some way with the version tracking Divya implemented in MapKnitter! Thanks!
