### ISSUE TITLE
Cleaning up!

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#397]
- Demo is perfect as is, just thinking we could recreate it with the new toolbar interface
- Also thinking to get a Demo gif added for multi-image interface
- but both of these are lower priority than getting out github pages demo where it should be -
   - [x] Update gh-pages
   - [ ] aerial images
   - [ ] one for `index.html`, and a compilation that fit together would be nice for `select.html`
   - [ ] fix the export links
   - [ ] Make a new GIF demo / screenshot for readme

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by rexagod** [comment]
Uploaded to GCI dashboard

**Comment by SidharthBansal** [comment]
Published

**Comment by jywarren** [comment]
I know this is old, but just noting agreement here! I also pinned a couple bigger features which we might be able to tackle now that so much progress has been made in this library over the past year and more. Tremendous job, everyone!
