### ISSUE TITLE
Hide lock Xs when not selected?

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#398]
This may need some discussion, but I noticed that on initial page load, there are a LOT of Xs:

![image](https://user-images.githubusercontent.com/24359/63441234-16e9ab00-c3ff-11e9-8c3b-0d2c370eb801.png)

We could do 2 things:

1. we could hide Xs on the read-only mode, so they wouldn't appear on a page like this: https://publiclab.org/wiki/one-cranston (in embed mode)
2. we could go further and say the Xs should only appear when the image is selected

Thoughts from others on this? I don't know the best solution, just trying to describe the issue well. Thanks!

**Comment by jywarren** [comment]
cc #25 https://github.com/publiclab/Leaflet.DistortableImage/issues/28

**Comment by sashadev-sky** [comment]
@jywarren I dont remember where I posted this, but I suggested a 'photo-ready' mode or something of the sort that would be an action given to the collection group only. It will make all the images disabled for editing using `img.editing.disable` and the x's will be gone. let me know if you want me to open up an issue for this. and get it down

**Comment by sashadev-sky** [comment]
Re: Hide X's in the read-only mode is a definite yes. I will look into that as I am working on mapknitter and open an issue for that in MK

**Comment by sashadev-sky** [comment]
Re: X's only when selected. agreed. will open up an issue for that here. Realized there is really no reason that its the only mode we keep showing.

**Comment by sashadev-sky** [comment]
closed via #586
