### ISSUE TITLE
Hide lock Xs when not selected

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#400]
Suggested by Jeff from #398 

"we could go further and say the Xs should only appear when the image is selected"

I think lets implement this here! 

@rexagod thoughts?

**Comment by rexagod** [comment]
+1. This would incorporate the same logic we use for other (distort, scale, etc.) markers, for the lock marker, I guess.

**Comment by sashadev-sky** [comment]
closed via #586

**Comment by sashadev-sky** [comment]
closed via #586
