### ISSUE TITLE
Strange behavior on map edges

### ISSUE THREAD

**Issue by adriankwiat** [publiclab/Leaflet.DistortableImage#402]
**Describe the bug:**
What happened vs. what did you expect to happen?

When image is scaled above map edges it expand on the sides.
When is moved beyond the edges it behaves strangely.

Expected: image stops scaling/moving when it touches borders or scales/moves normally.

![1](https://user-images.githubusercontent.com/36125672/63524685-bc367900-c4fc-11e9-8f08-1bf9a5f9f38e.gif)
![2](https://user-images.githubusercontent.com/36125672/63525312-c5741580-c4fd-11e9-9503-6e67e9621636.gif)
![4](https://user-images.githubusercontent.com/36125672/63530130-269fe700-c506-11e9-9fd2-4438a6773c6e.gif)

**Reproduce the behavior:**
 Steps to reproduce the behavior. (ex. 1. Go to... 2. Click on... 3. See error...)

You can see this behavior here:
https://jsfiddle.net/adriankwiat/fz9vbghq/33/

**Browser, version, and operating system:**
 - Browser [e.g. chrome, safari] -
 - Version [e.g. 22] -
 - Platform: [e.g. iOS, windows] -

**Comment by sashadev-sky** [comment]
@adriankwiat just when we thought we got scaling down 😂I'm guessing its due to projection distortions being the most extreme near the poles
@jywarren @rexagod

**Comment by rexagod** [comment]
One approach we could take to avoid such cases in the future is a fool-proof implementation that guarantees the markers never leave the image element. Maybe something like checking if the image and markers move accordingly at each 'drag' event? @sashadev-sky WDYT?

**Comment by sashadev-sky** [comment]
@rexagod I don't think thats the root of the issue. Its a little confusing but we update the corners and then we fire an update to the markers to go where the corners are placed (accoridng to latlng). So if the markers ever diverge from the corners, it means that the latlng were passing to them doesnt actually reflect where the image corners are - our distortion functions are off in some way.

**Comment by sashadev-sky** [comment]
I cant trace the cause back to any specific function yet - just dragging the image over to the edges starts distorting it regardless of what mode its in

**Comment by sashadev-sky** [comment]
Ok I can confirm now this is because of the way we overwrote `L.Draggable._updatePosition`

**Comment by sashadev-sky** [comment]
@adriankwiat updated and published 0.7.8 to npm for ya :)
