### ISSUE TITLE
Remove redundant images

### ISSUE THREAD

**Issue by rexagod** [publiclab/Leaflet.DistortableImage#408]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** All you need to do here is remove all the redundant images from https://github.com/publiclab/Leaflet.DistortableImage/tree/main/examples that aren't being used inside any file. A simple search of an image will help you narrow this down.
 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by rexagod** [comment]
I actually meant searching the whole codebase for any redundant images. Are
you familiar with doing a `cat` and `grep`ing the unwanted images?

Pranshu Srivastava | @rexagod

**Comment by galvc** [comment]
Yes! I was able to do that on the entire Leaflet.DistortableImage directory and found
examples/large.jpg - used
examples/example.jpg - used
examples/example.png
example.png in main folder - is not used
examples/example_.png - is not used

Which means I would have to remove example.png and examples/example_.png. 
Though the directions only said to remove unused images from the examples folder, so I will only be removing example_.png. Please correct me if I'm wrong.

**Comment by rexagod** [comment]
@galvc Sorry for the confusion! Please go ahead and remove both of them.
Nice work!

Also, you can find some more advanced issues to work on after this one in
the issues section you can always ping me or @sashadev-sky if there's
anything we can help with.

Pranshu Srivastava | @rexagod

**Comment by galvc** [comment]
@rexagod Submitted my first PR. Thanks for the opportunity and will continue to contribute. Thanks so much!
