### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by rexagod** [publiclab/Leaflet.DistortableImage#409]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** This one's interesting. We need you to make a break the css file inside the dist folder currently into smaller, more specific ones, which could be parts of different components, for eg., `L.DistorableImage.Keymapper` (file name) would contain all the styles that are currently inside the dist/*.css file that style the keymapper. Remember to change paths and also update the `Gruntfile.js`!
 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by sowmiyamuthuraman** [comment]
Hi! I would like to work on this.

**Comment by sashadev-sky** [comment]
@jywarren is this how we would want to proceed? I think perhaps before breaking up the css we should start with getting the css out of the `dist` folder?

**Comment by the-kaustubh** [comment]
@sowmiyamuthuraman have you opened a PR? I am thinking of contributing here, too.
If you have not opened a PR please notify.

**Comment by DylPickle11** [comment]
Is this still open? I would like to help work on this.

**Comment by skathuria29** [comment]
I would like to work on this issue. Is it still open?

**Comment by sashadev-sky** [comment]
Hi guys! I'm sorry but I don't think we'll be moving forward with this issue. -- anyhow, its been a little quiet on this repo for a while but hoping to start back up again this week so you should see some new FTO issues!
