### ISSUE TITLE
Generalize tests

### ISSUE THREAD

**Issue by rexagod** [publiclab/Leaflet.DistortableImage#410]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** In this one, you need to check if there's anything repetitive inside https://github.com/publiclab/Leaflet.DistortableImage/tree/main/test/src files and append the section of code to the `chai` runner object and replace that part of the code in different files with `chai.<your fn name>` as done below.

https://github.com/publiclab/Leaflet.DistortableImage/blob/4a4496f296a49698fe74dd2a08eaf08804efd5f0/test/SpecHelper.js#L14

https://github.com/publiclab/Leaflet.DistortableImage/blob/4a4496f296a49698fe74dd2a08eaf08804efd5f0/test/src/DistortableCollectionSpec.js#L66
 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Sri-V** [comment]
Hey folks, we are pretty new to OSS and planning to give this is a try.

**Comment by rexagod** [comment]
Please do! Thanks!

Pranshu Srivastava | @rexagod

**Comment by sashadev-sky** [comment]
@rexagod to add on to this, I think these three can be simplified into one function that takes options:

https://github.com/publiclab/Leaflet.DistortableImage/blob/2640118d1654a8d05e46de2ad46d0cd5499e9297/test/SpecHelper.js#L14-L36

**Comment by rexagod** [comment]
Including this too, awesome!

**Comment by sashadev-sky** [comment]
@rexagod after #417 is merged I think we could close this and instead for FTO's, open up ones with specific changes described like we usually do?

Otherwise we can reopen as an issue with `help wanted` and  `fto-candidate` that can be broken out into FTOs
