### ISSUE TITLE
Image handles still active when hidden

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#429]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## Problem

**What happens:**

Hidden handles remain [interactive](https://leafletjs.com/reference-1.5.0.html#interactive-layer)  (clickable, draggable, etc.), creating a bug where if the user clicks an image at a place where it overlaps another image's hidden handle, they will not be able to drag the image around. (it will appear stuck).

Here is a gif demonstrating the problem: ![kkk](https://user-images.githubusercontent.com/41092741/64922986-565bab00-d7a3-11e9-859b-13df8e25baf7.gif)

You can also find two excellent examples of the mouse event propagation demonstrated in the comments below by @themacboy.

**What's supposed to happen:**
The selected image should be draggable.

## Solution

The bug happens because moues events on the overlapping image are propagated down to the hidden handle. To prevent this, the image's handles should to stop being interactive when they are hidden.

There are two methods handling the showing and hiding of the image handles:

https://github.com/publiclab/Leaflet.DistortableImage/blob/22cf32253e8030f52ba0620ed33d12a5149766da/src/edit/DistortableImage.Edit.js#L454-L488

**Step 1:**

A simple Leaflet way to make a DOM element non-interactive is to remove the `leaflet-interactive` class from it. We can do that for our handles like this:

```JS
 L.DomUtil.removeClass(layer._icon, 'leaflet-interactive');
```

In `_hideMarkers`, inside the conditional checking if the `mode` is not `lock` (`if (m !== 'lock')`),
add that line right after the handle icon opacity is set to 0 to disable interactivity.

**Step 2:**

In `_showMarkers`, there is no conditional, but similarly we should re-enable interactivity right after the opacity on the handle icon is set back to 1 by adding ` L.DomUtil.addClass(layer._icon, 'leaflet-interactive')`;

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
2n. I think that when you click over a handler there is neede an event stopPropagation to avoid undesired event activation on other elements. --- what undesired event activation on other elements are you referring to specifically? I cannot recreate this problem

**Comment by sashadev-sky** [comment]
Oh i see. You mean like this for ex: ?
![kkk](https://user-images.githubusercontent.com/41092741/64922986-565bab00-d7a3-11e9-859b-13df8e25baf7.gif)

**Comment by sashadev-sky** [comment]
@themacboy I have resolved this, but I will be mentoring for Google Code-In this year and I think it will be a good first-timer issue for a GCI participant to resolve. Is this something you personally need fixed for your project? Opening for GCI means it will probably be here for a month or so

**Comment by themacboy** [comment]
> 
> 
> @themacboy I have resolved this, but I will be mentoring for Google Code-In this year and I think it will be a good first-timer issue for a GCI participant to resolve. Is this something you personally need fixed for your project? Opening for GCI means it will probably be here for a month or so

Im not sure to understand what is "mentoring for Google Code-In", but obviously I am at your disposal to help you as much as you can.

**Comment by themacboy** [comment]
> 
> 
> 2n. I think that when you click over a handler there is neede an event stopPropagation to avoid undesired event activation on other elements. --- what undesired event activation on other elements are you referring to specifically? I cannot recreate this problem

Here a undesired event propagation:

![2019-09-16-06-58-32](https://user-images.githubusercontent.com/8063711/64935143-b7d95380-d84f-11e9-8fff-83a94c847360.gif)

**Comment by themacboy** [comment]
And now a example of active handler when element is unselected:

![2019-09-16-07-04-21](https://user-images.githubusercontent.com/8063711/64935268-9167e800-d850-11e9-82ac-cd6b3a6e2ad6.gif)

**Comment by sashadev-sky** [comment]
@themacboy It is an annual mentoring program where students complete open source tasks on github assigned to them. So I was asking if this bug needs to be resolved now (is inconvenient for you) or we can wait for the program to start (about a month)

**Comment by themacboy** [comment]
> 
> 
> @themacboy It is an annual mentoring program where students complete open source tasks on github assigned to them. So I was asking if this bug needs to be resolved now (is inconvenient for you) or we can wait for the program to start (about a month)

can wait ! no problem hehehe do you best on Google Code-in !!!

**Comment by sashadev-sky** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
**Published on GCI Dashboard**

**Comment by Alexjake660** [comment]
Is this issue open?

**Comment by sashadev-sky** [comment]
@Alexjake660 it ended up falling into a bigger PR I made #586 so I completed it. I can assign you to a new FTO if you're interested!

**Comment by Alexjake660** [comment]
@sashadev-sky I'm interested, thank you.

**Comment by sashadev-sky** [comment]
@Alexjake660 ok great i just assigned you to #596
