### ISSUE TITLE
Colorize action ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#436]
Good morning, 

for my personal project I will need a colorize function to change the color in the svg elements.

First I was thinking to build a separate function in my code or build a new plug-in, but now that I looked all the work done to rebuild the distortableimage API and the toolbar and his actions, I was thinking to create a new action to change color.

My idea is to build a action/toolbar with a contexmenu with a list of (X) colors, If you choose any of them a css filter will be applied over the svg image (I supose that can work over any image hehehe but im not really skilled in this things, yet !).

In future versions, probably I will try to add a more complete color maker.

The question is ... do you think it is a good complement for your plug-in, or you prefer I code that out of Distortable Image? ;)

Example:

![imatge](https://user-images.githubusercontent.com/8063711/65302227-c8a10680-db7a-11e9-9cc6-2c2cd4528673.png)

**Comment by sashadev-sky** [comment]
Hi! I can't justify a need for such a tool in this library, but our toolbar API comes with a built-in subtoolbar ability - https://github.com/Leaflet/Leaflet.toolbar/blob/master/examples/subtoolbar.html

basically like: 

```JS
   subToolbar: new L.Toolbar2({ 
              actions: [World, Eiffel, Cancel]
    })
```
if you would want to use that

**Comment by themacboy** [comment]
ok, will check all that.

A lot of thank's !
