### ISSUE TITLE
Can't select after hide the layerGroup ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#440]
Hello !

Still getting the unselectable problem. After hide and show the layerGroup I can't select again my image:

![2019-09-23-09-17-22](https://user-images.githubusercontent.com/8063711/65407871-27b58400-dde4-11e9-9ab4-4eda0e822889.gif)

My image is added to a normal layerGroup, and I use it to hide or show a diferent types of elements (cars, bikes, motorbikes, bus, etc in one layer, traffice sings in other, etc)

Ah! And no error in console. Is like the event listener is lost. (not sure how to check)

**Comment by sashadev-sky** [comment]
please see my comment here! https://github.com/publiclab/Leaflet.DistortableImage/pull/444#issuecomment-562910686
