### ISSUE TITLE
>Deleted images come back, but not actives ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#441]
Hello,

After deleting a image used inside a layerGroup, the image come back if you hide and show this layerGroup. But it is not possible to select.

I supose that has some relation with issue #440, probably the solution is the same.

![2019-09-23-10-02-12](https://user-images.githubusercontent.com/8063711/65410123-d0b2ad80-dde9-11e9-95f9-61e0ad996afb.gif)

**Comment by themacboy** [comment]
I supose that image is not totally removed from DOM, and it still refered in the layerGroup.

**Comment by sashadev-sky** [comment]
Hi! can you please make a PR, with a simple demo of this problem in an html file in the `debug` folder. Perhaps call it like `layerControl.html`. So I can examine thee issue and solve it. Because with no physical code or familiarity with the code your using it will just be a guessing game
