### ISSUE TITLE
Difficulty moving images at high zoom levels

### ISSUE THREAD

**Issue by rmhorne** [publiclab/Leaflet.DistortableImage#446]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

First, this is a great project! However,I seem to have hit a weird error: When using the demo (https://publiclab.github.io/Leaflet.DistortableImage/examples/index.html) everything works as expected. However, when I built the code using npm and tried the same example file on my local machine (mac os running apache), the image becomes very sluggish to move at high zooms until it simply refuses to move at all. This seems to be the case as soon as the corners are no longer all within the viewable area of the image.

I am using the same browser (chrome) to view the pages, the javascript console is not throwing any errors, and the code is unchanged from the example. Again, the hosted demo page works great, but for some reason the zoom issue is happening on a local install.

**Comment by rmhorne** [comment]
Hosted behavior:
![hosted](https://user-images.githubusercontent.com/3486040/65838050-ac584480-e2b3-11e9-9bd6-71cf671da279.gif)

Localhost behavior:

![local](https://user-images.githubusercontent.com/3486040/65838076-f17c7680-e2b3-11e9-8a86-e83f00d55b44.gif)

**Comment by jywarren** [comment]
Oh, interesting! And great documentation! Sorry you're having this issue --
are there any console errors appearing? Any missing source files?

**Comment by rexagod** [comment]
Uploaded to GCI dashboard.

**Comment by SidharthBansal** [comment]
Published on gci dashboard

**Comment by anthony-zhou** [comment]
I have started to work on this issue. Interestingly enough, this issue now appears on both the online and offline versions for me. Perhaps this is a problem introduced by a new change that was already available locally but deployed online during the time span since this issue was first opened. Anyways, I will try to see what is causing this problem.
