### ISSUE TITLE
Overlays stay in the view when map is fully zoomed out (world view)

### ISSUE THREAD

**Issue by saadsaifse** [publiclab/Leaflet.DistortableImage#453]
**Describe the bug:**
I have a full zoom out button on my map, that zooms out to the world view. When I press that button, the loaded distortable overlays stays at their zoomed-in location until a scroll is applied.

**Reproduce the behavior:**
Overlay an image, zoom to the image location until the image is clearly visible. Then press the full zoom out button. The image will stay there while the map tiles will zoom out normally. Now scroll a little bit on the map to take the image to its original tile.

**Browser, version, and operating system:**

Tested on Chrome, Firefox -
Version: Chrome 77.0.3865.90, Firefox 69.0.1 (64-bit) -
Platform: macOS, haven't tried on Windows yet -

**Comment by themacboy** [comment]
Yes, innoticed that a few weeks ago

**Comment by jywarren** [comment]
Hi! I believe this was fixed by @anthony-zhou in https://github.com/publiclab/Leaflet.DistortableImage/pull/517 ! Can you test the latest to confirm? Thank you!

Feel free to re-open if it's not fixed. 🎉
