### ISSUE TITLE
Last release in npmjs.com is v0.8.4 and here is v0.7.4... Which one is good one?

### ISSUE THREAD

**Issue by flopail** [publiclab/Leaflet.DistortableImage#459]
**Describe the bug:**
- In **npmjs** web site, last version is **v0.8.4**: https://www.npmjs.com/package/leaflet-distortableimage
- In **pubiclab releases** repo, last version is **v0.7.4** : https://github.com/publiclab/Leaflet.DistortableImage/releases

Which one is good one?

**Reproduce the behavior:**
Follow these two links above.

**Browser, version, and operating system:**
 All.

**Comment by sashadev-sky** [comment]
Sorry! 0.8.4 is good :) When in doubt the npm package is always the most up to date. I will update the releases today, though. Thank you for pointing this out.

**Comment by sashadev-sky** [comment]
Just released v0.8.4 under releases (https://github.com/publiclab/Leaflet.DistortableImage/releases) so closing this
