### ISSUE TITLE
display Leaflet.Toolbar on right click (contextmenu)

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#46]
This as a possible workaround related to #30 (and a reasonable expectation of user in any case) - use the Leaflet event 'contextmenu' to display Leaflet.Toolbar on right click (or long press in mobile).

Just opening for debate :-)

**Comment by rexagod** [comment]
@jywarren Should we consider this approach over the current one?

**Comment by sashadev-sky** [comment]
Closing this one via #303 !
