### ISSUE TITLE
Not able to use the plugin

### ISSUE THREAD

**Issue by bjaggi-sag** [publiclab/Leaflet.DistortableImage#463]
**Scope**:
Installation, Code, API

**Description**:
Feel free to include any applicable: code, screenshots, or gifs.
When i include the library in my file and try to run a basic example. I am not able to run it as the browser console keeps showing the following error:
`
leaflet.distortableimage.js?20e9:1355 Uncaught (in promise) TypeError: Cannot read property 'Action' of undefined
    at eval (leaflet.distortableimage.js?20e9:1355)
    at Object../node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js (vendors~app.js:30535)
    at __webpack_require__ (bootstrap.js:64)
`
I checked in th code of the library it says that "L.Toolbar2" is undefined. So when i import 'leaflet-toolbar' in leaflet.distortableimage.js i am able to use it. But then the toolbar of the image overlay is not correctly visible. It gets highly scaled up. Can you please suggest how can i fix this.

**Comment by bjaggi-sag** [comment]
Here is a screenshot of the image overlay toolbar i see after i do the workaround.
![image](https://user-images.githubusercontent.com/48059198/69029460-46e02480-09d5-11ea-998c-27615c046323.png)

**Comment by bjaggi-sag** [comment]
The issue is resolved as on my framework one of the SVG .css properties was overriden.

**Comment by frontend210** [comment]
Hi @bjaggi-sag 
Could you please explain in detail how to resolve the kind of issue?

**Comment by bjaggi-sag** [comment]
Hi @frontend210 ,

I have to change the height and width property in the **.leaflet-container svg:not(.leaflet-zoom-animated)** Css class to **inherit** and it worked.

**Comment by frontend210** [comment]
Hi @bjaggi-sag Thanks for your help. I've resolved the issue on my side :)

**Comment by sashadev-sky** [comment]
@bjaggi-sag @frontend210 any chance you guys think this is related to https://github.com/publiclab/Leaflet.DistortableImage/issues/452 or have seen this problem as well?

**Comment by BrageKanKode** [comment]
For anyone else that has this issue, and changing the css class didn't work. I managed to solve this by adding a path to the css for leafletToolbar under 'styles' in angular.json.
`"./node_modules/leaflet-toolbar/dist/leaflet.toolbar.css"`
