### ISSUE TITLE
Disable box collector

### ISSUE THREAD

**Issue by adriankwiat** [publiclab/Leaflet.DistortableImage#466]
**Scope**:
API, documentation, installation, code, meta, other?
API

**Description**:
Feel free to include any applicable: code, screenshots, or gifs.
I want default box zoom instead of box collector. Is possible to disable it?

**Comment by sashadev-sky** [comment]
@adriankwiat you should now see this updated in version 0.8.8 on npm! 
and please reference the addition to the README instructions for swapping between them
