### ISSUE TITLE
Add meaningful return values for toolbar manipulation methods

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#469]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

#  Problem

We have toolbar manipulation methods `#addTool` `#removeTool` and `#replaceTool` for `L.DistortableImage.Edit`:

https://github.com/publiclab/Leaflet.DistortableImage/blob/0a162b57aac8be4644a878901567f306c3c006ee/src/edit/DistortableImage.Edit.js#L211-L238

Currently, the return results for them could be more purposeful.

# Solution

I think a good route to go would be to return false on failure like they already do, and the toolbar object itself on success to allow for chaining and more concise code. Open to other suggestions for a return value if you feel they would be better.

To complete:

- [ ] `addTool` needs a meaningful return value on success (undefined currently)
- [ ] `removeTool` needs a meaningful return value on success & failure (undefined currently)
- [ ] `replaceTool` needs a meaningful return value on success (undefined currently)
- [ ] document these return values in the README (just follow the current documentation pattern - see other tool related methods documented for reference)

This task is marked as `medium` because of the wide range of skills it touches on (code, doc, refactoring, etc.).

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
Published
