### ISSUE TITLE
Add prompt for multi-export scale AND/OR allow setting this in DistortableCollection constructor

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#471]
This seems to indicate we can set the scale in options:

https://github.com/publiclab/Leaflet.DistortableImage/blob/6e4b078eb83ddefa191a726be8a2671640897cba/src/edit/DistortableCollection.Edit.js#L194-L198

But we don't actually use that, here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/22cf32253e8030f52ba0620ed33d12a5149766da/src/edit/actions/ExportAction.js#L32

Can we make it possible to set the scale dynamically, either by opening a prompt (what if we said scale defaults to a prompt instead of 100?) or by allowing people to pass a function to determine the scale, as a DistortableCollection constructor option? cc @sashadev-sky what do you think?

**Comment by sashadev-sky** [comment]
@jywarren I think that was why we held off on docs for the exporter - we were still thinking about how we could make the function customizable without having to re-write the whole action like we did in MK. because we don't have any API for passing options to actions. So we would need to build that.

Also the prompt is really good idea. The prompt could be a GCI issue? The API for passing options to actions would probably be more of a longer consistent effort than a typical GCI task but could be a hall of fame?

**Comment by jywarren** [comment]
Yeah this could probably be a GCI issue! I think it's necessary to publish the new MapKnitter version, because with scale pegged to 100 px per cm, if you are mapping a large area like a city block, maps are HUGE files (15000 x 15000 px) and if you're mapping a small area like a garden, they're tiny... 300x300px.

Example of huge -- our exporter can handle this, which the legacy exporter cannot! This is about 15000x8000px:

http://mapknitter-exports-warps.storage.googleapis.com/1575518821/1575518821.jpg

So, we should set it to 100 by default but let people modify it. 

Later, we should make a rough calculation -- can we get the bounds of the collection? If so, we could do a rough suggested calculation to offer an initial export scale that generates a roughly 1000x1000px image. Note above it says `opts.scale = opts.scale || 100; // switch it to _getAvgCmPerPixel ! ` which would indeed offer a scaled suggested default!

But let's just get the basic prompt working first!

Could we just literally modify that line:

```js
   opts.scale = opts.scale || 100; // switch it to _getAvgCmPerPixel ! 
```

so instead of `100`, it's `prompt("Choose a scale or use the default (cm per pixel):", 100)` ?

That'd be a great initial step; later we can offer an override.

**Comment by jywarren** [comment]
Done in #478!
