### ISSUE TITLE
Document grunt tasks in README

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#499]
The Gruntfile.js has some very useful commands, including very critical ones like:

* `grunt concat:dist` - build the distribution files in `/dist/...`
* `grunt test` - run automated tests

Let's document those clearly near the top of the README!

**Comment by sharmamansi** [comment]
Hey @jywarren can I work on this?

**Comment by jywarren** [comment]
That would be great!

**Comment by sharmamansi** [comment]
Hey @jywarren im facin some issues while creating a pr can you help me?
![error](https://user-images.githubusercontent.com/44358571/72522454-bebab600-3883-11ea-9e82-9da4b29c91a4.png)

**Comment by jywarren** [comment]
Hmm. @VladimirMikulic did you get this when you committed? DO we need to fix these formatting issues, or is there a way to skip the lint checks?

Thanks!!

**Comment by VladimirMikulic** [comment]
@jywarren yes I get these every time, the workaround is to pass `--no-verify` option to the `git commit` command.

**Comment by sashadev-sky** [comment]
closing as we use webpack now!!
