### ISSUE TITLE
Enhance testing documentation

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/Leaflet.DistortableImage#506]
In many of our other publiclab repos, there is extensive documentation on how to correctly test the codebase.
It is very difficult for someone not acquainted with the tech stack or the code itself to run the tests.
For example, if a user runs `npm test`, the command executed is:
`echo \"Error: no test specified\" && exit 1`.
This just returns an error but doesn't give the user any information on how he can actually specify a test to have it run. Instead we could link to our documentation.
 
What do you think?
Is this a good idea?

**Comment by jywarren** [comment]
Agreed, this would be awesome!

**Comment by Uzay-G** [comment]
Yeah I think it would be useful. I'd love to work on it but I'm not familiar with the codebase for this repository.
