### ISSUE TITLE
Making sure the toolbar stays in viewport during image drags on zooming in

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/Leaflet.DistortableImage#516]
We have [this](https://codein.withgoogle.com/tasks/5154109926146048/?sp-organization=5664911678504960&sp-is_beginner=False&sp-search=medium) task on the GCI dashboard. Toolbar always has to be visible.
@sashadev-sky @rexagod @jywarren do you have something like this in mind?

![Screenshot_20200109_154115](https://user-images.githubusercontent.com/35997844/72077333-5b66dc00-32f7-11ea-9aa6-daf598501820.png)

![Screenshot_20200109_154305](https://user-images.githubusercontent.com/35997844/72077346-602b9000-32f7-11ea-9bba-180e11b19eaa.png)

**Comment by theprover97** [comment]
Hey @VladimirMikulic , can I work on this issue?

**Comment by VladimirMikulic** [comment]
@theprover97 if @sashadev-sky agrees on this type of layout, it's all yours :)

**Comment by DevanshCodes** [comment]
Is it still open, can I work on this?

**Comment by VladimirMikulic** [comment]
Hi @DevanshCodes. Thank you for your interest on this issue, but we are still waiting for @sashadev-sky's approval.

**Comment by sashadev-sky** [comment]
Sorry everyone to just reply now!!
@VladimirMikulic This has come up a bunch of times in discussion with @jywarren @rexagod and I. We considered your layout in the past but concluded we want to keep the toolbar attached to the image always. There is also to consider what will do in the scenario of multiple images.

I think what we could do is if the toolbar goes offscreen, add some logic to flip it to a different side of the image. What are your thoughts on that?

Open to any other ideas if you have! Have been thinking about this for a while
