### ISSUE TITLE
Circles not tracking with image

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/Leaflet.DistortableImage#52]
The circles that are supposed to be on the coners of my picture are not tracking with my image. I'm using Firefox with a Linux OS

![screenshot](https://cloud.githubusercontent.com/assets/7490478/8369313/170fed62-1b7d-11e5-9531-19f753a0752c.png)

**Comment by rexagod** [comment]
@steviepubliclab I'm unable to reproduce this issue on the same settings, can you please check if this issue still persists? Thanks!

**Comment by sashadev-sky** [comment]
closing because this is stale!
