### ISSUE TITLE
Make collection export option dynamic

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#522]
If you run an export here with two images: https://sasha.mapknitter.org/examples/select.html, and then cancel it by clicking on the icon (just to save time), and then run a new export on only 1 image, you'll find that it still says exporting 2 / 2 images. 

Since we call 
https://github.com/publiclab/Leaflet.DistortableImage/blob/449ec1506fb3c1a3cb624be52be8c7ade6538216/src/edit/DistortableCollection.Edit.js#L320

and save it back into the opts object, the next time it wont recall it and will keep re-using the same group of images. 

quickest solution would be to just update the line to:
```
 opts.collection = this._group.generateExportJson();
``` 

but then custom collections wouldn't be possible anymore. 

Waiting to call the function until inside the method would also work, but there seems to be issues with the `this` binding so would have to fix that

**Comment by sashadev-sky** [comment]
@jywarren this one is high priority too because breaks the exporter. I don't have the time to fix it right now

**Comment by jywarren** [comment]
Gotcha, thanks!!!!!

**Comment by sashadev-sky** [comment]
**Uploaded to GCI dashboard**

**Comment by SidharthBansal** [comment]
Published
