### ISSUE TITLE
Fix coverage grunt task from Gruntfile.js

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#537]
- Currently the `coverage` folder is created outside of the repository in its parent folder.
   1. Create it in the repository directory
    2. Possibility to collapse inner Phantom folder that holds all the files we need so its just coverage/~phantom~/files

also other potential followups for webpack config:
  - add `compress: true` to devServer to enable GZIP compression?

**Comment by sashadev-sky** [comment]
@jywarren @VladimirMikulic @rexagod

**Comment by VladimirMikulic** [comment]
It doesn't really make sense to compress assets in development server.

It will just slow it down, hence development server, not the production one :)

**Comment by sashadev-sky** [comment]
Wont it speed up page load, though, hence a faster development experience and one that is closer to the production experience? (FYI always here to learn so don't be shy to tell me i'm wrong)

**Comment by VladimirMikulic** [comment]
@sashadev-sky I am glad you ask. 
I agree with you up to the point, the bandwidth will be saved, but we are putting the load on the processor.
Again, if you have i7 it doesn't matter, but if you are on Athlon Dual Core it does for sure.
The same applies to the network :)

`hot` option serves this purpose, update the changes without browser reload.

The usual practice is to compress on the final build, but if insist I'll enable it.
