### ISSUE TITLE
Refactor code to eventually remove jquery dependency - part 1

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#538]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## Problem

**What happens:**

`JQuery` is the 2nd biggest resource we are pulling in (first is `Leaflet.js`), slowing down page loading time and we barely even use it.

## Solution

Let's start refactoring any jQuery find in the code base to vanilla JS. In this issue, we will tackle the below code. Please refactor the ajax  implementation to use XHR or fetch instead. 

https://github.com/publiclab/Leaflet.DistortableImage/blob/e0b51303151565dda66e075653c328f488acf169/src/edit/DistortableCollection.Edit.js#L260-L346

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sifihog** [comment]
Hello,
I'd like to give this a try, if possible. I've not worked on any open source projects before.

**Comment by Odisseuss** [comment]
Hello @sashadev-sky, has anyone taken up this issue yet?

**Comment by carlo-ev** [comment]
Hey I want to give this issue a go, would be my first open source contribution. Hope its open still didn't see it on pull requests.

**Comment by sabina-rohman** [comment]
Hi, I am new to open source contributions. Please, assign it to me if it's not assigned to anybody. Thanks.

**Comment by sashadev-sky** [comment]
hi @sabina-rohman thanks for your interest! @carlo-ev has opened a PR but hasn't replied to the review in 12 days so you can give it a try if you're still interested!
