### ISSUE TITLE
Do not warn about css transform 3d on IE10

### ISSUE THREAD

**Issue by mattiamanzati** [publiclab/Leaflet.DistortableImage#54]
Since IE10 supports css 3d transforms, I tried it and we should add IE10 to the is3d boolean check in the domutils

**Comment by jywarren** [comment]
+1! It worked in ie 10?

**Comment by mattiamanzati** [comment]
I tried it on IE10 mobile and IE10 with emulation mode and it worked! :D

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Would you be able to submit a pull request of this change?

**Comment by jywarren** [comment]
I believe it'd be a change in https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/util/DomUtil.js#L3 and https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/util/DomUtil.js#L28

Do you know the `L.Browser.xxxx` term for IE 10?

**Comment by imasaka1117** [comment]
Hi
i try this issues
i get the answer
ie css 3d in leaflet L.Browser is ie3d
so anwser is L.Browser.ie3d
i let the anwser in code line 3 and line 28
thanks your code 
this function is amazing

**Comment by jywarren** [comment]
Hi, Imasaka -- great, `L.Browser.ie3d` - do you have this in your repository, and could you create a pull request? Thanks!

**Comment by jywarren** [comment]
I did it and am closing this issue, thanks!
