### ISSUE TITLE
Update GitHub releases

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#567]
Good morning,

I just updated my tools with the last version you post in dist folder and I was surprised to see Handlers stop working for me.

Then I have tryed to go to releases to dowload previous version, till find when the problem start and i noticed that last released version is 0.8.4. But in NPM you can find 0.12.2

It is possible to update releases in github to easelly select the desired version?

Thanks in advance

**Comment by themacboy** [comment]
finally used JSDelivr to get previous version. Never used before hehehe

**Comment by sashadev-sky** [comment]
yes sure! I can be slow to update new releases because I like to dole out credit where it was earned so takes a little extra time! But will get this done

**Comment by sashadev-sky** [comment]
@themacboy done :)

**Comment by themacboy** [comment]
Love all you !
