### ISSUE TITLE
Handler are inactive after update to version 0.11.4 or greater ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#568]
Good morning,

i have tryewd to update to last version when I have noticed that from version 0.11.4 or greater handler stop working. I can't rotate, drag or other.

Not sure if there was a big change in API or it is a bug. Not sure what changed in every version.

Here a video:

https://youtu.be/hIFUD6ESCbQ

No error in console. No sure whats the problem all goes fine before.

**Comment by VladimirMikulic** [comment]
Hi @themacboy! Thank you for reporting this issue. Is your project open source/hosted here on Github? I am willing to help you resolve this. There were no breaking changes to the API, so it should work.

**Comment by sashadev-sky** [comment]
also just for a double check, I see in #567 the last version you checked was 0.12.2, would be great if you can double check you are having the same problem on 0.12.6 (latest release)

**Comment by themacboy** [comment]
Sorry was a Typo error, I would say version 0.12.6. sorry

**Comment by themacboy** [comment]
@VladimirMikulic no sorry I don't use any repository. Still learning how github works.

But as explained the problem comes  when I override this lib file with a version 0.11.4 or greater.

But im not sure hoy to check what changed after certain 0.11.3.

I load file using cdn

**Comment by sashadev-sky** [comment]
So you tried 0.12.6 and no dice? What platform and browser/ browser version are you using?

To help debug, try grabbing some more information on the handlers. Do you know how to access your image in your development console are run some methods from the API to see whats going on? I would check
- `img.editable()` should return true
- `img.isSelected()` should return true
- `img.getMode()` - should return the mode of the current handles you are seeing.

Is it all the handles or just the rotate ones?

Last, check if the `edit` event fires when you drag the image handle. It should be.
