### ISSUE TITLE
After webpack ... icons management will be receive any change?

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#577]
Hello ! After webpack adoption in this project im not sure if you will follow using grunt icon to manage all svg icons inside the project.

I refer to sprite generation, currently we were using grunt, grunt-svgmin and grunt-svg-sprite.

Can you explain me the current situation and the future way.

Thanks in advance !

**Comment by themacboy** [comment]
I have tryed to use "grunt icons" and he can't find my new svg. Not sure if you removed some config file of grunt

**Comment by sashadev-sky** [comment]
@themacboy grunt is a task runner besides just a way to bundle our code, so in the mean time I think we'll just continue with using grunt to manage it. Thanks closing this!
