### ISSUE TITLE
mapknitter in firefox slow save image

### ISSUE THREAD

**Issue by fiestin** [publiclab/Leaflet.DistortableImage#58]
Takes long time to show changes after refresh. If I open the map in Safari it shows the changes, while in firefox it can refresh a few time with the older version.

**Comment by GuidoS** [comment]
Would love to help out on this one, can you please share reproducible steps and urls. Thanks

**Comment by fiestin** [comment]
I tried it now and it worked, I changed one image and refreshed and it saved the changes. So it might be a result of slowness in my Firefox.
http://mapknitter.org/maps/katamon-2

**Comment by jywarren** [comment]
If the slowness is not consistent on Mapknitter, it seems likely that there is something else going on on your computer that's unrelated. I'd like to close this unless (or until) you can demonstrate reproducible steps that have a clear link to this code and to firefox, if that's OK.
