### ISSUE TITLE
Update L.TrigUtil method creation to ES6 syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#587]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/Leaflet.DistortableImage/issues) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We just added support for ES6 in our library, and would like to start transitioning our code to use this syntax.

Let's update the method creation syntax in the `src/util/TrigUtil.js` file from ES5 to ES6.

## Solution

**Where to find the relevant lines of code**: 

For the 3 functions in `src/util/TrigUtil.js`, remove the `function` keyword and attach the method arguments to the method name instead.

Here is an example of how this will look for one of the methods, the rest should follow suit:

ES5
```JS
radiansToDegrees: function(angle) {
  return (angle * 180) / Math.PI;
},
```
ES6
```JS
radiansToDegrees(angle) {
  return (angle * 180) / Math.PI;
},
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by kriti16** [comment]
@sashadev-sky Please assign it to me

**Comment by CasColucci** [comment]
Hey! Would I be able to give this one a shot?

**Comment by sashadev-sky** [comment]
@CasColucci yes go for it! i'll assign you now :)

**Comment by DrewStableBoi** [comment]
I'd love to also work on this if possible. I know it was already assigned, but just as a back up :)

**Comment by sashadev-sky** [comment]
@DrewStableBoi planning on opening some issues really similar to this sometime today, would you like me to assign you to one?

**Comment by iAmmar7** [comment]
@sashadev-sky can you assign me one? I'd love to try and contribute.

**Comment by sashadev-sky** [comment]
@iAmmar7 you can take #582 since the user has not responded in a week, I have assigned you there.

**Comment by romance939913** [comment]
Hi @sashadev-sky - First time contributor here as well. I'd like to take a task similar to this if one comes up. Thanks in advance!

**Comment by sashadev-sky** [comment]
@romance939913 awesome! you can take this one because it's been a week. I'll assign you now

**Comment by romance939913** [comment]
Hi @sashadev-sky - Just tried to commit and push my branch and it returned "permission denied" unable to access the repo with a 403 error. How to I gain access to push my branch?

**Comment by sashadev-sky** [comment]
@romance939913 are you sure you're working on your fork and not directly to this repo? You can check by running `git remote -v` the output should have your username in it, for ex. mine is `git@github.com:sashadev-sky/Leaflet.DistortableImage.git`

**Comment by romance939913** [comment]
Ah yes you were correct! I'll have a PR for you to review in a few minutes @sashadev-sky

**Comment by romance939913** [comment]
Hi @sashadev-sky This PR is ready for Review,

Quick question however, in the PR body where it says "tests pass -- look for a green checkbox" - does that mean it wants my code to pass some specs written somewhere?? Or Just make sure there aren't any merge conflicts.

Thanks in advance!

**Comment by romance939913** [comment]
Hi @sashadev-sky - Is this PR able to be merged? Looks good on my end

**Comment by charsides** [comment]
Hey, please can I give this a go? I'm new to open source projects :-)

**Comment by gjagnoor** [comment]
@sashadev-sky - Will you be able to assign me to an issue, please? I'm new to open source and would love to tackle one :)

**Comment by romance939913** [comment]
Hi @sashadev-sky  - Not sure if you're inactive, or I should reach out to someone else, however I believe the PR i opened is ready to be merged. Let know what you think. Thanks!

**Comment by sashadev-sky** [comment]
@charsides would you like to work on this one it has been abandoned (totally my fault bc I was inactive for so long sorry @romance939913 !!!)

**Comment by sashadev-sky** [comment]
@gjagnoor

**Comment by javed24** [comment]
hi @sashadev-sky any chance I could contribute to this one? I'm new to contributing to open source and would love to help with this. Thanks!

**Comment by sashadev-sky** [comment]
@javed24 would love your help! Assigning you now

**Comment by javed24** [comment]
> @javed24 would love your help! Assigning you now

thanks @sashadev-sky ! I'm on it. Will keep you posted 👍
