### ISSUE TITLE
Safari: some images appear transparent of distorted

### ISSUE THREAD

**Issue by fiestin** [publiclab/Leaflet.DistortableImage#59]
<img width="1242" alt="screen shot 2015-09-09 at 11 41 59" src="https://cloud.githubusercontent.com/assets/4379825/9757216/d8ae86c2-56e7-11e5-91b5-f87d66d93ace.png">
I think this happens with the separation between map and base layer, when zooming in and out in particular zoom points images are distorted.

**Comment by GuidoS** [comment]
Can you please include a url to check against?

Also, if the issue you are describing is about the transparent background, that is true in other browsers and I believe is correct for this project.

**Comment by fiestin** [comment]
here is a URL
http://mapknitter.org/maps/katamon-2#

**Comment by gauravano** [comment]
Hi @fiestin, @GuidoS is right and the transparent background is used in the project. I checked the URL and found nothing suspicious. 

@jywarren please do one more check.

I am closing this issue for now and feel free to update/reopen the issue or comment if you think the issue is misunderstood by us. Thanks!

**Comment by gauravano** [comment]
I ran the link using https://app.lambdatest.com/viewer/TES100961201549409707658960 to get Safari simulation and got a little suspicious on the image. Let's keep it open and wait for Jeff to confirm :confused:

**Comment by jywarren** [comment]
Hm, i'm also not sure -- let's close but if @fiestin can help us understand what's the behavior that's unexpected and what we should be looking for, we can re-open. Thanks!

**Comment by fiestin** [comment]
I went back to the issue and I have no recollection of the problem... Sorry.
I also went in the link and I don't see it happening. So I think it can be
closed? Thanks.

**Comment by gauravano** [comment]
No issue @fiestin as the issue is quite old so it's fine. Although, thanks for checking :smiley: .

**Comment by fiestin** [comment]
Sure :)

**Comment by jywarren** [comment]
Hi Hagit!!!! <3

**Comment by fiestin** [comment]
Jeff!! Miss you <3
