### ISSUE TITLE
addToolbarItem() to enable custom features

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#62]

**Comment by rexagod** [comment]
@jywarren Should we close this as I think this is addressed in #149? What do you think?

**Comment by sashadev-sky** [comment]
I am going to keep this on open because it reminds me to add defaults icon options for Rotate and Scale. Also its not done yet - have to hash out the custom feature API next.

**Comment by sashadev-sky** [comment]
this one is ready for close now!
