### ISSUE TITLE
How do I import this to an Angular project?

### ISSUE THREAD

**Issue by ZenMinz** [publiclab/Leaflet.DistortableImage#622]
Hi,
I tried using this line to add this to an Angular project:
`import 'node_modules/leaflet-distortableimage/dist/leaflet.distortableimage.js';`

but i kept getting this error.
![image](https://user-images.githubusercontent.com/39125801/79492874-f93f1500-8063-11ea-99cc-5f790d89941c.png)

Please help thank you.

**Comment by hansbrito** [comment]
Hi @ZenMinz How did you worked with this library in Angular ? Can you share you solution ? Thanks!
