### ISSUE TITLE
Travis build taking up to 3 rebuilds to pass

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#625]
Travis build taking up to 3 rebuilds to pass - currently the rebuild needs to be run manually. I suspect the issue is with Phantom JS or some other dependencies that need updating. I'm thinking 1) try to fix it (might need to be a major testing update) or 2) make it retry automatically 
@jywarren @VladimirMikulic

**Comment by VladimirMikulic** [comment]
As a short-term fix, it can rerun on the failed build.
