### ISSUE TITLE
"Can't find variable L" for index.html

### ISSUE THREAD

**Issue by ryangdar** [publiclab/Leaflet.DistortableImage#688]
Hi, 

I am trying to run DistortableImage using the index.html in the documentation. I cloned the repo and created a local server on the computer. However, we I run it in the browser I get the following error message: "Can't find variable L" What do I need to change in the index.html file to make this work? Thanks!
<img width="1456" alt="Screen Shot 2020-07-16 at 10 17 19 PM" src="https://user-images.githubusercontent.com/20191700/87751313-9a984d00-c7b2-11ea-9310-c3f4605fd8cd.png">

**Comment by tannerdolby** [comment]
Have you tried running `npm run setup` to install dependencies & build dist files then run `npm run serve:dev` to run the webpack development server? I'm curious as I can't recreate your issue even by starting a local live server and opening `index.html`.

Make sure to view [CONTRIBUTING.md](https://github.com/publiclab/Leaflet.DistortableImage/blob/main/CONTRIBUTING.md) to ensure you've performed the proper setup.

**Comment by ryangdar** [comment]
That solved the issue! Your help was very much appreciated

**Comment by tannerdolby** [comment]
Ok great!
