### ISSUE TITLE
Broken downstream tests in MapKnitter when bumping from v0.11.6 to v0.19.7

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#709]
Hi all, just wanted to note that something in a recent release has broken tests in Mapknitter, downstream: 

https://github.com/publiclab/mapknitter/pull/1379

I'd like to request that we address this in LDI as we haven't released a breaking change version bump, and in general it's good practice. Let's figure out what's happened! Any help much appreciated, it'll be great to get these new changes and improvements published onto MapKnitter!

cc @sashadev-sky @rexagod and @publiclab/mapknitter-reviewers ❤️ 

Hope you're all well!

**Comment by sashadev-sky** [comment]
@jywarren I opened a PR for this in mapknitter! https://github.com/publiclab/mapknitter/pull/1395

**Comment by sashadev-sky** [comment]
resolved https://github.com/publiclab/mapknitter/pull/1395!
