### ISSUE TITLE
Doesnt work with leaflet 1.1

### ISSUE THREAD

**Issue by viswanathamsantosh** [publiclab/Leaflet.DistortableImage#72]
This component doesnt work with leaflet 1.1. Getting errors in console.

**Comment by jywarren** [comment]
What errors, can you post them? There are efforts to get this working in 1.0 which could address this in https://github.com/publiclab/Leaflet.DistortableImage/issues/64 and https://github.com/publiclab/Leaflet.DistortableImage/pull/65 -- do you have any ability to help out in making these changes? We'd dearly appreciate the assistance!

**Comment by viswanathamsantosh** [comment]
PFA.
![distortimage](https://user-images.githubusercontent.com/3799600/29649394-6b076e92-88b1-11e7-8b86-a618c33249fc.png)

**Comment by viswanathamsantosh** [comment]
I'm not a geek coder but i m totally up for it if i can be any help. :)

**Comment by viswanathamsantosh** [comment]
I just replaced the leaflet-src.js and leaflet.css with 1.1 versions
```

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.1.0/dist/leaflet.css"
   integrity="sha512-wcw6ts8Anuw10Mzh9Ytw4pylW8+NAD4ch3lqm9lzAsTxg0GFeJgoAtxuCLREZSC5lUXdVyo/7yfsqFjQ4S+aKw=="
   crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.1.0/dist/leaflet.js"
   integrity="sha512-mNqn2Wg7tSToJhvHcqfzLMU6J4mkOImSPTxVZAdo+lcPlk+GhZmYgACEe0x35K7YzW1zJ7XyJV/TT1MrdXvMcA=="
   crossorigin=""></script>
```

**Comment by jywarren** [comment]
Possible fix in #64 at the end of the comments... which would be added on top of the initial fix in #65 -- if you can test those out together, great, else I'll try to over the next hour.

**Comment by jywarren** [comment]
Hi, can you test out whether the release I just made (bumped to v0.1.0) works in Leaflet 1.1?

**Comment by jywarren** [comment]
Actually confirmed it works in up to leaflet `v1.2`! Though I don't see the leaflet-toolbar anymore... so perhaps we need to open an issue over there -- https://www.npmjs.com/package/leaflet-toolbar

**Comment by viswanathamsantosh** [comment]
Hey @jywarren, this is working with 1.1 as well. thank you. :)

**Comment by jywarren** [comment]
Hi, one more issue required here to get full v1.1 compatibility: #78 highlights some issues with the new Leaflet.Toolbar, also just released, as the toolbar seems broken as of the v1.x compatibility fixes mentioned above.

Any help there appreciated to bring this lib up to full v1.0 Leaflet compatibility!
