### ISSUE TITLE
Update testing framework to one that doesn't require a real browser

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#735]
We currently use `karma` as our main framework and would like to consider updating to a framework that does not require an actual browser for testing, so that we don't need to work around browser security issues regarding sandbox. 

Open to any framework suggestions that the contributor is interested in implementing, but a great example of an implementation we can emulate in this project can be found at https://github.com/publiclab/image-sequencer.

This will also allow us to re-implement support for Gitpod checks on PRs.
@jywarren @rexagod @rexagod @MLefebvreICO

**Comment by jywarren** [comment]
Hi Sasha - sorry, i should've replied here -- https://github.com/publiclab/Leaflet.DistortableImage/pull/716#issuecomment-692987230

> I believe `--no-sandbox` is standard usage for headless chrome, so I'd appreciate adding that back in! The Gitpod integration in #680 is really really useful and i think critical for both broadening our contributor base and also for manually testing out PRs. 

> You can read about `--no-sandbox` here and it also offers a workaround -- https://developers.google.com/web/updates/2017/04/headless-chrome#faq and https://github.com/theintern/intern/issues/878#issue-295257724

I've re-added the `--no-sandbox` option in #750, but if you have more research showing that `--no-sandbox` is a security issue in the context of Karma or Jest testing, or more discussion you can link to for context, i'm happy to discuss! Thank you!

**Comment by sashadev-sky** [comment]
@jywarren so in Google's documentation of it, they write they don't recommend using `--no-sandbox` to fix the issue we were experiencing running tests in gitpod, and offer up 2 alternative suggestions. I looked into both of those and unfortunately, Gitpod would not support either of them because you need admin privileges to "Enable user namespace cloning" or "Setup setuid sandbox", and these privileges cannot be granted in a running Gitpod container.

I don't think its an issue in itself in our testing context, but my understanding is that it leaves an opening to potentially become one, and having it run by default for any contributor that clicks the Gitpod link might be something to avoid in case the contributor doesn't want to run it.

I haven't tried the suggestion here: https://github.com/GoogleChromeLabs/lighthousebot/blob/master/builder/Dockerfile#L35-L40 so maybe worth it to check that out

**Comment by sashadev-sky** [comment]
actually nevermind, I think that option would face the same issues with admin privileges
