### ISSUE TITLE
Select not firing on click event 

### ISSUE THREAD

**Issue by johnksv** [publiclab/Leaflet.DistortableImage#747]
**Describe the bug:**
What happened: 
Clicked DistortableImageOverlay, nothing happened/edit mode didn't trigger.
Drag DistortableImageOverlay, nothing happened.

 If `selected:true` is passed as option I can manipulate the image until it is deselected. After this the image is not able to select again.
From my investigations it seems that the on click listener that should call select is not triggered (code: https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/DistortableImageOverlay.js#L68 ).
Instead, deselect is triggered every time (code: https://github.com/publiclab/Leaflet.DistortableImage/blob/main/src/DistortableImageOverlay.js#L80)

Expected: 
The DistortableImageOverlay should be (selected and) editable.

**Reproduce the behavior:**
 Steps to reproduce the behavior. (ex. 1. Go to... 2. Click on... 3. See error...)

Code sandbox: https://codesandbox.io/s/quirky-jang-rpw8i?file=/src/index.js
GIF
![Screen Recording 2020-09-12 at 21 06 42](https://user-images.githubusercontent.com/10381866/93003226-3b01b800-f53d-11ea-8646-2dc97e824c27.gif)

**PS:** I was not able to reproduce the bug when running the example in this repo (`npm run serve:dev`). Am i missing a dependency or something?

**Browser, version, and operating system:**
Tested in two browsers:
 - Browser [e.g. chrome, safari] - Brave
 - Version [e.g. 22] - 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
 - Platform: [e.g. iOS, windows] - macOS Catalina

And:
 - Browser [e.g. chrome, safari] - Firefox 
 - Version [e.g. 22] - 80.0.1
 - Platform: [e.g. iOS, windows] - macOS Catalina

Side note: Thank you for a great leaflet plugin!

**Comment by tettusud** [comment]
@johnksv I was facing the same issue too ,but including vendor.js solved it (the file is in the same director like leaflet-distortableimage.js , give a try

**Comment by johnksv** [comment]
This solved it. Thank you very much.
