### ISSUE TITLE
offer example using Google base layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#81]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

With the `googleMutant` plugin- https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

Here's an example of an implementation!

https://github.com/jywarren/mapknitter/blob/88bd8bd3b01cb61d3ca0883d463b2361ea2e67a5/app/assets/javascripts/mapknitter/Map.js#L489-L500

It'd be great to copy the basic `index.html` example to one called `google.html` and add this layer: https://github.com/publiclab/Leaflet.DistortableImage/tree/master/examples

We'd love some help with this one. Thanks!

**Comment by SK1723** [comment]
@jywarren can I work on this as a first time contributor?

**Comment by jywarren** [comment]
Oh, that'd be great! Please open a PR and we can help you out!

On Sep 7, 2018 9:40 PM, "Sneha Kumar" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> can I work on this as a first time
contributor?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/Leaflet.DistortableImage/issues/81#issuecomment-419603556>,
or mute the thread

**Comment by sashadev-sky** [comment]
@jywarren resolving this one so it can go along with #315 !
