### ISSUE TITLE
enlarge corner handles on mobile/tablet 

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#82]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab.org/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

For fingertip use, the basic circle controls are a bit small: https://publiclab.github.io/Leaflet.DistortableImage/examples/

The icon itself is a data-url, here:

https://github.com/publiclab/Leaflet.DistortableImage/blob/11852f2fc902abef878b7c1a8ef7c22fd7072bc0/src/edit/DistortHandle.js#L5-L7

1. [ ] To replace it, let's find a new one at 2x the size (so 32x32), and post it in a comment here. 
2. [ ] Then we'll make a data-url from it with https://dopiaza.org/tools/datauri/index.php
3. [ ] then we can paste that into the file above and double the other dimensions too.

****

Follow-up: Not sure, but offset may also need to be changed -- 10 is 1/2 the icon width?

https://github.com/publiclab/Leaflet.DistortableImage/blob/4f4011d159b7fbf00e671b50a7b5f85a2dc7dba2/src/edit/EditHandle.js#L13

**Comment by John905** [comment]
@jywarren , I'll give this one a try if it's ok with you.
![iconcircle](https://user-images.githubusercontent.com/36971784/37547727-09fe94e4-2939-11e8-8a22-fdd9369ad728.png)

**Comment by jywarren** [comment]
That'd be super, thank you! Do you use Leaflet DistortableImage yourself?
Just curious!

**Comment by John905** [comment]
Cool – I haven’t used it before, I’ll have to play with it a bit.

**Comment by John905** [comment]
Hey @jywarren , I enlarged the handles and they look ok.  I haven't done anything with the zIndexOffset because I'm not sure what to do.  Are you concerned the larger handles will cover something that wasn't covered before?  Do you want me to push what I have so you can take a look at it?

**Comment by jywarren** [comment]
Sure, let's open a PR, thanks! Can you post a screenshot too?

Awesome!

**Comment by John905** [comment]
![leafletlgrhandles2](https://user-images.githubusercontent.com/36971784/37571571-01d81844-2ac4-11e8-9e2f-7dd6216c2e29.jpg)
Looks like I missed the commit step earlier, but I think it's ready now.

**Comment by jywarren** [comment]
Oh wow this looks great. And the "clickable" regions work normally? It was
a while ago this code was written but I thought the radius segments could
have been for positioning icons and/or defining the clickable regions. Can
you drag these when clicking on their outside edges?

Thanks!

**Comment by John905** [comment]
I'll have to do some testing...

**Comment by John905** [comment]
Yes, you can click the outer edges of the circle to drag.  If you approach it from the lower left, it looks like you can click it from outside the circle, but I assume that has to do with the actual location of the mouse pointer and the appearance of the mouse icon.

**Comment by jywarren** [comment]
OK, that sounds great, then! I'll merge it in. Thanks so much! We'd love your help with other issues if you're interested!

**Comment by jywarren** [comment]
OK, over at #88 --

**Comment by jywarren** [comment]
Super! 👍 👍 👍

**Comment by jywarren** [comment]
For example perhaps #83 would be interesting, although a bit more complex... thanks!
