### ISSUE TITLE
build in full-resolution image export using webgl-distort

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#83]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

https://github.com/jywarren/webgl-distort -- there's example code there! However, we'll need to be able to reference the original quality image -- we're currently doing this now in MapKnitter but we should build this function into this library itself, as it's a common desire: 

https://github.com/publiclab/mapknitter/blob/8d94132c81b3040ae0d0b4627e685ff75275b416/app/assets/javascripts/mapknitter/Map.js#L47-L82

Making this a button in the menu would be great -- button code is here; this excerpt is a single button on the menu:

https://github.com/publiclab/Leaflet.DistortableImage/blob/3714b06bcdae2ff088c1f52c32ec322d120b4962/src/edit/DistortableImage.EditToolbar.js#L12-L25

Any help much appreciated! This could be broken into several pieces for first-timers, possibly.

**Comment by John905** [comment]
I'll give this one a try.

**Comment by jywarren** [comment]
awesome, thank you!!!

**Comment by John905** [comment]
Hey, I just got back to this yesterday and I'm having a problem with dependencies.  I went ahead and put webgl-distort in src/edit, but even then I have to use window.webgl-distort to get Grunt to pick up the reference.  Maybe one file isn't a big deal, but then there's glfx and that's quite a bit more.  Should I just force it through and see what happens or am I missing something?  package.json does have the dependencies for both projects but Grunt doesn't seem to see them.

**Comment by jywarren** [comment]
Hi! Hmm, could you open up a PR so I can see exactly where you're putting things? I think we could include `webgl-distort` in the HTML, then rely on it being in the global namespace... but let's see!

Thank you!!!

**Comment by John905** [comment]
Another question: should warpable.rb be included or should I being snipping it out?

**Comment by jywarren** [comment]
Hmm, from which line?

**Comment by John905** [comment]
If you look at the mapknitter code it has references to warpables - those are defined in models/warpable.rb - at least that how it appears to me.  I was assuming we'd switch those for references in distortableimage.

**Comment by jywarren** [comment]
aha, yes -- the "warpable" in MapKnitter parlance is just an image, indeed.

**Comment by jywarren** [comment]
Hmm, can you console log out the coordinates and the pixel positions before
and after to compare ? Just to check the artithmetic. If any is zero, NaN,
things like that?

**Comment by John905** [comment]
ok

**Comment by John905** [comment]
Before:
<img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost/images/example.jpg" alt="" style="z-index: 1; transform: translate3d(901px, 394px, 0px) matrix3d(-0.466, 0, 0, 0, 0, 0.498667, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 0px 0px 0px;">

**Comment by John905** [comment]
"<img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost/images/example.jpg" alt="" style="z-index: 1; transform: translate3d(901px, 394px, 0px) matrix3d(-0.466, 0, 0, 0, 0, 0.498667, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 0px 0px 0px;">"

**Comment by John905** [comment]
Grr, sorry, html:
/<img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost/images/example.jpg" alt="" style="z-index: 1; transform: translate3d(901px, 394px, 0px) matrix3d(-0.466, 0, 0, 0, 0, 0.498667, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 0px 0px 0px;"/>

**Comment by John905** [comment]
img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost/images/example.jpg" alt="" style="z-index: 1; transform: translate3d(901px, 394px, 0px) matrix3d(-0.466, 0, 0, 0, 0, 0.498667, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 0px 0px 0px;"

**Comment by jywarren** [comment]
Maybe double check that these values change when you distort, and you could also log out the actual `webgldistort()` command parameters to confirm they're passed along.

Looking very close! Great work here! 👍 💪

**Comment by jywarren** [comment]
Just noting relation to https://github.com/publiclab/Leaflet.DistortableImage/pull/97
