### ISSUE TITLE
 keyboard command to delete image

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#98]
Via @steviepubliclab -- 

> I've had the problem multiple times where I'm running a workshop, or just trying to work in MK and we can't get the toolbar to show up. I can usually work around the with the commands, but there isn't a command for deleting an image which always seems to be a problem. Can we make one?

**Comment by jywarren** [comment]
To make this easier, here is the list of key commands -- we should add one for the delete key:

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.Edit.js#L7-L14

The delete key is `46` i think!

And this is the code that drives it!

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.Edit.js#L160-L167

Here's the code to delete an image: 

https://github.com/publiclab/Leaflet.DistortableImage/blob/dc9e64cc084b67bc9ce9c9b9fa72fefe30beac00/src/edit/DistortableImage.EditToolbar.js#L52-L54

However, perhaps we should be sure to use a javascript `confirm('Are you sure?)` in there!

**Comment by vsk4** [comment]
@jywarren  should I add 46 to the key map directly ? will it work ?

**Comment by jywarren** [comment]
I believe it will! Would love help!

**Comment by Rishabh570** [comment]
@vsk4 Are you on it? I would like to work on it if it's not in progress...

**Comment by vsk4** [comment]
@Rishabh570  go ahead

**Comment by sashadev-sky** [comment]
@Rishabh570 @jywarren Hi, I saw there was never a pull request for this so I went ahead and did it. Going to open a pull request in a minute but have some questions I will ask on there so any input is appreciated! Thank you

**Comment by jywarren** [comment]
This was completed by @sashadev-sky in https://github.com/publiclab/Leaflet.DistortableImage/pull/130 -- thank you!!! I've also opened up a set of new issues which we'd love help with 👍
