### ISSUE TITLE
Some handlers won't work ...

### ISSUE THREAD

**Issue by themacboy** [publiclab/Leaflet.DistortableImage#983]
**Scope**: code

**Description**:
Good morning, after three years I have updated the plug-in and I have noticed that there are different handlers that do not work, in my case specifically are the rotation and drag handlers.
As you can see in the video once the handler is selected it does nothing, just deselect the image.

I have attached a video where you can see the problem:

https://user-images.githubusercontent.com/8063711/174533932-dfb55173-5c4b-48d7-9235-497807331daf.mp4

I looked at the code to see if I understood the problem, but unfortunately I don't have enough code skill.

I would ask someone to help me understand, or how I found , why it is malfunctioning.

Thank you very much in advance.

**Comment by themacboy** [comment]
Tried to build from scratch, but same result.

**Comment by themacboy** [comment]
ummm I tried to go back ... and the last version that worked for me is:
Leaflet.DistortableImage-v.0.8.4

Will try to figure what changed in the nexts versions, that brokes all handlers and can't move o change images.

Any idea is welcome !

**Comment by themacboy** [comment]
I go through the commits and v0.9.0 still works for me.

Then got throught all commint in relaease v0.11.6, but in all them I get and error on due a missing missing functions in Toolbar.

Once reach the release v0.12.6 the toolbar works again but then, as explained at the beginning I can't drag, rotate, resize ... etc any handler works.

Sorry not sure why. Probably something related to the way I load this plug-in, due I use it in a old web page and I load as <script> tag.

... working on it

**Comment by themacboy** [comment]
found the problem, reported as a bug in #1007

**Comment by jywarren** [comment]
Thank you for reporting and investigating!
